// Differential parity suite: renders every case of the corpus in test/parity/expected
// (generated by test/parity/generate.py with Python Jinja2) and compares the result.
// Known divergences are listed in test/parity/divergences/<area>.txt; see test/parity/README.md.
// ParityWideTest renders the same cases through TemplateW and lists only the cases where
// the wide result differs from the narrow one, under a "wide." id prefix.

#include <jinja2cpp/filesystem_handler.h>
#include <jinja2cpp/template.h>
#include <jinja2cpp/template_env.h>

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <map>
#include <memory>
#include <set>
#include <stdexcept>
#include <sstream>
#include <string>
#include <type_traits>
#include <vector>

#ifndef JINJA2CPP_PARITY_DIR
#error "JINJA2CPP_PARITY_DIR must point to test/parity"
#endif

// Keeps the key order of the case files, so context dicts reach Jinja2C++ in the insertion
// order Python saw (nlohmann::json would sort them).
using Json = nlohmann::ordered_json;

namespace
{

// How the C++ result relates to the Python one.
enum class Outcome
{
    Match,       // same output, or both report an error
    Output,      // both render, outputs differ
    Rejects,     // C++ reports an error, Python renders
    Accepts,     // C++ renders, Python reports an error
    Unsupported, // the case needs an Environment option Jinja2C++ does not have
};

const char* OutcomeName(Outcome o)
{
    switch (o)
    {
    case Outcome::Match:
        return "match";
    case Outcome::Output:
        return "output";
    case Outcome::Rejects:
        return "rejects";
    case Outcome::Accepts:
        return "accepts";
    case Outcome::Unsupported:
        return "unsupported";
    }
    return "?";
}

struct Divergence
{
    std::string kind; // an OutcomeName, or "crash" for cases that must not run
    std::string task;
    std::string reason;
};

struct ParityCase
{
    std::string id;
    Json data;

    friend std::ostream& operator<<(std::ostream& os, const ParityCase& c) { return os << c.id; }
};

std::string ReadFile(const std::string& path)
{
    std::ifstream in(path, std::ios::binary);
    std::ostringstream os;
    os << in.rdbuf();
    return os.str();
}

// expected/index.json lists the areas, so adding cases/<area>.py needs no C++ change.
const std::vector<std::string>& AreaNames()
{
    static const std::vector<std::string> areas = [] {
        std::vector<std::string> result;
        auto text = ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/expected/index.json");
        if (!text.empty())
            result = Json::parse(text)["areas"].get<std::vector<std::string>>();
        return result;
    }();
    return areas;
}

std::vector<ParityCase> LoadCases()
{
    std::vector<ParityCase> cases;
    for (auto& area : AreaNames())
    {
        auto text = ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/expected/" + area + ".json");
        if (text.empty())
            continue; // reported by ParityRegistry.CorpusPresent
        auto doc = Json::parse(text);
        for (auto& c : doc["cases"])
            cases.push_back(ParityCase{ c["id"].get<std::string>(), c });
    }
    return cases;
}

// The area a case id belongs to: "wide.literals.dict" and "literals.dict" are both "literals".
std::string AreaOf(const std::string& id)
{
    const auto start = id.compare(0, 5, "wide.") == 0 ? 5 : 0;
    return id.substr(start, id.find('.', start) - start);
}

// Allow-list lines that cannot be used as they are: an id listed twice, or listed in the
// file of another area. Reported by ParityRegistry.DivergencesAreWellFormed.
std::vector<std::string>& DivergenceProblems()
{
    static std::vector<std::string> problems;
    return problems;
}

// divergences/<area>.txt, one file per area, so parity PRs for different areas never touch
// the same file (docs/tasks/0040).
const std::map<std::string, Divergence>& Divergences()
{
    static const std::map<std::string, Divergence> result = [] {
        std::map<std::string, Divergence> m;
        for (auto& area : AreaNames())
        {
            std::istringstream in(ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/divergences/" + area + ".txt"));
            std::string line;
            while (std::getline(in, line))
            {
                if (!line.empty() && line.back() == '\r') // checkouts with CRLF line endings
                    line.pop_back();
                std::istringstream ls(line);
                std::string id;
                Divergence d;
                if (!(ls >> id) || id[0] == '#')
                    continue;
                ls >> d.kind >> d.task;
                std::getline(ls >> std::ws, d.reason);
                if (AreaOf(id) != area)
                    DivergenceProblems().push_back(id + " is listed in divergences/" + area + ".txt, not " + AreaOf(id) + ".txt");
                if (!m.emplace(id, d).second)
                    DivergenceProblems().push_back(id + " is listed twice");
            }
        }
        return m;
    }();
    return result;
}

// UTF-8 <-> wchar_t (UTF-32, or UTF-16 where wchar_t is 16 bits) for the wide suite. The
// harness does not use jinja2::ConvertString: that goes through the C locale, which drops
// every non-ASCII string unless the process sets a UTF-8 locale.
std::wstring Utf8ToWide(const std::string& from)
{
    std::wstring result;
    for (std::size_t i = 0; i < from.size();)
    {
        auto byte = static_cast<unsigned char>(from[i]);
        int extra = 0; // continuation bytes after the lead byte
        if (byte >= 0xF0)
            extra = 3;
        else if (byte >= 0xE0)
            extra = 2;
        else if (byte >= 0xC0)
            extra = 1;
        uint32_t cp = extra == 0 ? byte : byte & (0x3F >> extra);
        for (int n = 1; n <= extra && i + n < from.size(); ++n)
            cp = (cp << 6) | (static_cast<unsigned char>(from[i + n]) & 0x3F);
        i += extra + 1;
        if (sizeof(wchar_t) == 2 && cp >= 0x10000)
        {
            cp -= 0x10000;
            result.push_back(static_cast<wchar_t>(0xD800 + (cp >> 10)));
            result.push_back(static_cast<wchar_t>(0xDC00 + (cp & 0x3FF)));
        }
        else
            result.push_back(static_cast<wchar_t>(cp));
    }
    return result;
}

std::string WideToUtf8(const std::wstring& from)
{
    std::string result;
    for (std::size_t i = 0; i < from.size(); ++i)
    {
        auto cp = static_cast<uint32_t>(from[i]);
        if (sizeof(wchar_t) == 2)
        {
            cp &= 0xFFFF;
            if (cp >= 0xD800 && cp < 0xDC00 && i + 1 < from.size())
                cp = 0x10000 + ((cp - 0xD800) << 10) + ((static_cast<uint32_t>(from[++i]) & 0xFFFF) - 0xDC00);
        }
        if (cp < 0x80)
            result.push_back(static_cast<char>(cp));
        else if (cp < 0x800)
            result += { static_cast<char>(0xC0 | (cp >> 6)), static_cast<char>(0x80 | (cp & 0x3F)) };
        else if (cp < 0x10000)
            result += { static_cast<char>(0xE0 | (cp >> 12)), static_cast<char>(0x80 | ((cp >> 6) & 0x3F)), static_cast<char>(0x80 | (cp & 0x3F)) };
        else
            result += { static_cast<char>(0xF0 | (cp >> 18)), static_cast<char>(0x80 | ((cp >> 12) & 0x3F)), static_cast<char>(0x80 | ((cp >> 6) & 0x3F)),
                        static_cast<char>(0x80 | (cp & 0x3F)) };
    }
    return result;
}

// The corpus strings are UTF-8; these give them in the character type under test.
template<typename CharT>
std::basic_string<CharT> FromUtf8(const std::string& from);
template<>
std::string FromUtf8<char>(const std::string& from)
{
    return from;
}
template<>
std::wstring FromUtf8<wchar_t>(const std::string& from)
{
    return Utf8ToWide(from);
}

const std::string& ToUtf8(const std::string& from)
{
    return from;
}
std::string ToUtf8(const std::wstring& from)
{
    return WideToUtf8(from);
}

// Strings are converted from UTF-8 to CharT, so the wide path gets wide context values.
template<typename CharT>
jinja2::Value ToValue(const Json& j)
{
    switch (j.type())
    {
    case Json::value_t::boolean:
        return j.get<bool>();
    case Json::value_t::number_integer:
    case Json::value_t::number_unsigned:
        return j.get<int64_t>();
    case Json::value_t::number_float:
        return j.get<double>();
    case Json::value_t::string:
        return FromUtf8<CharT>(j.get<std::string>());
    case Json::value_t::array:
    {
        jinja2::ValuesList list;
        for (auto& item : j)
            list.push_back(ToValue<CharT>(item));
        return jinja2::Value(std::move(list));
    }
    case Json::value_t::object:
    {
        jinja2::ValuesMap map;
        for (auto it = j.begin(); it != j.end(); ++it)
            map[it.key()] = ToValue<CharT>(it.value());
        return jinja2::Value(std::move(map));
    }
    default:
        return jinja2::Value();
    }
}

// The filters, tests and finalize functions a case can register by name ("filters", "tests" and
// "finalize" env options), each the counterpart of the Python function of that name in
// generate.py. They take the ints and strings of the corpus, narrow or wide.
std::string StrOf(const jinja2::Value& v)
{
    auto& data = v.data();
    if (auto* s = nonstd::get_if<std::string>(&data))
        return *s;
    if (auto* s = nonstd::get_if<nonstd::string_view>(&data))
        return std::string(s->begin(), s->end());
    if (auto* s = nonstd::get_if<std::wstring>(&data))
        return WideToUtf8(*s);
    if (auto* s = nonstd::get_if<nonstd::wstring_view>(&data))
        return WideToUtf8(std::wstring(s->begin(), s->end()));
    if (auto* i = nonstd::get_if<int64_t>(&data))
        return std::to_string(*i);
    return v.isEmpty() ? "None" : "<unsupported>";
}

// s in the character type of like
jinja2::Value StrLike(const jinja2::Value& like, const std::string& s)
{
    const bool wide = nonstd::get_if<std::wstring>(&like.data()) || nonstd::get_if<nonstd::wstring_view>(&like.data());
    return wide ? jinja2::Value(Utf8ToWide(s)) : jinja2::Value(s);
}

int64_t IntOf(const jinja2::Value& v)
{
    auto* i = nonstd::get_if<int64_t>(&v.data());
    if (!i)
        throw std::runtime_error("expected an int");
    return *i;
}

const std::map<std::string, jinja2::UserCallable>& CustomFilters()
{
    static const std::map<std::string, jinja2::UserCallable> filters = {
        { "double", { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return IntOf(p["v"]) * IntOf(p["n"]); }, { { "v", true }, { "n", false, int64_t(2) } } } },
        { "wrap",
          { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return StrLike(p["v"], StrOf(p["left"]) + StrOf(p["v"]) + StrOf(p["right"])); },
            { { "v", true }, { "left", false, std::string("[") }, { "right", false, std::string("]") } } } },
        { "upper", { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return StrLike(p["v"], "U:" + StrOf(p["v"])); }, { { "v", true } } } },
    };
    return filters;
}

const std::map<std::string, jinja2::UserCallable>& CustomTests()
{
    static const std::map<std::string, jinja2::UserCallable> tests = {
        { "big", { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return IntOf(p["v"]) > IntOf(p["limit"]); }, { { "v", true }, { "limit", false, int64_t(10) } } } },
        { "even", { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return IntOf(p["v"]) % 3 == 0; }, { { "v", true } } } },
    };
    return tests;
}

const std::map<std::string, jinja2::UserCallable>& CustomFinalize()
{
    static const std::map<std::string, jinja2::UserCallable> finalize = {
        { "none_to_empty", { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return p["v"].isEmpty() ? jinja2::Value(std::string()) : p["v"]; }, { { "v", true } } } },
        { "brackets", { [](const jinja2::UserCallableParams& p) -> jinja2::Value { return StrLike(p["v"], "[" + StrOf(p["v"]) + "]"); }, { { "v", true } } } },
    };
    return finalize;
}

// Registers the custom filters and tests a case names on env
void AddCustomCallables(const Json& options, jinja2::TemplateEnv& env)
{
    if (options.contains("filters"))
        for (auto& name : options["filters"])
            env.AddFilter(name.get<std::string>(), CustomFilters().at(name.get<std::string>()));
    if (options.contains("tests"))
        for (auto& name : options["tests"])
            env.AddTester(name.get<std::string>(), CustomTests().at(name.get<std::string>()));
}

// Maps the Python Environment options of a case onto Settings. Returns the name of the
// first option Jinja2C++ cannot express, or an empty string.
std::string ApplyEnv(const Json& env, jinja2::Settings& settings)
{
    for (auto it = env.begin(); it != env.end(); ++it)
    {
        const auto& key = it.key();
        const auto& val = it.value();
        if (key == "trim_blocks")
            settings.trimBlocks = val.get<bool>();
        else if (key == "lstrip_blocks")
            settings.lstripBlocks = val.get<bool>();
        else if (key == "keep_trailing_newline")
            settings.keepTrailingNewline = val.get<bool>();
        else if (key == "newline_sequence")
            settings.newlineSequence = val.get<std::string>();
        else if (key == "variable_start_string")
            settings.variableStartString = val.get<std::string>();
        else if (key == "variable_end_string")
            settings.variableEndString = val.get<std::string>();
        else if (key == "block_start_string")
            settings.blockStartString = val.get<std::string>();
        else if (key == "block_end_string")
            settings.blockEndString = val.get<std::string>();
        else if (key == "comment_start_string")
            settings.commentStartString = val.get<std::string>();
        else if (key == "comment_end_string")
            settings.commentEndString = val.get<std::string>();
        else if (key == "line_statement_prefix")
            settings.lineStatementPrefix = val.get<std::string>();
        else if (key == "line_comment_prefix")
            settings.lineCommentPrefix = val.get<std::string>();
        else if (key == "autoescape" && val.is_boolean())
            settings.autoescape = val.get<bool>();
        else if (key == "extensions")
        {
            for (auto& ext : val)
            {
                if (ext == "do")
                    settings.extensions.Do = true;
                else if (ext == "loopcontrols")
                    settings.extensions.LoopControls = true;
                else if (ext == "i18n")
                    settings.extensions.I18n = true;
                else
                    return "extension " + ext.get<std::string>();
            }
        }
        else if (key == "undefined" && val == "default")
            continue;
        else if (key == "finalize")
            settings.finalize = CustomFinalize().at(val.get<std::string>());
        else if (key == "filters" || key == "tests")
            continue; // registered on the environment by RenderCpp
        else
            return key;
    }
    return {};
}

struct Result
{
    bool ok = false;
    std::string text; // output, or error description
};

// Renders a case through jinja2::Template (char) or jinja2::TemplateW (wchar_t). The wide
// path converts the template, the loader files and the context strings from UTF-8, and
// the output back to UTF-8, so both paths compare with the same expectation.
template<typename CharT>
Result RenderCpp(const Json& c, const jinja2::Settings& settings)
{
    using Tpl = typename std::conditional<std::is_same<CharT, char>::value, jinja2::Template, jinja2::TemplateW>::type;

    jinja2::TemplateEnv env;
    env.SetSettings(settings);
    AddCustomCallables(c["env"], env);
    auto fs = std::make_shared<jinja2::MemoryFileSystem>();
    for (auto it = c["templates"].begin(); it != c["templates"].end(); ++it)
        fs->AddFile(it.key(), FromUtf8<CharT>(it.value().get<std::string>()));
    env.AddFilesystemHandler(std::string(), fs);

    jinja2::ValuesMap params;
    for (auto it = c["context"].begin(); it != c["context"].end(); ++it)
        params[it.key()] = ToValue<CharT>(it.value());

    try
    {
        Tpl tpl(&env);
        auto loaded = tpl.Load(FromUtf8<CharT>(c["template"].get<std::string>()), "parity");
        if (!loaded)
            return { false, "load: " + ToUtf8(loaded.error().ToString()) };
        auto rendered = tpl.RenderAsString(params);
        if (!rendered)
            return { false, "render: " + ToUtf8(rendered.error().ToString()) };
        return { true, ToUtf8(rendered.value()) };
    }
    catch (const std::exception& ex)
    {
        return { false, std::string("exception: ") + ex.what() };
    }
}

// With JINJA2CPP_PARITY_RESULTS=<file> set, every case appends "<id> <outcome>" to that
// file; test/parity/update_divergences.py turns it into the edits divergences/ needs.
void RecordOutcome(const std::string& id, const char* outcome)
{
    static std::unique_ptr<std::ofstream> out = []() -> std::unique_ptr<std::ofstream> {
        const char* path = std::getenv("JINJA2CPP_PARITY_RESULTS");
        if (!path || !*path)
            return nullptr;
        return std::make_unique<std::ofstream>(path, std::ios::binary | std::ios::app);
    }();
    if (out)
        *out << id << ' ' << outcome << std::endl;
}

// Python's output, or its error as "<type>: <message>".
std::string PythonText(const Json& c)
{
    return c.contains("output") ? c["output"].get<std::string>() : c["error"]["type"].get<std::string>() + ": " + c["error"]["message"].get<std::string>();
}

Outcome Classify(const Json& c, const Result& cpp)
{
    const bool pyOk = c.contains("output");
    if (cpp.ok && pyOk)
        return cpp.text == PythonText(c) ? Outcome::Match : Outcome::Output;
    if (cpp.ok)
        return Outcome::Accepts;
    return pyOk ? Outcome::Rejects : Outcome::Match;
}

std::string Details(const Json& c, const std::string& cppText)
{
    std::ostringstream details;
    details << "template: " << c["template"].dump() << "\n  python: " << Json(PythonText(c)).dump()
            << "\n  c++:    " << Json(cppText).dump();
    return details.str();
}

// Checks an outcome against the allow-list entry for id (if any), with the same rules for
// the narrow and the wide suite.
void CheckListed(const std::string& id, Outcome outcome, const std::string& details)
{
    auto& divergences = Divergences();
    auto known = divergences.find(id);
    if (known == divergences.end())
    {
        if (outcome != Outcome::Match)
            ADD_FAILURE() << "new divergence (" << OutcomeName(outcome) << ")\n  " << details;
        return;
    }
    // Output that depends on hash order may match on one standard library and not another.
    if (known->second.kind == "unordered" && (outcome == Outcome::Match || outcome == Outcome::Output))
        return;
    if (outcome == Outcome::Match)
        ADD_FAILURE() << "case now matches: remove " << id << " from test/parity/divergences/" << AreaOf(id) << ".txt\n  " << details;
    else if (known->second.kind != OutcomeName(outcome))
        ADD_FAILURE() << "divergence changed from '" << known->second.kind << "' to '" << OutcomeName(outcome)
                      << "': update " << id << " in test/parity/divergences/" << AreaOf(id) << ".txt\n  " << details;
}

// The allow-list entry when divergences/ marks id as a crash, so it must not run.
const Divergence* ListedCrash(const std::string& id)
{
    auto& divergences = Divergences();
    auto known = divergences.find(id);
    return known != divergences.end() && known->second.kind == "crash" ? &known->second : nullptr;
}

class ParityTest : public ::testing::TestWithParam<ParityCase>
{
};

TEST_P(ParityTest, MatchesPython)
{
    const auto& id = GetParam().id;
    const auto& c = GetParam().data;
    if (auto crash = ListedCrash(id))
    {
        RecordOutcome(id, "crash");
        GTEST_SKIP() << "crashes Jinja2C++, task " << crash->task << ": " << crash->reason;
    }

    Outcome outcome;
    Result cpp;
    jinja2::Settings settings;
    auto unsupported = ApplyEnv(c["env"], settings);
    if (!unsupported.empty())
    {
        outcome = Outcome::Unsupported;
        cpp.text = "Environment option not supported: " + unsupported;
    }
    else
    {
        cpp = RenderCpp<char>(c, settings);
        outcome = Classify(c, cpp);
    }
    RecordOutcome(id, OutcomeName(outcome));
    CheckListed(id, outcome, Details(c, cpp.text));
}

// The wide suite holds TemplateW to the narrow result rather than to Python, so that a
// narrow divergence is listed once. A case diverges in the wide path ("wide.<id>" in
// divergences/, kind relative to Python) when the wide result differs from the narrow
// one and does not match Python either; errors compare by presence, as in the narrow suite.
class ParityWideTest : public ::testing::TestWithParam<ParityCase>
{
};

TEST_P(ParityWideTest, MatchesNarrow)
{
    const auto& c = GetParam().data;
    const auto& narrowId = GetParam().id;
    const auto id = "wide." + narrowId;
    if (auto crash = ListedCrash(narrowId))
        GTEST_SKIP() << "crashes Jinja2C++, task " << crash->task << ": " << crash->reason;
    if (auto crash = ListedCrash(id))
    {
        RecordOutcome(id, "crash");
        GTEST_SKIP() << "crashes Jinja2C++ in the wide path, task " << crash->task << ": " << crash->reason;
    }

    jinja2::Settings settings;
    if (!ApplyEnv(c["env"], settings).empty())
        return; // unsupported: reported by the narrow suite

    auto narrow = RenderCpp<char>(c, settings);
    auto wide = RenderCpp<wchar_t>(c, settings);
    auto outcome = Classify(c, wide);
    // std::hash differs for std::string and std::wstring, so hash-ordered output may too:
    // for those cases compare the characters as a multiset, which still catches lost or
    // corrupted content.
    auto known = Divergences().find(narrowId);
    const bool unordered = known != Divergences().end() && known->second.kind == "unordered";
    auto sameText = [unordered](std::string a, std::string b) {
        if (unordered)
        {
            std::sort(a.begin(), a.end());
            std::sort(b.begin(), b.end());
        }
        return a == b;
    };
    const bool sameAsNarrow = wide.ok == narrow.ok && (!wide.ok || sameText(wide.text, narrow.text));
    if (sameAsNarrow)
        outcome = Outcome::Match;
    RecordOutcome(id, OutcomeName(outcome));
    CheckListed(id, outcome, Details(c, wide.text) + "\n  narrow: " + Json(narrow.text).dump());
}

std::string CaseName(const ::testing::TestParamInfo<ParityCase>& info)
{
    std::string name = info.param.id;
    std::replace_if(name.begin(), name.end(), [](char ch) { return !std::isalnum(static_cast<unsigned char>(ch)); }, '_');
    return name;
}

INSTANTIATE_TEST_SUITE_P(Parity, ParityTest, ::testing::ValuesIn(LoadCases()), CaseName);
INSTANTIATE_TEST_SUITE_P(ParityWide, ParityWideTest, ::testing::ValuesIn(LoadCases()), CaseName);

TEST(ParityRegistry, CorpusPresent)
{
    EXPECT_FALSE(AreaNames().empty()) << "missing expected/index.json; run test/parity/generate.py";
    for (auto& area : AreaNames())
        EXPECT_FALSE(ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/expected/" + area + ".json").empty())
            << "missing expected/" << area << ".json; run test/parity/generate.py";
}

TEST(ParityRegistry, DivergencesNameExistingCases)
{
    std::set<std::string> ids;
    for (auto& c : LoadCases())
        ids.insert(c.id);
    static const std::set<std::string> kinds = { "output", "rejects", "accepts", "unsupported", "unordered", "crash" };
    for (auto& d : Divergences())
    {
        const auto& id = d.first.compare(0, 5, "wide.") == 0 ? d.first.substr(5) : d.first;
        EXPECT_TRUE(ids.count(id)) << "divergences/ names unknown case " << d.first;
        EXPECT_TRUE(kinds.count(d.second.kind)) << d.first << ": unknown kind " << d.second.kind;
        EXPECT_FALSE(d.second.reason.empty()) << d.first << ": reason is required";
    }
}

TEST(ParityRegistry, DivergencesAreWellFormed)
{
    Divergences();
    for (auto& problem : DivergenceProblems())
        ADD_FAILURE() << problem;
}

} // namespace
