// Differential parity suite: renders every case of the corpus in test/parity/expected
// (generated by test/parity/generate.py with Python Jinja2) and compares the result.
// Known divergences are listed in test/parity/divergences.txt; see test/parity/README.md.

#include <jinja2cpp/filesystem_handler.h>
#include <jinja2cpp/template.h>
#include <jinja2cpp/template_env.h>

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

#include <algorithm>
#include <cctype>
#include <fstream>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#ifndef JINJA2CPP_PARITY_DIR
#error "JINJA2CPP_PARITY_DIR must point to test/parity"
#endif

namespace
{

// How the C++ result relates to the Python one.
enum class Outcome
{
    Match,       // same output, or both report an error
    Output,      // both render, outputs differ
    Rejects,     // C++ reports an error, Python renders
    Accepts,     // C++ renders, Python reports an error
    Unsupported, // the case needs an Environment option Jinja2C++ does not have
};

const char* OutcomeName(Outcome o)
{
    switch (o)
    {
    case Outcome::Match:
        return "match";
    case Outcome::Output:
        return "output";
    case Outcome::Rejects:
        return "rejects";
    case Outcome::Accepts:
        return "accepts";
    case Outcome::Unsupported:
        return "unsupported";
    }
    return "?";
}

struct Divergence
{
    std::string kind; // an OutcomeName, or "crash" for cases that must not run
    std::string task;
    std::string reason;
};

struct ParityCase
{
    std::string id;
    nlohmann::json data;

    friend std::ostream& operator<<(std::ostream& os, const ParityCase& c) { return os << c.id; }
};

std::string ReadFile(const std::string& path)
{
    std::ifstream in(path, std::ios::binary);
    std::ostringstream os;
    os << in.rdbuf();
    return os.str();
}

// expected/index.json lists the areas, so adding cases/<area>.py needs no C++ change.
const std::vector<std::string>& AreaNames()
{
    static const std::vector<std::string> areas = [] {
        std::vector<std::string> result;
        auto text = ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/expected/index.json");
        if (!text.empty())
            result = nlohmann::json::parse(text)["areas"].get<std::vector<std::string>>();
        return result;
    }();
    return areas;
}

std::vector<ParityCase> LoadCases()
{
    std::vector<ParityCase> cases;
    for (auto& area : AreaNames())
    {
        auto text = ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/expected/" + area + ".json");
        if (text.empty())
            continue; // reported by ParityRegistry.CorpusPresent
        auto doc = nlohmann::json::parse(text);
        for (auto& c : doc["cases"])
            cases.push_back(ParityCase{ c["id"].get<std::string>(), c });
    }
    return cases;
}

const std::map<std::string, Divergence>& Divergences()
{
    static const std::map<std::string, Divergence> result = [] {
        std::map<std::string, Divergence> m;
        std::istringstream in(ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/divergences.txt"));
        std::string line;
        while (std::getline(in, line))
        {
            if (line.empty() || line[0] == '#')
                continue;
            std::istringstream ls(line);
            std::string id;
            Divergence d;
            ls >> id >> d.kind >> d.task;
            std::getline(ls >> std::ws, d.reason);
            m[id] = d;
        }
        return m;
    }();
    return result;
}

jinja2::Value ToValue(const nlohmann::json& j)
{
    switch (j.type())
    {
    case nlohmann::json::value_t::boolean:
        return j.get<bool>();
    case nlohmann::json::value_t::number_integer:
    case nlohmann::json::value_t::number_unsigned:
        return j.get<int64_t>();
    case nlohmann::json::value_t::number_float:
        return j.get<double>();
    case nlohmann::json::value_t::string:
        return j.get<std::string>();
    case nlohmann::json::value_t::array:
    {
        jinja2::ValuesList list;
        for (auto& item : j)
            list.push_back(ToValue(item));
        return jinja2::Value(std::move(list));
    }
    case nlohmann::json::value_t::object:
    {
        jinja2::ValuesMap map;
        for (auto it = j.begin(); it != j.end(); ++it)
            map[it.key()] = ToValue(it.value());
        return jinja2::Value(std::move(map));
    }
    default:
        return jinja2::Value();
    }
}

// Maps the Python Environment options of a case onto Settings. Returns the name of the
// first option Jinja2C++ cannot express, or an empty string.
std::string ApplyEnv(const nlohmann::json& env, jinja2::Settings& settings)
{
    for (auto it = env.begin(); it != env.end(); ++it)
    {
        const auto& key = it.key();
        const auto& val = it.value();
        if (key == "trim_blocks")
            settings.trimBlocks = val.get<bool>();
        else if (key == "lstrip_blocks")
            settings.lstripBlocks = val.get<bool>();
        else if (key == "extensions")
        {
            for (auto& ext : val)
            {
                if (ext == "do")
                    settings.extensions.Do = true;
                else if (ext != "loopcontrols") // loop controls are always enabled
                    return "extension " + ext.get<std::string>();
            }
        }
        else if (key == "undefined" && val == "default")
            continue;
        else
            return key;
    }
    return {};
}

struct Result
{
    bool ok = false;
    std::string text; // output, or error description
};

Result RenderCpp(const nlohmann::json& c, const jinja2::Settings& settings)
{
    jinja2::TemplateEnv env;
    env.SetSettings(settings);
    auto fs = std::make_shared<jinja2::MemoryFileSystem>();
    for (auto it = c["templates"].begin(); it != c["templates"].end(); ++it)
        fs->AddFile(it.key(), it.value().get<std::string>());
    env.AddFilesystemHandler(std::string(), fs);

    jinja2::ValuesMap params;
    for (auto it = c["context"].begin(); it != c["context"].end(); ++it)
        params[it.key()] = ToValue(it.value());

    try
    {
        jinja2::Template tpl(&env);
        auto loaded = tpl.Load(c["template"].get<std::string>(), "parity");
        if (!loaded)
            return { false, "load: " + loaded.error().ToString() };
        auto rendered = tpl.RenderAsString(params);
        if (!rendered)
            return { false, "render: " + rendered.error().ToString() };
        return { true, rendered.value() };
    }
    catch (const std::exception& ex)
    {
        return { false, std::string("exception: ") + ex.what() };
    }
}

class ParityTest : public ::testing::TestWithParam<ParityCase>
{
};

TEST_P(ParityTest, MatchesPython)
{
    const auto& c = GetParam().data;
    auto& divergences = Divergences();
    auto known = divergences.find(GetParam().id);
    if (known != divergences.end() && known->second.kind == "crash")
        GTEST_SKIP() << "crashes Jinja2C++, task " << known->second.task << ": " << known->second.reason;

    const bool pyOk = c.contains("output");
    const std::string pyText = pyOk ? c["output"].get<std::string>() : c["error"]["type"].get<std::string>() + ": " + c["error"]["message"].get<std::string>();

    Outcome outcome;
    Result cpp;
    jinja2::Settings settings;
    auto unsupported = ApplyEnv(c["env"], settings);
    if (!unsupported.empty())
    {
        outcome = Outcome::Unsupported;
        cpp.text = "Environment option not supported: " + unsupported;
    }
    else
    {
        cpp = RenderCpp(c, settings);
        if (cpp.ok && pyOk)
            outcome = cpp.text == pyText ? Outcome::Match : Outcome::Output;
        else if (cpp.ok)
            outcome = Outcome::Accepts;
        else
            outcome = pyOk ? Outcome::Rejects : Outcome::Match;
    }

    std::ostringstream details;
    details << "template: " << c["template"].dump() << "\n  python: " << nlohmann::json(pyText).dump()
            << "\n  c++:    " << nlohmann::json(cpp.text).dump();

    if (known == divergences.end())
    {
        if (outcome != Outcome::Match)
            ADD_FAILURE() << "new divergence (" << OutcomeName(outcome) << ")\n  " << details.str();
        return;
    }
    if (outcome == Outcome::Match)
        ADD_FAILURE() << "case now matches Python: remove it from test/parity/divergences.txt\n  " << details.str();
    else if (known->second.kind != OutcomeName(outcome))
        ADD_FAILURE() << "divergence changed from '" << known->second.kind << "' to '" << OutcomeName(outcome)
                      << "': update test/parity/divergences.txt\n  " << details.str();
}

std::string CaseName(const ::testing::TestParamInfo<ParityCase>& info)
{
    std::string name = info.param.id;
    std::replace_if(name.begin(), name.end(), [](char ch) { return !std::isalnum(static_cast<unsigned char>(ch)); }, '_');
    return name;
}

INSTANTIATE_TEST_SUITE_P(Parity, ParityTest, ::testing::ValuesIn(LoadCases()), CaseName);

TEST(ParityRegistry, CorpusPresent)
{
    EXPECT_FALSE(AreaNames().empty()) << "missing expected/index.json; run test/parity/generate.py";
    for (auto& area : AreaNames())
        EXPECT_FALSE(ReadFile(std::string(JINJA2CPP_PARITY_DIR) + "/expected/" + area + ".json").empty())
            << "missing expected/" << area << ".json; run test/parity/generate.py";
}

TEST(ParityRegistry, DivergencesNameExistingCases)
{
    std::set<std::string> ids;
    for (auto& c : LoadCases())
        ids.insert(c.id);
    static const std::set<std::string> kinds = { "output", "rejects", "accepts", "unsupported", "crash" };
    for (auto& d : Divergences())
    {
        EXPECT_TRUE(ids.count(d.first)) << "divergences.txt names unknown case " << d.first;
        EXPECT_TRUE(kinds.count(d.second.kind)) << d.first << ": unknown kind " << d.second.kind;
        EXPECT_FALSE(d.second.reason.empty()) << d.first << ": reason is required";
    }
}

} // namespace
