#!/usr/bin/env python3
"""Generate src/unicode_tables.h: the Unicode character classes Python's regular
expressions use (\\w, \\d, \\s), as code point ranges above ASCII.

The tables follow the Unicode version of the Python that runs this script
(unicodedata.unidata_version, written into the header). Regenerate with
    python3 scripts/gen_unicode_tables.py && clang-format -i src/unicode_tables.h
"""
import pathlib
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent


def ranges(pred):
    result, start = [], None
    for cp in range(0x80, 0x110000):
        if pred(chr(cp)):
            if start is None:
                start = cp
        elif start is not None:
            result.append((start, cp - 1))
            start = None
    if start is not None:
        result.append((start, 0x10FFFF))
    return result


def table(name, comment, rows):
    body = "\n".join("    {{ 0x{:04X}, 0x{:04X} }},".format(a, b) for a, b in rows)
    return "// {}\nconstexpr CodePointRange {}[] = {{\n{}\n}};\n".format(comment, name, body)


def main():
    parts = [
        "// Generated by scripts/gen_unicode_tables.py from Unicode {}; do not edit.\n".format(unicodedata.unidata_version),
        "#ifndef JINJA2CPP_SRC_UNICODE_TABLES_H\n#define JINJA2CPP_SRC_UNICODE_TABLES_H\n",
        "#include <algorithm>\n#include <cstdint>\n#include <iterator>\n",
        "namespace jinja2\n{\nnamespace unicode\n{\n",
        "struct CodePointRange\n{\n    uint32_t first;\n    uint32_t last;\n};\n",
        table("WordRanges", "Python \\w above ASCII: str.isalnum()", ranges(lambda c: c.isalnum())),
        table("DecimalRanges", "Python \\d above ASCII: str.isdecimal()", ranges(lambda c: c.isdecimal())),
        table("SpaceRanges", "Python \\s and str.strip() above ASCII: str.isspace()", ranges(lambda c: c.isspace())),
        """template<size_t N>
bool InRanges(const CodePointRange (&ranges)[N], uint32_t cp)
{
    auto it = std::upper_bound(std::begin(ranges), std::end(ranges), cp, [](uint32_t value, const CodePointRange& r) { return value < r.first; });
    return it != std::begin(ranges) && cp <= std::prev(it)->last;
}

// Python's \\w, \\d and str.isspace() for one code point
inline bool IsWordChar(uint32_t cp)
{
    if (cp < 0x80)
        return (cp >= '0' && cp <= '9') || (cp >= 'a' && cp <= 'z') || (cp >= 'A' && cp <= 'Z') || cp == '_';
    return InRanges(WordRanges, cp);
}

inline bool IsDecimal(uint32_t cp)
{
    return cp < 0x80 ? cp >= '0' && cp <= '9' : InRanges(DecimalRanges, cp);
}

inline bool IsSpace(uint32_t cp)
{
    if (cp < 0x80)
        return (cp >= 0x09 && cp <= 0x0D) || (cp >= 0x1C && cp <= 0x20);
    return InRanges(SpaceRanges, cp);
}
""",
        "} // namespace unicode\n} // namespace jinja2\n\n#endif // JINJA2CPP_SRC_UNICODE_TABLES_H\n",
    ]
    (ROOT / "src" / "unicode_tables.h").write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
