#!/usr/bin/env python3
"""Generates src/unicode_printable.h: the code points Python's repr() escapes.

Python's str.__repr__ escapes every character for which str.isprintable() is false
(categories Cc, Cf, Cs, Co, Cn, Zl, Zp and Zs other than the space). The table follows
the Unicode database of the Python that runs this script; rerun it when the parity
oracle moves to a Python with a newer database.

    python3 scripts/gen_unicode_printable.py > src/unicode_printable.h
"""
import sys
import unicodedata


def ranges():
    start = None
    for cp in range(0x110000):
        printable = chr(cp).isprintable()
        if not printable and start is None:
            start = cp
        elif printable and start is not None:
            yield start, cp - 1
            start = None
    if start is not None:
        yield start, 0x10FFFF


def main():
    rows = list(ranges())
    out = sys.stdout
    out.write("// Generated by scripts/gen_unicode_printable.py from Python %d.%d (Unicode %s).\n"
              % (sys.version_info[0], sys.version_info[1], unicodedata.unidata_version))
    out.write("// Do not edit by hand.\n")
    out.write("#ifndef JINJA2CPP_SRC_UNICODE_PRINTABLE_H\n#define JINJA2CPP_SRC_UNICODE_PRINTABLE_H\n\n")
    out.write("#include <algorithm>\n#include <cstdint>\n#include <iterator>\n\n")
    out.write("namespace jinja2\n{\nnamespace detail\n{\n\n")
    out.write("// True when Python's str.isprintable() holds for the code point, so repr() keeps it as is\n")
    out.write("inline bool IsPythonPrintable(uint32_t cp)\n{\n")
    out.write("    if (cp >= 0x20 && cp < 0x7f)\n        return true;\n\n")
    out.write("    struct Range\n    {\n        uint32_t first;\n        uint32_t last;\n    };\n")
    out.write("    // clang-format off\n    static const Range nonPrintable[] = {\n")
    for i in range(0, len(rows), 4):
        out.write("        " + " ".join("{0x%X, 0x%X}," % r for r in rows[i:i + 4]) + "\n")
    out.write("    };\n    // clang-format on\n\n")
    out.write("    auto it = std::upper_bound(std::begin(nonPrintable), std::end(nonPrintable), cp,\n"
              "                               [](uint32_t val, const Range& r) { return val < r.first; });\n")
    out.write("    if (it == std::begin(nonPrintable))\n        return true;\n")
    out.write("    --it;\n    return cp > it->last;\n}\n\n")
    out.write("} // namespace detail\n} // namespace jinja2\n\n#endif // JINJA2CPP_SRC_UNICODE_PRINTABLE_H\n")


if __name__ == "__main__":
    main()
