"""HTML autoescaping and Markup semantics."""
CONTEXT = {"html": "<b>&'\"</b>", "n": None, "l": ["<a>", "<b>"]}
AE = {"env": {"autoescape": True}}
CASES = [
    ("off_by_default", "{{ html }}"),
    ("env_on", "{{ html }}", AE),
    ("env_on_safe", "{{ html|safe }}", AE),
    ("env_on_escape_once", "{{ html|e }}", AE),
    ("env_on_forceescape", "{{ html|e|forceescape }}", AE),
    ("env_on_literal", "{{ '<i>' }}", AE),
    ("env_on_text_untouched", "<p>{{ 'x' }}</p>", AE),
    ("env_on_concat_safe", "{{ '<i>'|safe ~ '<u>' }}", AE),
    ("env_on_plus_safe", "{{ '<i>'|safe + '<u>' }}", AE),
    ("env_on_join", "{{ l|join('<br>') }}", AE),
    ("env_on_join_safe_sep", "{{ l|join('<br>'|safe) }}", AE),
    ("env_on_none", "[{{ n }}]", AE),
    ("env_on_int", "{{ 1 < 2 }}{{ 5 }}", AE),
    ("env_on_macro_result", "{% macro m() %}<b>{% endmacro %}{{ m() }}", AE),
    ("env_on_set_block", "{% set v %}<b>{% endset %}{{ v }}", AE),
    ("env_on_filter_upper_safe", "{{ '<i>'|safe|upper }}", AE),
    ("env_on_replace_safe", "{{ '<i>'|safe|replace('i', '<u>') }}", AE),
    ("env_on_format", "{{ '<%s>'|safe|format('<x>') }}", AE),
    ("env_on_tojson", "{{ html|tojson }}", AE),
    ("env_on_xmlattr", "<a{{ {'t': '<x>'}|xmlattr }}>", AE),
    ("env_on_striptags", "{{ '<b>a&amp;b</b>'|striptags }}", AE),
    ("env_on_include", "{% include 't.j2' %}", {"env": {"autoescape": True}, "templates": {"t.j2": "{{ html }}"}}),
    ("block_on", "{% autoescape true %}{{ html }}{% endautoescape %}"),
    ("block_off_inside_on", "{% autoescape false %}{{ html }}{% endautoescape %}", AE),
    ("block_nested", "{% autoescape true %}{% autoescape false %}{{ html }}{% endautoescape %}{{ html }}{% endautoescape %}"),
    ("escaped_test", "{{ html|e is escaped }}{{ html is escaped }}"),
    ("escape_numbers", "{{ 5|e }}"),
    ("escape_none", "[{{ n|e }}]"),
    # Markup operations that do not depend on autoescape
    ("plus_safe_left", "{{ '<i>'|safe + '<u>' }}"),
    ("plus_safe_right", "{{ '<u>' + '<i>'|safe }}"),
    ("mul_safe", "{{ ('<i>'|safe * 2) is escaped }}"),
    ("escape_twice", "{{ html|e|e }}"),
    ("forceescape_safe", "{{ '<i>'|safe|forceescape }}"),
    ("safe_methods_keep_markup", "{{ '<i>'|safe|upper is escaped }}{{ '<i>'|safe|title is escaped }}{{ '<i>'|safe|trim is escaped }}"),
    ("format_safe", "{{ '<%s>'|safe|format('<x>') }}"),
    ("percent_safe", "{{ '<%s>'|safe % '<x>' }}{{ ('%s'|safe % 1) is escaped }}"),
    ("string_keeps_markup", "{{ '<i>'|safe|string is escaped }}"),
    ("safe_number", "{{ 5|safe is escaped }}"),
    ("safe_in_list", "{% set l2 = ['<i>'|safe] %}{{ l2[0] is escaped }}"),
    ("tojson_escaped", "{{ html|tojson is escaped }}"),
    ("xmlattr_off", "{{ {'t': '<x>'}|xmlattr is escaped }}"),
    ("xmlattr_safe_value", "<a{{ {'t': '<x>'|safe}|xmlattr }}>"),
    ("replace_safe_off", "{{ '<i>'|safe|replace('i', '<u>') }}"),
    ("join_off", "{{ ['<a>'|safe, '<b>']|join(',') is escaped }}"),
    ("macro_result_off", "{% macro m() %}x{% endmacro %}{{ m() is escaped }}"),
    ("percent_safe_containers", "{{ '%s'|safe % (l,) }}|{{ '%s'|safe % l }}|{{ '%s|%s'|safe % ((html, 1), none) }}"),
    ("format_safe_containers", "{{ '<%s>'|safe|format(l) }}|{{ '%(a)s'|safe % {'a': l} }}"),
    ("replace_safe_old_unescaped", "{{ html|safe|replace('<', '[', 1) }}|{{ html|safe|replace('&', '<&>', 1) }}"),
    # Autoescape on
    ("env_on_macro_escaped", "{% macro m() %}x{% endmacro %}{{ m() is escaped }}", AE),
    ("env_on_macro_body", "{% macro m(v) %}[{{ v }}]{% endmacro %}{{ m(html) }}", AE),
    ("env_on_caller", "{% macro m() %}[{{ caller() }}]{% endmacro %}{% call m() %}<i>{{ '<x>' }}{% endcall %}", AE),
    ("env_on_join_markup_item", "{{ ['<a>'|safe, '<b>']|join(',') }}", AE),
    ("env_on_join_escaped", "{{ l|join('<br>') is escaped }}{{ l|join('<br>'|safe) is escaped }}", AE),
    ("env_on_replace_safe_new", "{{ '<i>'|replace('i', '<u>'|safe) }}", AE),
    ("env_on_set_filtered_block", "{% set v | length %}<i>{% endset %}{{ v }}{{ v is escaped }}", AE),
    ("env_on_set_filtered_block_title", "{% set v | title %}<i>{% endset %}{{ v }}", AE),
    ("env_on_filter_block", "{% filter title %}<i>{% endfilter %}", AE),
    ("env_on_filter_block_replace", "{% filter replace('<', '[') %}<{{ html }}>{% endfilter %}", AE),
    ("env_on_urlize", "{{ 'see <http://a.b>'|urlize }}", AE),
    ("env_on_list", "{{ l }}", AE),
    ("env_on_set_value", "{% set v = html %}{{ v }}{% set w = html|safe %}{{ w }}", AE),
    ("env_on_import", "{% from 'm.j2' import mm %}{{ mm(html) }}|{{ mm(html) is escaped }}",
     {"env": {"autoescape": True}, "templates": {"m.j2": "{% macro mm(v) %}<{{ v }}>{% endmacro %}"}}),
    ("env_on_extends", "{% extends 'b.j2' %}{% block b %}{{ html }}{% endblock %}",
     {"env": {"autoescape": True}, "templates": {"b.j2": "[{% block b %}{% endblock %}]"}}),
    # The autoescape block
    ("block_expression", "{% autoescape 1 > 0 %}{{ html }}{% endautoescape %}"),
    ("block_none_value", "{% autoescape n %}{{ html }}{% endautoescape %}", AE),
    ("block_scoped", "{% autoescape true %}{% set q = 1 %}{% endautoescape %}[{{ q }}]"),
    ("block_macro_defined_inside", "{% autoescape true %}{% macro m() %}{{ html }}{% endmacro %}{% endautoescape %}{{ m is defined }}"),
    ("block_macro_defined_inside_on", "{% autoescape true %}{% macro m() %}{{ html }}{% endmacro %}{% autoescape false %}{{ m() }}{% endautoescape %}{% endautoescape %}"),
    ("block_macro_called_inside", "{% macro m() %}{{ html }}{% endmacro %}{% autoescape true %}{{ m() }}{% endautoescape %}"),
    ("block_include", "{% autoescape true %}{% include 't.j2' %}{% endautoescape %}", {"templates": {"t.j2": "{{ html }}"}}),
    ("block_off_include", "{% autoescape false %}{% include 't.j2' %}{% endautoescape %}", {"env": {"autoescape": True}, "templates": {"t.j2": "{{ html }}"}}),
    ("block_with_block", "{% autoescape true %}{% block b %}{{ html }}{% endblock %}{% endautoescape %}"),
    ("block_no_argument", "{% autoescape %}x{% endautoescape %}"),
    ("block_unclosed", "{% autoescape true %}x"),
    ("block_end_with_argument", "{% autoescape true %}x{% endautoescape true %}"),
    ("block_stray_end", "x{% endautoescape %}"),
    ("variable_named_autoescape", "{% set autoescape = 1 %}{{ autoescape }}"),
    # Gaps left for task 0051
    ("markup_kept_by_filters", "{{ 'T' if '<i>'|safe|upper is escaped else 'F' }}{{ 'T' if '<i>'|safe|lower is escaped else 'F' }}{{ 'T' if '<i>'|safe|capitalize is escaped else 'F' }}{{ 'T' if '<i>'|safe|title is escaped else 'F' }}{{ 'T' if '<i>'|safe|trim is escaped else 'F' }}{{ 'T' if '<i>'|safe|center(9) is escaped else 'F' }}{{ 'T' if '<i>'|safe|indent(2) is escaped else 'F' }}{{ 'T' if '<i>'|safe|wordwrap(3) is escaped else 'F' }}{{ 'T' if '<i>'|safe|truncate(2,true,'') is escaped else 'F' }}{{ 'T' if '<i>'|safe|reverse is escaped else 'F' }}{{ 'T' if '<i>'|safe|first is escaped else 'F' }}{{ 'T' if '<i>'|safe|last is escaped else 'F' }}{{ 'T' if '<i>'|safe|striptags is escaped else 'F' }}{{ 'T' if '<i>'|safe|string is escaped else 'F' }}{{ 'T' if '<i>'|safe|urlize is escaped else 'F' }}{{ 'T' if '<i>'|safe|wordcount is escaped else 'F' }}{{ 'T' if '<i>'|safe|replace('a','b') is escaped else 'F' }}{{ 'T' if '<i>'|safe|format() is escaped else 'F' }}{{ 'T' if '<i>'|safe|default('x') is escaped else 'F' }}"),
    ("markup_method_upper", "{{ ('<i>'|safe).upper() is escaped }}{{ ('<i>'|safe).replace('i', '<u>') }}"),
    ("markup_repr_in_list", "{{ ['<i>'|safe] }}|{{ ['<i>'|safe]|pprint }}"),
    ("env_on_caller_markup_call_site", "{% macro w() %}[{{ caller() }}]{% endmacro %}{% autoescape false %}{% call w() %}<{{ html }}>{% endcall %}{% endautoescape %}", AE),
    ("markup_slice", "{{ (html|safe)[0] is escaped }}{{ (html|safe)[1:3] is escaped }}"),
    ("env_on_concat_markup_var", "{% set a = '<i>'|safe %}{{ a ~ '<u>' }}", AE),
]
