"""Templates Jinja2 rejects. Only the fact of an error is compared, not the message."""
CONTEXT = {"x": 3, "l": [1, 2], "s": "abc"}
CASES = [
    ("binary_missing_operand", "{{ 1 + }}"),
    ("if_no_condition", "{% if %}x{% endif %}"),
    ("unclosed_subscript", "{{ l[ }}"),
    ("unclosed_expression", "{{ x "),
    ("unclosed_block", "{% if true %}x"),
    ("unclosed_for", "{% for i in l %}x"),
    ("unclosed_comment", "{# x"),
    ("unclosed_expression_after_text", "{{ x }}{{"),
    ("unclosed_block_after_text", "{{ x }}{%"),
    ("unclosed_with", "{% with a = 1 %}{{ a }}"),
    ("unclosed_filter_block", "{% filter upper %}a"),
    ("unclosed_string", "{{ 'abc }}"),
    ("for_no_target", "{% for %}{% endfor %}"),
    ("for_no_in", "{% for i l %}{% endfor %}"),
    ("stray_endif", "{% endif %}"),
    ("stray_endfor", "x{% endfor %}"),
    ("mismatched_end", "{% if true %}{% endfor %}"),
    ("else_after_else", "{% if true %}{% else %}{% else %}{% endif %}"),
    ("elif_after_else", "{% if true %}{% else %}{% elif false %}{% endif %}"),
    ("else_outside_if", "{% macro m() %}{% else %}{% endmacro %}"),
    ("elif_in_for", "{% for i in l %}{% elif true %}{% endfor %}"),
    ("for_else_after_else", "{% for i in l %}{% else %}{% else %}{% endfor %}"),
    ("empty_expression", "{{ }}"),
    ("bad_token", "{{ x $ 1 }}"),
    ("assign_to_literal", "{% set 1 = 2 %}"),
    ("set_no_value", "{% set a %}"),
    ("macro_no_name", "{% macro () %}{% endmacro %}"),
    ("macro_duplicate_arg", "{% macro m(a, a) %}{% endmacro %}"),
    ("macro_non_default_after_default", "{% macro m(a=1, b) %}{% endmacro %}"),
    ("macro_explicit_caller_no_default", "{% macro m(caller) %}{{ caller() }}{% endmacro %}"),
    ("call_explicit_caller_no_default", "{% macro m() %}{{ caller(1) }}{% endmacro %}{% call(caller) m() %}{{ caller }}{% endcall %}"),
    ("call_duplicate_arg", "{% macro m() %}{% endmacro %}{% call(a, a) m() %}{% endcall %}"),
    ("break_outside_loop", "{% break %}", {"env": {"extensions": ["loopcontrols"]}}),
    ("extends_twice", "{% extends 'a' %}{% extends 'b' %}", {"templates": {"a": "", "b": ""}}),
    ("string_plus_int", "{{ 'a' + 1 }}"),
    ("int_plus_list", "{{ 1 + [1] }}"),
    ("div_by_zero", "{{ 1 / 0 }}"),
    ("call_non_callable", "{{ x() }}"),
    ("call_list", "{{ l() }}"),
    ("in_number", "{{ 1 in x }}"),
    ("in_string_non_string", "{{ 1 in s }}"),
    ("unpack_wrong_count", "{% for a, b in [[1, 2, 3]] %}{% endfor %}"),
    ("set_unpack_wrong_count", "{% set a, b = [1] %}"),
    ("unpack_too_few", "{% for a, b in [[1, 2], [3]] %}{% endfor %}"),
    ("unpack_non_iterable", "{% for a, b in [1] %}{% endfor %}"),
    ("set_unpack_too_many", "{% set a, b = 1, 2, 3 %}"),
    ("unknown_filter", "{{ x|nonexistent }}"),
    ("unknown_test", "{{ x is nonexistent }}"),
    ("filter_wrong_arg_type", "{{ s|truncate('a') }}"),
    ("int_filter_bad_kwarg", "{{ s|upper(foo=1) }}"),
    ("filter_too_many_args", "{{ l|first(1) }}"),
    ("filter_missing_arg", "{{ s|replace('a') }}"),
    ("center_width_not_int", "{{ s|center('a') }}"),
    ("wordwrap_width_not_int", "{{ s|wordwrap(2.5) }}"),
    ("truncate_shorter_than_end", "{{ s|truncate(2) }}"),
    ("truncate_negative_leeway", "{{ s|truncate(5, leeway=-1) }}"),
    ("dict_unhashable_key", "{{ {[1]: 2} }}"),
    ("tuple_assign_in_expr", "{{ a = 1 }}"),
    ("sort_mixed_types", "{{ [1, 'a']|sort|join }}"),
    ("max_mixed_types", "{{ ['a', 1]|max }}"),
    ("sort_dicts", "{{ [{'a': 1}, {'a': 2}]|sort|length }}"),
    ("dictsort_mixed_values", "{{ {'a': 1, 'b': 'x'}|dictsort(by='value')|length }}"),
    ("sort_with_none", "{{ [none, 1]|sort|length }}"),
    ("sort_undefined_attribute", "{{ [{'c': 'b'}, {}]|sort(attribute='c')|length }}"),
    ("missing_endmacro", "{% macro m() %}x"),
    ("missing_endraw", "{% raw %}x"),
    ("int_leading_zero", "{{ 01 }}"),
    ("int_leading_zero_underscore", "{{ 0_1 }}"),
    ("float_leading_dot", "{{ .5 }}"),
    ("float_exponent_no_digits", "{{ 1e+ }}"),
    ("call_after_bad_subscript", "{{ x[8( }}"),
]
