"""Templates Jinja2 rejects. Only the fact of an error is compared, not the message."""
CONTEXT = {"x": 3, "l": [1, 2], "s": "abc"}
CASES = [
    ("binary_missing_operand", "{{ 1 + }}"),
    ("if_no_condition", "{% if %}x{% endif %}"),
    ("unclosed_subscript", "{{ l[ }}"),
    ("unclosed_expression", "{{ x "),
    ("unclosed_block", "{% if true %}x"),
    ("unclosed_for", "{% for i in l %}x"),
    ("unclosed_comment", "{# x"),
    ("unclosed_string", "{{ 'abc }}"),
    ("for_no_target", "{% for %}{% endfor %}"),
    ("for_no_in", "{% for i l %}{% endfor %}"),
    ("stray_endif", "{% endif %}"),
    ("stray_endfor", "x{% endfor %}"),
    ("mismatched_end", "{% if true %}{% endfor %}"),
    ("else_after_else", "{% if true %}{% else %}{% else %}{% endif %}"),
    ("elif_after_else", "{% if true %}{% else %}{% elif false %}{% endif %}"),
    ("empty_expression", "{{ }}"),
    ("bad_token", "{{ x $ 1 }}"),
    ("assign_to_literal", "{% set 1 = 2 %}"),
    ("set_no_value", "{% set a %}"),
    ("macro_no_name", "{% macro () %}{% endmacro %}"),
    ("macro_duplicate_arg", "{% macro m(a, a) %}{% endmacro %}"),
    ("macro_non_default_after_default", "{% macro m(a=1, b) %}{% endmacro %}"),
    ("macro_explicit_caller_no_default", "{% macro m(caller) %}{{ caller() }}{% endmacro %}"),
    ("call_explicit_caller_no_default", "{% macro m() %}{{ caller(1) }}{% endmacro %}{% call(caller) m() %}{{ caller }}{% endcall %}"),
    ("call_duplicate_arg", "{% macro m() %}{% endmacro %}{% call(a, a) m() %}{% endcall %}"),
    ("break_outside_loop", "{% break %}", {"env": {"extensions": ["loopcontrols"]}}),
    ("extends_twice", "{% extends 'a' %}{% extends 'b' %}", {"templates": {"a": "", "b": ""}}),
    ("string_plus_int", "{{ 'a' + 1 }}"),
    ("int_plus_list", "{{ 1 + [1] }}"),
    ("div_by_zero", "{{ 1 / 0 }}"),
    ("call_non_callable", "{{ x() }}"),
    ("unpack_wrong_count", "{% for a, b in [[1, 2, 3]] %}{% endfor %}"),
    ("set_unpack_wrong_count", "{% set a, b = [1] %}"),
    ("unknown_filter", "{{ x|nonexistent }}"),
    ("unknown_test", "{{ x is nonexistent }}"),
    ("filter_wrong_arg_type", "{{ s|truncate('a') }}"),
    ("int_filter_bad_kwarg", "{{ s|upper(foo=1) }}"),
    ("dict_unhashable_key", "{{ {[1]: 2} }}"),
    ("tuple_assign_in_expr", "{{ a = 1 }}"),
    ("sort_mixed_types", "{{ [1, 'a']|sort|join }}"),
    ("missing_endmacro", "{% macro m() %}x"),
    ("missing_endraw", "{% raw %}x"),
]
