"""Builtin filters. List results are iterated or joined as strings, so list repr (output.py)
and join of numbers do not mask the behaviour of the filter under test."""
CONTEXT = {"x": 3, "neg": -3, "y": 2.567, "s": "Hello World", "l": [3, 1, 2], "dup": [3, 1, 3, 2, 1],
           "words": ["b", "A", "c"], "d": {"b": 2, "a": 1, "C": 3}, "e": [], "n": None,
           "html": "<b>Tom & \"Jerry\"</b>", "long": "The quick brown fox jumps over the lazy dog",
           "users": [{"name": "bob", "age": 30, "city": "Oslo"}, {"name": "alice", "age": 25, "city": "Rome"},
                     {"name": "carl", "age": 30, "city": "Oslo"}, {"name": "dan", "age": 41}],
           "lines": "a\nb\n\nc", "nums_str": ["10", "9", "100"]}
CASES = [
    ("abs", "{{ neg|abs }}|{{ -2.5|abs }}"),
    ("attr", "{{ users[0]|attr('name') }}"),
    ("attr_missing", "[{{ users[0]|attr('nope') }}]"),
    ("batch", "{% for b in l|batch(2) %}{% for x in b %}{{ x }},{% endfor %};{% endfor %}"),
    ("batch_fill", "{% for b in l|batch(2, 'x') %}{% for x in b %}{{ x }},{% endfor %};{% endfor %}"),
    ("capitalize", "{{ 'hELLO wORLD'|capitalize }}"),
    ("center", "[{{ 'abc'|center(9) }}]"),
    ("center_default", "[{{ 'abc'|center }}]"),
    ("count", "{{ l|count }}"),
    ('count_string', "{{ 'abc'|count }}|{{ d|count }}"),
    ("default", "{{ nope|default('dflt') }}"),
    ("default_alias", "{{ nope|d('dflt') }}"),
    ("default_defined_none", "[{{ n|default('dflt') }}]"),
    ("default_boolean", "{{ ''|default('dflt', true) }}|{{ ''|default('dflt', boolean=true) }}"),
    ("dictsort", "{% for k, v in d|dictsort %}{{ k }}={{ v }};{% endfor %}"),
    # Python sorts by key.lower(): '_' (0x5f) comes before every lowercase letter
    ("select_single_pass", "{% set a = [1, 2, 3]|select('odd') %}{{ a|list }}{{ a|list }}"),
    ("dictsort_lowered_keys", "{% for k, v in {'ab': 1, 'a_b': 2, 'AC': 3, 'b': 4, 'A[': 5}|dictsort %}{{ k }};{% endfor %}"),
    ("dictsort_case_sensitive", "{% for k, v in d|dictsort(true) %}{{ k }};{% endfor %}"),
    ("dictsort_by_value", "{% for k, v in d|dictsort(by='value') %}{{ k }};{% endfor %}"),
    ("dictsort_reverse", "{% for k, v in d|dictsort(reverse=true) %}{{ k }};{% endfor %}"),
    ("dictsort_stable", "{% for k, v in {'b': 1, 'a': 1, 'c': 0}|dictsort(by='value') %}{{ k }}{% endfor %}"),
    ("dictsort_stable_reverse", "{% for k, v in {'b': 1, 'a': 1, 'c': 0}|dictsort(by='value', reverse=true) %}{{ k }}{% endfor %}"),
    ("escape", "{{ html|escape }}"),
    ("escape_alias", "{{ html|e }}"),
    ("escape_single_quote", "{{ \"it's\"|e }}"),
    ('escape_non_string', "{{ ['<a>']|e }}|{{ 1.5|escape }}|[{{ nope|e }}]"),
    ("filesizeformat", "{{ 1234567|filesizeformat }}|{{ 100|filesizeformat }}|{{ 1000|filesizeformat }}"),
    ("filesizeformat_binary", "{{ 1234567|filesizeformat(true) }}"),
    ('filesizeformat_edges', "{{ 1|filesizeformat }}|{{ 0|filesizeformat }}|{{ -5|filesizeformat }}|{{ 2.5|filesizeformat }}|{{ 1023|filesizeformat(true) }}|{{ 1024|filesizeformat(binary=true) }}|{{ '2048'|filesizeformat }}|{{ 1e30|filesizeformat }}"),
    ('filesizeformat_not_number', "{{ 'abc'|filesizeformat }}"),
    ('filesizeformat_string_whitespace', "{{ '1000 '|filesizeformat }}|{{ ' \\t-2e3\\n'|filesizeformat }}|{{ '1_000_000'|filesizeformat }}|{{ '.5'|filesizeformat }}|{{ '1.'|filesizeformat }}|{{ 'Infinity'|filesizeformat }}|{{ '1e999'|filesizeformat }}|{{ '1e-999'|filesizeformat }}"),
    ('filesizeformat_empty_string', "{{ ''|filesizeformat }}"),
    ('filesizeformat_hex_string', "{{ '0x10'|filesizeformat }}"),
    ('filesizeformat_bad_underscore', "{{ '1__0'|filesizeformat }}"),
    ('filesizeformat_dot_only', "{{ '.'|filesizeformat }}"),
    ('filesizeformat_exact_units', "{{ '999999999999999999999999'|filesizeformat }}|{{ 1e24|filesizeformat }}|{{ 1e27|filesizeformat }}"),
    ("first", "{{ l|first }}"),
    ("first_empty", "[{{ e|first }}]"),
    ("first_string", "{{ s|first }}"),
    ("float", "{{ '3.5'|float }}|{{ 3|float }}|{{ 'x'|float }}|{{ 'x'|float(1.5) }}"),
    ("forceescape", "{{ html|forceescape }}"),
    ("format_percent", "{{ '%s-%d'|format('a', 3) }}"),
    ("format_float", "{{ '%.2f'|format(3.14159) }}"),
    ("format_named", "{{ '%(a)s!'|format(a='x') }}"),
    ("groupby", "{% for g in users|groupby('age') %}{{ g.grouper }}:{{ g.list|map(attribute='name')|join(',') }};{% endfor %}"),
    ("groupby_tuple_unpack", "{% for age, items in users|groupby('age') %}{{ age }}={{ items|length }};{% endfor %}"),
    ("groupby_default", "{% for g in users|groupby('city', default='?') %}{{ g.grouper }};{% endfor %}"),
    ("indent", "{{ lines|indent(2) }}"),
    ("indent_first", "{{ lines|indent(2, true) }}"),
    ("indent_blank", "{{ lines|indent(2, blank=true) }}"),
    ("indent_string", "{{ lines|indent('> ') }}"),
    ('indent_default', "[{{ 'a\\nb\\n'|indent }}]"),
    ('indent_line_breaks', "[{{ t|indent(1, true, true) }}]", {"ctx": {"t": "a\r\nb\rc\x0bd\u2028e\x85f\x1cg"}}),
    ('indent_empty', "[{{ ''|indent(2, true) }}]|[{{ ''|indent(2, true, true) }}]"),
    ("int", "{{ 3.7|int }}|{{ '42'|int }}|{{ 'x'|int }}|{{ 'x'|int(7) }}"),
    ("int_base", "{{ '0x1A'|int(0, 16) }}|{{ '101'|int(base=2) }}"),
    ("int_float_string", "{{ '3.9'|int }}"),
    ("items", "{% for k, v in {'a': 1}|items %}{{ k }}{{ v }}{% endfor %}"),
    ('items_tuple_repr', "{{ {'a': 1}|items|list }}|{{ {'a': 1}|items|first }}"),
    ('items_undefined', '[{% for k, v in nope|items %}x{% endfor %}]'),
    ('items_not_mapping', '{{ l|items|list }}'),
    ('items_values', "{% for k, v in {'a': [1, 2]}|items %}{{ k }}{% for i in v %},{{ i }}{% endfor %}{% endfor %}"),
    ("join_strings", "{{ words|join }}|{{ words|join(', ') }}"),
    ("join_numbers", "{{ l|join }}|{{ l|join(', ') }}"),
    ("join_mixed", "{{ [1, 'a', 2.5]|join('-') }}"),
    ("join_attribute", "{{ users|join(',', attribute='name') }}"),
    ("last", "{{ l|last }}"),
    ("length", "{{ l|length }}|{{ s|length }}|{{ d|length }}"),
    ("list_string", "{{ 'abc'|list|join(',') }}"),
    ("list_dict", "{{ {'a': 1}|list|join(',') }}"),
    ("list_dict_order", "{{ {'b': 1, 'a': 2, 'C': 3}|list|join(',') }}"),
    ("lower", "{{ s|lower }}"),
    ("map_attribute", "{{ users|map(attribute='name')|join(',') }}"),
    ("map_attribute_default", "{{ users|map(attribute='city', default='?')|join(',') }}"),
    ("map_filter", "{{ words|map('upper')|join(',') }}"),
    ("map_filter_args", "{{ l|map('string')|map('center', 3)|join('|') }}"),
    ("max", "{{ l|max }}|{{ words|max }}"),
    ("max_attribute", "{{ (users|max(attribute='age')).name }}"),
    ("max_case_sensitive", "{{ words|max(case_sensitive=true) }}"),
    ("min", "{{ l|min }}|{{ words|min }}"),
    ("pprint", "{{ d|pprint }}"),
    ("pprint_dict_literal", "{{ {'b': 1, 'a': 2, 'C': 3}|pprint }}"),
    ("reject", "{% for i in l|reject('odd') %}{{ i }},{% endfor %}"),
    ("rejectattr", "{{ users|rejectattr('age', 'gt', 26)|map(attribute='name')|join(',') }}"),
    ("rejectattr_truthy", "{{ users|rejectattr('city')|map(attribute='name')|join(',') }}"),
    ("replace", "{{ 'a b c'|replace(' ', '_') }}"),
    ("replace_count", "{{ 'a b c'|replace(' ', '_', 1) }}"),
    ("reverse_list", "{% for i in l|reverse %}{{ i }},{% endfor %}"),
    ("reverse_string", "{{ s|reverse }}"),
    ("round", "{{ y|round }}|{{ y|round(1) }}|{{ y|round(1, 'floor') }}|{{ y|round(1, 'ceil') }}"),
    ("round_half", "{{ 2.5|round }}|{{ 0.125|round(2) }}"),
    ("safe", "{{ html|safe }}"),
    ('safe_non_string', '{{ 5|safe }}|{{ l|safe|first }}'),
    ("select", "{% for i in l|select('odd') %}{{ i }},{% endfor %}"),
    ("select_no_test", "{% for i in [0, 1, '', 'a']|select %}{{ i }},{% endfor %}"),
    ("select_test_arg", "{% for i in l|select('divisibleby', 3) %}{{ i }},{% endfor %}"),
    ("selectattr", "{{ users|selectattr('age', 'equalto', 30)|map(attribute='name')|join(',') }}"),
    ("selectattr_truthy", "{{ users|selectattr('city')|map(attribute='name')|join(',') }}"),
    ("slice", "{% for c in [1, 2, 3, 4, 5]|slice(2) %}{% for x in c %}{{ x }},{% endfor %};{% endfor %}"),
    ("slice_fill", "{% for c in [1, 2, 3, 4, 5]|slice(3, 0) %}{% for x in c %}{{ x }},{% endfor %};{% endfor %}"),
    ("sort", "{% for i in l|sort %}{{ i }},{% endfor %}"),
    ("sort_reverse", "{% for i in l|sort(reverse=true) %}{{ i }},{% endfor %}"),
    ("sort_case", "{{ words|sort|join(',') }}|{{ words|sort(case_sensitive=true)|join(',') }}"),
    ("sort_attribute", "{{ users|sort(attribute='age')|map(attribute='name')|join(',') }}"),
    ("sort_mixed_numbers", "{% for i in [2, 1.5, 1]|sort %}{{ i }},{% endfor %}"),
    ("sort_equal_dicts", "{{ [{'a': 1}, {'a': 1}]|sort|length }}"),
    ("filter_bad_args_not_evaluated", "{{ s|upper(foo=1) if false else 'ok' }}"),
    ("sort_multi_attribute", "{{ users|sort(attribute='age,name')|map(attribute='name')|join(',') }}"),
    ("sort_numeric_strings", "{{ nums_str|sort|join(',') }}"),
    ("string", "{{ x|string ~ 'a' }}"),
    ('string_container', "{{ [1, 'a']|string|length }}|{{ 2.0|string }}|{{ (1 < 2)|string ~ '!' }}"),
    ("striptags", "{{ '<p>a  <b>b</b>\n c</p>'|striptags }}"),
    ("striptags_entities", "{{ 'a &amp; b'|striptags }}"),
    ("sum", "{{ l|sum }}|{{ l|sum(start=10) }}"),
    ("sum_attribute", "{{ users|sum(attribute='age') }}"),
    ("title", "{{ 'hello wORLD-foo'|title }}"),
    ("tojson_list", "{{ l|tojson }}"),
    ("tojson_dict", "{{ d|tojson }}"),
    ("tojson_dict_literal", "{{ {'b': 1, 'a': 2, 'C': 3}|tojson|replace(' ', '') }}"),
    ("tojson_string", "{{ html|tojson }}"),
    ("tojson_indent", "{{ {'a': [1]}|tojson(indent=2) }}"),
    ("tojson_none_bool", "{{ [none, true]|tojson }}"),
    ("trim", "[{{ '  a  '|trim }}]"),
    ("trim_chars", "[{{ 'xxaxx'|trim('x') }}]"),
    ("truncate", "{{ long|truncate(20) }}"),
    ("truncate_killwords", "{{ long|truncate(20, true) }}"),
    ("truncate_unicode_end", "{{ 'Hello wide world'|truncate(1, end='\u2026') }}"),
    ("wordwrap_whole_float_width", "{{ 'Hello wide world'|wordwrap(5.0) }}"),
    ("truncate_end", "{{ long|truncate(20, false, '…') }}"),
    ("truncate_leeway", "{{ 'abcdefghij'|truncate(8) }}|{{ 'abcdefghij'|truncate(8, leeway=0) }}"),
    ("truncate_short", "{{ 'short'|truncate(20) }}"),
    ("unique", "{% for i in dup|unique %}{{ i }},{% endfor %}"),
    ("unique_case", "{{ ['a', 'A', 'b']|unique|join(',') }}"),
    ("unique_attribute", "{{ users|unique(attribute='age')|map(attribute='name')|join(',') }}"),
    ("upper", "{{ s|upper }}"),
    ("urlencode", "{{ 'a b&c/d'|urlencode }}"),
    ("urlencode_dict", "{{ {'a': 'x y', 'b': 1}|urlencode }}"),
    ("urlize", "{{ 'see https://example.com now'|urlize }}"),
    ('urlize_www', "{{ 'go to www.example.com. now'|urlize }}"),
    ('urlize_bare_domain', "{{ 'see example.org, example.co and a.com'|urlize }}"),
    ('urlize_email', "{{ 'mail me@example.com or mailto:a@b.org but not @a@b.c'|urlize }}"),
    ('urlize_parens', "{{ '(see http://example.com/a_(b)) and <http://x.org>'|urlize }}"),
    ('urlize_options', "{{ 'http://example.com/very/long/path'|urlize(10, true, target='_blank') }}"),
    ('urlize_rel', "{{ 'example.org'|urlize(rel='me noopener') }}"),
    ('urlize_extra_schemes', "{{ 'ftp://host/x and tel:123 and tel:'|urlize(extra_schemes=['ftp://', 'tel:']) }}"),
    ('urlize_hosts', "{{ 'http://127.0.0.1:8080/x http://[::1]/ http://1.2.3 https://xn--bcher-kva.de HTTP://EXAMPLE.COM http://x.com:123456'|urlize }}"),
    ('urlize_escapes', '{{ \'a <b> & http://x.com/?a=1&b=2 "q"\'|urlize }}'),
    ('urlize_whitespace', "{{ 'a\\n\\thttp://x.com\\n'|urlize }}"),
    ('urlize_bad_scheme', "{{ 'x'|urlize(extra_schemes=['a']) }}"),
    ("wordcount", "{{ long|wordcount }}"),
    ("wordwrap", "{{ long|wordwrap(15) }}"),
    ("wordwrap_break", "{{ 'abcdefghij'|wordwrap(4) }}"),
    ("xmlattr", "<a{{ {'href': 'x&y', 'title': none, 'class': 'c'}|xmlattr }}>"),
    ("xmlattr_no_space", "<a{{ {'href': 'x'}|xmlattr(false) }}>"),
    ("filter_chain", "{{ s|lower|replace('o', '0')|upper }}"),
    ("filter_on_literal_list", "{{ [3, 1]|sort|first }}"),
    ("filter_precedence_unary", "{{ -3|abs }}"),
    ("filter_kwargs_only", "{{ l|join(d=',') }}"),
    ("unknown_filter", "{{ x|nonexistent }}"),
    ("unknown_filter_unused_branch", "{% if false %}{{ x|nonexistent }}{% endif %}ok"),
    ("filters_on_bool", "{{ true|int }}|{{ true|abs }}|{{ false|lower }}"),
    # equal items that cannot be ordered (task 0015)
    ("sort_equal_unorderable", "{{ [{'a': 1}, {'a': 1}]|sort|length }}|{{ [n, n]|sort|length }}"),
    ("unique_mixed_types", "{% for i in [1, 'a', 1, 2.0, 2] | unique %}{{ i }},{% endfor %}|{{ [n, 1, n]|unique|list|length }}"),
    # task 0019: filter behaviour
    ("attr_dict_item", "[{{ {'k': 1}|attr('k') is defined }}]"),
    ("batch_zero", "{% for b in [1, 2, 3]|batch(0) %}[{{ b|join(',') }}]{% endfor %}"),
    ("batch_fill_none", "{% for b in [1, 2, 3]|batch(2, none) %}{{ b|length }};{% endfor %}"),
    ("slice_more_than_items", "{% for c in [1, 2]|slice(3) %}[{{ c|join(',') }}]{% endfor %}"),
    ("slice_even_fill", "{% for c in [1, 2, 3, 4]|slice(2, 0) %}[{{ c|join(',') }}]{% endfor %}"),
    ("slice_negative", "[{% for c in [1, 2]|slice(-1) %}x{% endfor %}]"),
    ("center_odd", "[{{ 'ab'|center(5) }}][{{ 'abc'|center(6) }}][{{ 'é'|center(4) }}]"),
    ("center_number", "[{{ 7|center(3) }}]"),
    ("default_none_boolean", "[{{ n|default('dflt', true) }}]"),
    ("float_edges", "{{ true|float }}|{{ '1_0.5'|float }}|{{ n|float }}|{{ ' 2 '|float }}|{{ l|float }}"),
    ("int_edges", "{{ ' 0x1A'|int(base=16) }}|{{ '0b11'|int(base=0) }}|{{ '1_000'|int }}|{{ ' 12 '|int }}|{{ '1e3'|int }}|{{ n|int }}|{{ l|int }}|{{ 'inf'|int }}|{{ '12'|int(base=8) }}|{{ '-7'|int }}|{{ '010'|int(base=0) }}|{{ '1__0'|int }}"),
    ("int_bool_float", "{{ false|int }}|{{ -3.9|int }}|{{ true|float }}"),
    ("abs_string", "{{ 'a'|abs }}"),
    ("abs_values", "{{ -3|abs }}|{{ false|abs }}|{{ -0.5|abs }}"),
    ("round_int", "{{ 3|round }}|{{ 3|round(1) }}|{{ true|round }}|{{ 1234|round(-2) }}|{{ 1250|round(-2) }}|{{ 1350|round(-2) }}|{{ -1250|round(-2) }}"),
    ("round_float_edges", "{{ 1234.5|round(-2) }}|{{ 3|round(method='ceil') }}|{{ -10.5|round(method='ceil') }}|{{ -10.5|round(method='floor') }}|{{ 2.675|round(2) }}|{{ -0.4|round }}|{{ 0.5|round }}|{{ 1.5|round }}|{{ 1e20|round(2) }}|{{ 5e-324|round(400) }}"),
    ("round_bad_method", "{{ 2|round(method='x') }}"),
    ("round_string", "{{ 'x'|round }}"),
    ("format_flags", "{{ '%05d|%+d|% d|%-5d|%.3d|%x|%#X|%#o|%o'|format(42, 5, 5, 7, 5, 255, 255, 8, -8) }}"),
    ("format_strings", "[{{ '%5s|%-5s|%.2s|%r|%c%c'|format('ab', 'cd', 'xyz', 'q', 65, 'z') }}]"),
    ("format_floats", "{{ '%e|%E|%g|%G|%#g|%10.3f|%-10.2e|%010.2f|%+.1f'|format(12345.678, 0.00001, 1e20, 1e-5, 1.0, 3.14159, 1234.5, -3.14159, 2.0) }}"),
    ("format_star", "[{{ '%*d|%-*.*f'|format(5, 3, 8, 2, 3.14159) }}]"),
    ("format_int_of_float", "{{ '%d %i %x'|format(3.9, true, 255) }}"),
    ("format_named_repr", "{{ '%(a)s %(a)r %(b)05.1f %%'|format(a='x', b=2) }}"),
    ("format_values_str", "{{ '%s|%s|%s|%s'|format([1, 'a'], none, true, 1.0) }}"),
    ("format_zero_pad_after_precision", "{{ '%05.2x|%06.3x|%#08.3x|%-6.3d|%+06d|%05.2o'|format(11, 188, 11, -5, 42, 1) }}"),
    ("format_too_few", "{{ '%s %s'|format('a') }}"),
    ("format_too_many", "{{ '%s'|format('a', 'b') }}"),
    ("format_bad_type", "{{ '%d'|format('x') }}"),
    ("format_mixed_args", "{{ '%s'|format('a', b=1) }}"),
    ("format_incomplete", "{{ '50%'|format() }}"),
    ("format_not_string", "{{ 5|format() }}"),
    ("groupby_case", "{% for k, v in ['CA', 'NY', 'ca']|groupby(0) %}{{ k }}={{ v|join(',') }};{% endfor %}"),
    ("groupby_case_sensitive", "{% for k, v in ['CA', 'NY', 'ca']|groupby(0, case_sensitive=true) %}{{ k }}={{ v|join(',') }};{% endfor %}"),
    ("groupby_index_and_repr", "{{ (users|groupby('age'))[0][0] }}|{{ (users|groupby('age')|first).list|length }}|{{ [1, 2]|groupby(0) if false else 'ok' }}"),
    ("groupby_dotted", "{% for k, v in [{'a': {'b': 2} }, {'a': {'b': 1} }]|groupby('a.b') %}{{ k }};{% endfor %}"),
    ("map_attribute_dotted", "{{ [{'a': {'b': 1} }, {'a': [5, 6]}]|map(attribute='a.b')|list|length }}|{{ [[1, [2, 3]]]|map(attribute='1.0')|join }}"),
    ("map_attr_filter", "[{{ users|map('attr', 'name')|select('defined')|list|length }}]"),
    ("sort_dotted_attribute", "{{ [{'a': {'b': 2}, 'n': 'x'}, {'a': {'b': 1}, 'n': 'y'}]|sort(attribute='a.b')|map(attribute='n')|join }}"),
    ("selectattr_dotted", "{{ [{'a': {'b': 0} }, {'a': {'b': 1} }]|selectattr('a.b')|list|length }}"),
    ("striptags_more", "[{{ 'a<!-- <b> -->b <br/>c&lt;d&gt; &#65;&#x42;&#67 &nbsp;x &bogus; e  f'|striptags }}]"),
    ("striptags_unclosed", "[{{ 'a <b c<!-- d'|striptags }}]"),
    ("title_delimiters", "{{ 'a(bC)d[eF]{gH}<iJ>k\tlM 1st o\\'neil'|title }}"),
    ("trim_whitespace", "[{{ ' \t a  b \n'|trim }}][{{ 'abcba'|trim('ab') }}][{{ 'éaé'|trim('é') }}][{{ 12|trim('1') }}]"),
    ("tojson_escapes", "{{ {'k': 'é☃\U0001F600<&>\\'\"\\\\\n\t\x01'}|tojson }}"),
    ("tojson_numbers", "{{ [1.5, 1e20, -0.0, 1, 2.0]|tojson }}"),
    ("tojson_nested_indent", "{{ {'b': [], 'a': {}, 'c': [1, {'d': none}]}|tojson(indent=1) }}"),
    ("tojson_indent_zero_string", "{{ [1, 2]|tojson(indent=0) }}|{{ [1]|tojson(indent='--') }}"),
    ("tojson_tuple_items", "{{ (1, 'a')|tojson }}|{{ {'a': 1}|items|list|tojson }}"),
    ("truncate_edges", "{{ 'foo bar baz qux'|truncate(9) }}|{{ 'foo bar baz qux'|truncate(11, true, leeway=0) }}|{{ 'foo bar baz qux'|truncate(6, true) }}|{{ 'ééééééééééé'|truncate(5, leeway=0) }}"),
    ("truncate_bad_length", "{{ 'abc'|truncate(1) }}"),
    ("urlencode_more", "{{ 'é ~_.-/?'|urlencode }}|{{ 5|urlencode }}|{{ [('a b', 'c/d'), ('e', 1)]|urlencode }}|{{ {'é': none}|urlencode }}"),
    ("xmlattr_values", "<a{{ {'b': true, 'n': 1.5, 'l': [1, '<'], 'u': nope}|xmlattr }}>"),
    ("xmlattr_bad_key", "<a{{ {'a b': 1}|xmlattr }}>"),
    ("lower_upper_non_string", "{{ 12|lower }}|{{ n|upper }}|{{ 1.5|title }}|{{ true|capitalize }}|{{ 12|replace('1', 'x') }}|{{ 123|wordcount }}|{{ [1]|upper }}"),
    ("truncate_huge", "{{ 'abc def'|truncate(9223372036854775807) }}|{{ 'abc def'|truncate(1e30) }}|{{ 'abc def ghi'|truncate(4, leeway=9223372036854775807) }}"),
    ("format_percent_after_width", "{{ '%5%'|format(1) }}"),
    ("format_length_modifier", "{{ '%ld|%hi|%Lf'|format(1, 2, 3) }}"),
    ("format_double_length_modifier", "{{ '%lld'|format(1) }}"),
    ("format_nan_sign", "{{ '%f|%+5f'|format(1e999 - 1e999, -(1e999 - 1e999)) }}"),
    ("round_ceil_negative_zero", "{{ -0.5|round(0, 'ceil') }}|{{ -2.5|round(-1, 'ceil') }}|{{ -0.5|round(0, 'floor') }}"),
    ("round_ceil_overflow", "{{ 1.5|round(400, 'ceil') }}"),
    # task 0048: leftovers of 0019
    ("case_non_ascii", "{{ 'éa'|upper }}|{{ 'ÉA'|title }}|{{ 'ÉA'|lower }}|{{ 'éa'|capitalize }}"),
    ("striptags_named_entities", "[{{ '&hearts; &frac12; &amp x'|striptags }}]"),
    ("int_out_of_range", "{{ '99999999999999999999'|int }}|{{ 1e20|int }}"),
    ("round_int_overflow", "{{ 9223372036854775807|round(-1) }}|{{ 12345678901234567890|round(-19) }}"),
    ("format_d_big_float", "{{ '%d'|format(1e30) }}"),
    ("format_ascii_repr", "{{ '%a'|format('\\u00e9') }}"),
    ("format_without_percent", "{{ 'x'|format(1) }}"),
    ("int_unicode_digits", "{{ '١٢'|int }}|{{ '１２'|float }}"),
    ("tojson_undefined", "{{ nope|tojson }}"),
    ("batch_none", "{% for b in none|batch(2) %}x{% endfor %}"),
    ("map_missing_parent", "{{ users|map(attribute='addr.zip')|list|length }}"),
]
