"""Builtin filters. List results are iterated or joined as strings, so list repr (output.py)
and join of numbers do not mask the behaviour of the filter under test."""
CONTEXT = {"x": 3, "neg": -3, "y": 2.567, "s": "Hello World", "l": [3, 1, 2], "dup": [3, 1, 3, 2, 1],
           "words": ["b", "A", "c"], "d": {"b": 2, "a": 1, "C": 3}, "e": [], "n": None,
           "html": "<b>Tom & \"Jerry\"</b>", "long": "The quick brown fox jumps over the lazy dog",
           "users": [{"name": "bob", "age": 30, "city": "Oslo"}, {"name": "alice", "age": 25, "city": "Rome"},
                     {"name": "carl", "age": 30, "city": "Oslo"}, {"name": "dan", "age": 41}],
           "lines": "a\nb\n\nc", "nums_str": ["10", "9", "100"]}
CASES = [
    ("abs", "{{ neg|abs }}|{{ -2.5|abs }}"),
    ("attr", "{{ users[0]|attr('name') }}"),
    ("attr_missing", "[{{ users[0]|attr('nope') }}]"),
    ("batch", "{% for b in l|batch(2) %}{% for x in b %}{{ x }},{% endfor %};{% endfor %}"),
    ("batch_fill", "{% for b in l|batch(2, 'x') %}{% for x in b %}{{ x }},{% endfor %};{% endfor %}"),
    ("capitalize", "{{ 'hELLO wORLD'|capitalize }}"),
    ("center", "[{{ 'abc'|center(9) }}]"),
    ("center_default", "[{{ 'abc'|center }}]"),
    ("count", "{{ l|count }}"),
    ("default", "{{ nope|default('dflt') }}"),
    ("default_alias", "{{ nope|d('dflt') }}"),
    ("default_defined_none", "[{{ n|default('dflt') }}]"),
    ("default_boolean", "{{ ''|default('dflt', true) }}|{{ ''|default('dflt', boolean=true) }}"),
    ("dictsort", "{% for k, v in d|dictsort %}{{ k }}={{ v }};{% endfor %}"),
    ("dictsort_case_sensitive", "{% for k, v in d|dictsort(true) %}{{ k }};{% endfor %}"),
    ("dictsort_by_value", "{% for k, v in d|dictsort(by='value') %}{{ k }};{% endfor %}"),
    ("dictsort_reverse", "{% for k, v in d|dictsort(reverse=true) %}{{ k }};{% endfor %}"),
    ("dictsort_stable", "{% for k, v in {'b': 1, 'a': 1, 'c': 0}|dictsort(by='value') %}{{ k }}{% endfor %}"),
    ("dictsort_stable_reverse", "{% for k, v in {'b': 1, 'a': 1, 'c': 0}|dictsort(by='value', reverse=true) %}{{ k }}{% endfor %}"),
    ("escape", "{{ html|escape }}"),
    ("escape_alias", "{{ html|e }}"),
    ("escape_single_quote", "{{ \"it's\"|e }}"),
    ("filesizeformat", "{{ 1234567|filesizeformat }}|{{ 100|filesizeformat }}|{{ 1000|filesizeformat }}"),
    ("filesizeformat_binary", "{{ 1234567|filesizeformat(true) }}"),
    ("first", "{{ l|first }}"),
    ("first_empty", "[{{ e|first }}]"),
    ("first_string", "{{ s|first }}"),
    ("float", "{{ '3.5'|float }}|{{ 3|float }}|{{ 'x'|float }}|{{ 'x'|float(1.5) }}"),
    ("forceescape", "{{ html|forceescape }}"),
    ("format_percent", "{{ '%s-%d'|format('a', 3) }}"),
    ("format_float", "{{ '%.2f'|format(3.14159) }}"),
    ("format_named", "{{ '%(a)s!'|format(a='x') }}"),
    ("groupby", "{% for g in users|groupby('age') %}{{ g.grouper }}:{{ g.list|map(attribute='name')|join(',') }};{% endfor %}"),
    ("groupby_tuple_unpack", "{% for age, items in users|groupby('age') %}{{ age }}={{ items|length }};{% endfor %}"),
    ("groupby_default", "{% for g in users|groupby('city', default='?') %}{{ g.grouper }};{% endfor %}"),
    ("indent", "{{ lines|indent(2) }}"),
    ("indent_first", "{{ lines|indent(2, true) }}"),
    ("indent_blank", "{{ lines|indent(2, blank=true) }}"),
    ("indent_string", "{{ lines|indent('> ') }}"),
    ("int", "{{ 3.7|int }}|{{ '42'|int }}|{{ 'x'|int }}|{{ 'x'|int(7) }}"),
    ("int_base", "{{ '0x1A'|int(0, 16) }}|{{ '101'|int(base=2) }}"),
    ("int_float_string", "{{ '3.9'|int }}"),
    ("items", "{% for k, v in {'a': 1}|items %}{{ k }}{{ v }}{% endfor %}"),
    ("join_strings", "{{ words|join }}|{{ words|join(', ') }}"),
    ("join_numbers", "{{ l|join }}|{{ l|join(', ') }}"),
    ("join_mixed", "{{ [1, 'a', 2.5]|join('-') }}"),
    ("join_attribute", "{{ users|join(',', attribute='name') }}"),
    ("last", "{{ l|last }}"),
    ("length", "{{ l|length }}|{{ s|length }}|{{ d|length }}"),
    ("list_string", "{{ 'abc'|list|join(',') }}"),
    ("list_dict", "{{ {'a': 1}|list|join(',') }}"),
    ("list_dict_order", "{{ {'b': 1, 'a': 2, 'C': 3}|list|join(',') }}"),
    ("lower", "{{ s|lower }}"),
    ("map_attribute", "{{ users|map(attribute='name')|join(',') }}"),
    ("map_attribute_default", "{{ users|map(attribute='city', default='?')|join(',') }}"),
    ("map_filter", "{{ words|map('upper')|join(',') }}"),
    ("map_filter_args", "{{ l|map('string')|map('center', 3)|join('|') }}"),
    ("max", "{{ l|max }}|{{ words|max }}"),
    ("max_attribute", "{{ (users|max(attribute='age')).name }}"),
    ("max_case_sensitive", "{{ words|max(case_sensitive=true) }}"),
    ("min", "{{ l|min }}|{{ words|min }}"),
    ("pprint", "{{ d|pprint }}"),
    ("pprint_dict_literal", "{{ {'b': 1, 'a': 2, 'C': 3}|pprint }}"),
    ("reject", "{% for i in l|reject('odd') %}{{ i }},{% endfor %}"),
    ("rejectattr", "{{ users|rejectattr('age', 'gt', 26)|map(attribute='name')|join(',') }}"),
    ("rejectattr_truthy", "{{ users|rejectattr('city')|map(attribute='name')|join(',') }}"),
    ("replace", "{{ 'a b c'|replace(' ', '_') }}"),
    ("replace_count", "{{ 'a b c'|replace(' ', '_', 1) }}"),
    ("reverse_list", "{% for i in l|reverse %}{{ i }},{% endfor %}"),
    ("reverse_string", "{{ s|reverse }}"),
    ("round", "{{ y|round }}|{{ y|round(1) }}|{{ y|round(1, 'floor') }}|{{ y|round(1, 'ceil') }}"),
    ("round_half", "{{ 2.5|round }}|{{ 0.125|round(2) }}"),
    ("safe", "{{ html|safe }}"),
    ("select", "{% for i in l|select('odd') %}{{ i }},{% endfor %}"),
    ("select_no_test", "{% for i in [0, 1, '', 'a']|select %}{{ i }},{% endfor %}"),
    ("select_test_arg", "{% for i in l|select('divisibleby', 3) %}{{ i }},{% endfor %}"),
    ("selectattr", "{{ users|selectattr('age', 'equalto', 30)|map(attribute='name')|join(',') }}"),
    ("selectattr_truthy", "{{ users|selectattr('city')|map(attribute='name')|join(',') }}"),
    ("slice", "{% for c in [1, 2, 3, 4, 5]|slice(2) %}{% for x in c %}{{ x }},{% endfor %};{% endfor %}"),
    ("slice_fill", "{% for c in [1, 2, 3, 4, 5]|slice(3, 0) %}{% for x in c %}{{ x }},{% endfor %};{% endfor %}"),
    ("sort", "{% for i in l|sort %}{{ i }},{% endfor %}"),
    ("sort_reverse", "{% for i in l|sort(reverse=true) %}{{ i }},{% endfor %}"),
    ("sort_case", "{{ words|sort|join(',') }}|{{ words|sort(case_sensitive=true)|join(',') }}"),
    ("sort_attribute", "{{ users|sort(attribute='age')|map(attribute='name')|join(',') }}"),
    ("sort_multi_attribute", "{{ users|sort(attribute='age,name')|map(attribute='name')|join(',') }}"),
    ("sort_numeric_strings", "{{ nums_str|sort|join(',') }}"),
    ("string", "{{ x|string ~ 'a' }}"),
    ("striptags", "{{ '<p>a  <b>b</b>\n c</p>'|striptags }}"),
    ("striptags_entities", "{{ 'a &amp; b'|striptags }}"),
    ("sum", "{{ l|sum }}|{{ l|sum(start=10) }}"),
    ("sum_attribute", "{{ users|sum(attribute='age') }}"),
    ("title", "{{ 'hello wORLD-foo'|title }}"),
    ("tojson_list", "{{ l|tojson }}"),
    ("tojson_dict", "{{ d|tojson }}"),
    ("tojson_dict_literal", "{{ {'b': 1, 'a': 2, 'C': 3}|tojson|replace(' ', '') }}"),
    ("tojson_string", "{{ html|tojson }}"),
    ("tojson_indent", "{{ {'a': [1]}|tojson(indent=2) }}"),
    ("tojson_none_bool", "{{ [none, true]|tojson }}"),
    ("trim", "[{{ '  a  '|trim }}]"),
    ("trim_chars", "[{{ 'xxaxx'|trim('x') }}]"),
    ("truncate", "{{ long|truncate(20) }}"),
    ("truncate_killwords", "{{ long|truncate(20, true) }}"),
    ("truncate_end", "{{ long|truncate(20, false, '…') }}"),
    ("truncate_leeway", "{{ 'abcdefghij'|truncate(8) }}|{{ 'abcdefghij'|truncate(8, leeway=0) }}"),
    ("truncate_short", "{{ 'short'|truncate(20) }}"),
    ("unique", "{% for i in dup|unique %}{{ i }},{% endfor %}"),
    ("unique_case", "{{ ['a', 'A', 'b']|unique|join(',') }}"),
    ("unique_attribute", "{{ users|unique(attribute='age')|map(attribute='name')|join(',') }}"),
    ("upper", "{{ s|upper }}"),
    ("urlencode", "{{ 'a b&c/d'|urlencode }}"),
    ("urlencode_dict", "{{ {'a': 'x y', 'b': 1}|urlencode }}"),
    ("urlize", "{{ 'see https://example.com now'|urlize }}"),
    ("wordcount", "{{ long|wordcount }}"),
    ("wordwrap", "{{ long|wordwrap(15) }}"),
    ("wordwrap_break", "{{ 'abcdefghij'|wordwrap(4) }}"),
    ("xmlattr", "<a{{ {'href': 'x&y', 'title': none, 'class': 'c'}|xmlattr }}>"),
    ("xmlattr_no_space", "<a{{ {'href': 'x'}|xmlattr(false) }}>"),
    ("filter_chain", "{{ s|lower|replace('o', '0')|upper }}"),
    ("filter_on_literal_list", "{{ [3, 1]|sort|first }}"),
    ("filter_precedence_unary", "{{ -3|abs }}"),
    ("filter_kwargs_only", "{{ l|join(d=',') }}"),
    ("unknown_filter", "{{ x|nonexistent }}"),
    ("unknown_filter_unused_branch", "{% if false %}{{ x|nonexistent }}{% endif %}ok"),
    ("filters_on_bool", "{{ true|int }}|{{ true|abs }}|{{ false|lower }}"),
]
