"""Global functions: range, dict, cycler, joiner, namespace, lipsum."""
CASES = [
    ("range_stop", "{% for i in range(4) %}{{ i }},{% endfor %}"),
    ("range_start_stop", "{% for i in range(2, 5) %}{{ i }},{% endfor %}"),
    ("range_step", "{% for i in range(1, 10, 3) %}{{ i }},{% endfor %}"),
    ("range_negative_step", "{% for i in range(5, 0, -2) %}{{ i }},{% endfor %}"),
    ("range_empty", "[{% for i in range(0) %}{{ i }},{% endfor %}]"),
    ("range_length", "{{ range(10)|length }}"),
    ("range_list", "{{ range(3)|list }}"),
    ("dict", "{{ dict(a=1)['a'] }}"),
    ("dict_print", "{{ dict(a=1, b=2) }}"),
    ("cycler_next", "{% set c = cycler('a', 'b') %}{{ c.next() }}{{ c.next() }}{{ c.next() }}"),
    ("cycler_current", "{% set c = cycler('a', 'b') %}{{ c.current }}{% do c.next() %}{{ c.current }}", {"env": {"extensions": ["do"]}}),
    ("cycler_reset", "{% set c = cycler('a', 'b') %}{{ c.next() }}{{ c.reset() }}{{ c.next() }}"),
    ("joiner", "{% set j = joiner(',') %}{% for i in [1, 2, 3] %}{{ j() }}{{ i }}{% endfor %}"),
    ("joiner_default", "{% set j = joiner() %}{% for i in [1, 2] %}{{ j() }}{{ i }}{% endfor %}"),
    ("range_step_inexact", "{% for i in range(0, 10, 3) %}{{ i }},{% endfor %}"),
    ("range_negative_inexact", "{% for i in range(10, 0, -3) %}{{ i }},{% endfor %}|{{ range(10, 0, -3)|length }}"),
    ("range_negative_empty", "[{% for i in range(0, 5, -1) %}{{ i }},{% endfor %}]"),
    ("range_object_step", "{{ range(5, 0, -2) }}|{{ range(2, 8, 1) }}|{{ range(0) }}"),
    ("range_int64_bounds", "{% for i in range(-9223372036854775807, 9223372036854775807, 4611686018427387904) %}{{ i }},{% endfor %}|{{ range(9223372036854775807, -9223372036854775807, -9223372036854775807)|list }}"),
    ("range_zero_step", "{{ range(1, 5, 0) }}"),
    ("range_set_print", "{% set r = range(1, 3) %}{{ r }}|{{ r|list }}|{{ r|first }}"),
    ("dict_from_mapping", "{{ dict({'a': 1}, b=2) }}"),
    ("dict_from_pairs", "{{ dict([('a', 1), ('b', 2)]) }}"),
    ("dict_from_string_pairs", "{{ dict(['ab', 'cd']) }}|{% set d = dict([('x', 'yz'), 'pq']) %}{{ d['p'] }}{{ d|length }}"),
    ("dict_bad_pair", "{{ dict(['abc']) }}"),
    ("dict_empty", "{{ dict() }}|{{ dict()|length }}"),
    ("cycler_items_pos", "{% set c = cycler(1, 2, 3) %}{{ c.next() }}{{ c.items }}{{ c.pos }}"),
    ("cycler_items_list", "{% set c = cycler(1, 2) %}{{ c.items|list }}"),
    ("cycler_shared_across_loops", "{% set c = cycler('odd', 'even') %}{% for i in [1, 2, 3] %}{{ c.next() }},{% endfor %}{% for i in [1, 2] %}{{ c.next() }},{% endfor %}"),
    ("cycler_no_items", "{% set c = cycler() %}{{ c.next() }}"),
    ("joiner_two_loops", "{% set j = joiner('|') %}{% for i in [1, 2] %}{{ j() }}{{ i }}{% endfor %}{% for i in [3] %}{{ j() }}{{ i }}{% endfor %}"),
    ("lipsum_paragraphs", "{{ lipsum(3, html=False)|list|select('equalto', '\\n')|list|length }}|{% set h = lipsum(2) %}{{ h|list|select('equalto', '\\n')|list|length }}|{{ h|first }}{{ h|last }}"),
    ("lipsum_word_bounds", "{% set w = lipsum(1, False, 5, 6)|wordcount %}{{ w }}"),
    ("int_called_in_loop", "{% for x in [1] %}{% set f = 2 %}{{ f('a', 'b') }}{% endfor %}"),
    ("cycler_not_mapping", "{% set c = cycler(1) %}{{ 'T' if c is mapping else 'F' }}"),
    ("range_float_argument", "{{ range(1.5)|list }}"),
    ("namespace_kwargs", "{% set ns = namespace(a=1, b=2) %}{{ ns.a + ns.b }}"),
    ("lipsum_html", "{{ lipsum(2)|wordcount > 0 }}"),
    ("undefined_global_call", "{{ no_such_function() }}"),
]
