"""Literal syntax: numbers, strings, collections, constants."""
CASES = [
    ("int", "{{ 42 }}"),
    ("int_negative", "{{ -42 }}"),
    ("int_underscore", "{{ 1_000_000 }}"),
    ("int_hex", "{{ 0x1F }}"),
    ("int_octal", "{{ 0o17 }}"),
    ("int_binary", "{{ 0b101 }}"),
    ("int_prefix_upper_underscore", "{{ 0XFF_FF }}|{{ 0O_17 }}|{{ 0B1_0 }}"),
    ("int_hex_then_keyword", "{{ 'T' if 0x1for 0 else 'F' }}"),
    ("int_zero_forms", "{{ 0_0 }}|{{ 00 }}|{{ 0_1.5 }}|{{ 01.5 }}"),
    ("int_after_float_overflow", "{{ 'T' if 1e400 > 0 else 'F' }}{{ 4611686018427387904 + 1 }}"),
    ("int_big", "{{ 12345678901234567890 }}"),
    ("float", "{{ 1.5 }}"),
    ("float_whole", "{{ 2.0 }}"),
    ("float_exponent", "{{ 1e3 }}"),
    ("float_exponent_negative", "{{ 2.5e-3 }}"),
    ("float_underscore", "{{ 1_000.5 }}"),
    ("float_exponent_underscore", "{{ 1_5e-0_1 }}"),
    ("float_precision", "{{ 0.1 + 0.2 }}"),
    ("float_large", "{{ 1e20 }}"),
    ("float_small", "{{ 1e-7 }}"),
    ("string_single", "{{ 'abc' }}"),
    ("string_double", '{{ "abc" }}'),
    ("string_escape_quote", r"{{ 'it\'s' }}"),
    ("string_escape_newline", r"{{ 'a\nb' }}"),
    ("string_escape_tab", r"{{ 'a\tb' }}"),
    ("string_escape_backslash", r"{{ 'a\\b' }}"),
    ("string_escape_unicode", r"{{ 'é' }}"),
    ("string_escape_hex_octal", r"{{ 'A\x42\u0043\U00000044\105' }}"),
    ("string_escape_control", r"{{ '\a\b\f\v\0' == 'abfv0' }}|{{ '\a\b\f\v\0'|length }}"),
    ("string_escape_named", r"{{ '\N{BULLET}' }}"),
    ("string_unicode_literal", "{{ 'héllo ✓' }}"),
    ("string_adjacent_concat", "{{ 'a' 'b' }}"),
    ("string_adjacent_mixed_quotes", """{{ 'a' "b" 'c' ~ 'd' }}"""),
    ("bool_lower", "{{ true }}|{{ false }}"),
    ("bool_title", "{{ True }}|{{ False }}"),
    ("none_lower", "{{ none }}"),
    ("none_title", "{{ None }}"),
    ("list", "{{ [1, 2, 3] }}"),
    ("list_empty", "{{ [] }}"),
    ("list_trailing_comma", "{{ [1, 2,] }}"),
    ("list_nested", "{{ [[1], [2, [3]]] }}"),
    ("list_mixed", "{{ [1, 'a', none, true, 1.5] }}"),
    ("tuple", "{{ (1, 2) }}"),
    ("tuple_single", "{{ (1,) }}"),
    ("tuple_empty", "{{ () }}"),
    ("tuple_trailing_comma", "{% for i in (1, 2,) %}{{ i }},{% endfor %}{{ (1,)|length }}{{ ()|length }}"),
    ("dict", "{{ {'a': 1} }}"),
    ("dict_empty", "{{ {} }}"),
    ("dict_order", "{{ {'b': 1, 'a': 2, 'c': 3} }}"),
    ("dict_int_key", "{{ {1: 'x'}[1] }}"),
    ("dict_nested", "{{ {'a': {'b': [1]}} }}"),
    ("dict_trailing_comma", "{{ {'a': 1,}['a'] }}"),
    ("dict_expression_key", "{% set k = 'x' %}{{ {k: 1, k ~ 'y': 2}['xy'] }}"),
    ("dict_nested_lookup", "{% set d = {'a': {'b': [1, 2]}} %}{{ d['a']['b'][1] }}"),
    ("parenthesised", "{{ (1) }}"),
    ("number_dot_attribute", "[{{ 1.e3 }}][{{ 1.5.2 }}]"),
]
