"""Template composition: include, import, from-import, extends, blocks."""
CONTEXT = {"x": 3, "name": "world"}
T = {
    "hello.j2": "Hello {{ name }}!",
    "uses_x.j2": "[{{ x }}]",
    "lib_default.j2": "{% set g = 'lib' %}{% macro m(a=g) %}{{ a }}{% endmacro %}",
    "macros.j2": "{% macro greet(n) %}hi {{ n }}{% endmacro %}{% macro ctx() %}{{ name }}{% endmacro %}{% set const = 42 %}{% set _private = 1 %}",
    "base.j2": "<{% block head %}H{% endblock %}|{% block body %}B{% endblock %}>",
    "child.j2": "{% extends 'base.j2' %}{% block body %}C{% endblock %}",
    "child_super.j2": "{% extends 'base.j2' %}{% block body %}C+{{ super() }}{% endblock %}",
    "grandchild.j2": "{% extends 'child_super.j2' %}{% block body %}G+{{ super() }}{% endblock %}",
    "loop_base.j2": "{% for i in [1, 2] %}{% block item %}{{ i }}{% endblock %}{% endfor %}",
    "required_base.j2": "{% block r required %}{% endblock %}",
    "nested_blocks.j2": "{% block outer %}O{% block inner %}I{% endblock %}{% endblock %}",
    "include_inner.j2": "inner({{ x }})",
    "outer_include.j2": "outer:{% include 'include_inner.j2' %}",
}
L = {"templates": T}
CASES = [
    ("include", "{% include 'hello.j2' %}", L),
    ("include_context", "{% set x = 9 %}{% include 'uses_x.j2' %}", L),
    ("include_loop_var", "{% for x in [1, 2] %}{% include 'uses_x.j2' %}{% endfor %}", L),
    ("include_without_context", "{% include 'uses_x.j2' without context %}", L),
    ("include_ignore_missing", "a{% include 'missing.j2' ignore missing %}b", L),
    ("include_missing", "{% include 'missing.j2' %}", L),
    ("include_list", "{% include ['missing.j2', 'hello.j2'] %}", L),
    ("include_variable", "{% set t = 'hello.j2' %}{% include t %}", L),
    ("include_nested", "{% include 'outer_include.j2' %}", L),
    ("import_as", "{% import 'macros.j2' as m %}{{ m.greet('a') }}", L),
    ("import_variable", "{% import 'macros.j2' as m %}{{ m.const }}", L),
    ("import_macro_default", "{% import 'lib_default.j2' as L %}{{ L.m() }}", L),
    ("from_import_macro_default", "{% from 'lib_default.j2' import m %}{{ m() }}", L),
    ("import_no_context", "{% import 'macros.j2' as m %}[{{ m.ctx() }}]", L),
    ("import_with_context", "{% import 'macros.j2' as m with context %}[{{ m.ctx() }}]", L),
    ("from_import", "{% from 'macros.j2' import greet %}{{ greet('b') }}", L),
    ("from_import_as", "{% from 'macros.j2' import greet as g, const %}{{ g('c') }}{{ const }}", L),
    ("from_import_private", "{% from 'macros.j2' import _private %}", L),
    ("from_import_missing_name", "{% from 'macros.j2' import nope %}[{{ nope }}]", L),
    ("extends", "{% extends 'base.j2' %}{% block head %}h{% endblock %}", L),
    ("extends_two_levels", "{% extends 'child.j2' %}{% block head %}h{% endblock %}", L),
    ("extends_super", "{% extends 'child_super.j2' %}", L),
    ("extends_super_chain", "{% extends 'grandchild.j2' %}", L),
    ("extends_content_outside_blocks", "{% extends 'base.j2' %}ignored{% block body %}b{% endblock %}", L),
    ("extends_variable", "{% set p = 'base.j2' %}{% extends p %}", L),
    ("extends_conditional", "{% if true %}{% extends 'base.j2' %}{% endif %}", L),
    ("block_scoped", "{% extends 'loop_base.j2' %}{% block item %}[{{ i }}]{% endblock %}", L),
    ("block_scoped_keyword", "{% for i in [1, 2] %}{% block item scoped %}{{ i }}{% endblock %}{% endfor %}", L),
    ("block_unscoped_loop_var", "{% for i in [1, 2] %}{% block item %}[{{ i }}]{% endblock %}{% endfor %}", L),
    ("block_required_missing", "{% extends 'required_base.j2' %}", L),
    ("block_required_given", "{% extends 'required_base.j2' %}{% block r %}ok{% endblock %}", L),
    ("block_nested_override", "{% extends 'nested_blocks.j2' %}{% block inner %}i{% endblock %}", L),
    ("block_self_call", "{% block title %}T{% endblock %}|{{ self.title() }}", L),
    ("block_end_name", "{% block a %}x{% endblock a %}", L),
    ("block_end_name_mismatch", "{% block a %}x{% endblock b %}", L),
    ("block_duplicate", "{% block a %}{% endblock %}{% block a %}{% endblock %}", L),
    ("block_standalone", "{% block a %}standalone{% endblock %}", L),
    ("extends_output_before_kept", "pre{% extends 'base.j2' %}post{{ 'expr' }}", L),
    ("extends_conditional_false", "{% if false %}{% extends 'base.j2' %}{% endif %}tail{% block head %}X{% endblock %}", L),
    ("extends_conditional_output_dropped", "{% if true %}{% extends 'base.j2' %}after{% endif %}tail", L),
    ("extends_in_for", "{% for i in [1] %}{% extends 'base.j2' %}{% endfor %}", L),
    ("extends_twice_conditional", "{% if true %}{% extends 'base.j2' %}{% endif %}{% if true %}{% extends 'base.j2' %}{% endif %}", L),
    ("extends_none", "{% extends none %}", L),
    ("block_required_content", "{% block r required %}x{% endblock %}", L),
    ("block_required_standalone", "{% block r required %}{# c #} {% endblock %}", L),
    ("block_scoped_required", "{% extends 'scoped_required.j2' %}{% block r %}{{ i }}{% endblock %}",
     {"templates": {**T, "scoped_required.j2": "{% for i in [1, 2] %}{% block r scoped required %}{% endblock %}{% endfor %}"}}),
    ("block_scoped_in_child_only", "{% extends 'loop_base.j2' %}{% block item scoped %}[{{ i }}]{% endblock %}", L),
    ("block_super_missing", "{% block a %}{{ super() }}{% endblock %}", L),
    ("block_super_block_locals", "{% extends 'uses_y.j2' %}{% block a %}{% set y = 1 %}{{ super() }}{% endblock %}",
     {"templates": {**T, "uses_y.j2": "{% block a %}[{{ y }}]{% endblock %}"}}),
    ("block_self_before_definition", "{{ self.a() }}{% block a %}A{% endblock %}", L),
    ("block_self_override", "{% extends 'base.j2' %}{% block head %}{{ self.body() }}{% endblock %}{% block body %}NB{% endblock %}", L),
    ("block_sees_top_level_set", "{% extends 'base.j2' %}{% set g = 5 %}{% block head %}[{{ g }}]{% endblock %}", L),
    ("block_nested_duplicate", "{% block a %}{% block b %}{% endblock %}{% endblock %}{% block b %}{% endblock %}", L),
    ("include_does_not_leak_sets", "{% include 'sets_y.j2' %}[{{ y }}]", {"templates": {**T, "sets_y.j2": "{% set y = 1 %}"}}),
    ("import_name_per_iteration", "{% for t in ['ya.j2', 'yb.j2'] %}{% import t as m %}{{ m.y }}{% endfor %}",
     {"templates": {**T, "ya.j2": "{% set y = 'a' %}", "yb.j2": "{% set y = 'b' %}"}}),
    ("from_import_private_alias", "{% from 'macros.j2' import greet as _g %}{{ _g('x') }}", L),
]
