"""Template composition: include, import, from-import, extends, blocks."""
CONTEXT = {"x": 3, "name": "world"}
T = {
    "hello.j2": "Hello {{ name }}!",
    "uses_x.j2": "[{{ x }}]",
    "lib_default.j2": "{% set g = 'lib' %}{% macro m(a=g) %}{{ a }}{% endmacro %}",
    "macros.j2": "{% macro greet(n) %}hi {{ n }}{% endmacro %}{% macro ctx() %}{{ name }}{% endmacro %}{% set const = 42 %}{% set _private = 1 %}",
    "base.j2": "<{% block head %}H{% endblock %}|{% block body %}B{% endblock %}>",
    "child.j2": "{% extends 'base.j2' %}{% block body %}C{% endblock %}",
    "child_super.j2": "{% extends 'base.j2' %}{% block body %}C+{{ super() }}{% endblock %}",
    "grandchild.j2": "{% extends 'child_super.j2' %}{% block body %}G+{{ super() }}{% endblock %}",
    "loop_base.j2": "{% for i in [1, 2] %}{% block item %}{{ i }}{% endblock %}{% endfor %}",
    "required_base.j2": "{% block r required %}{% endblock %}",
    "nested_blocks.j2": "{% block outer %}O{% block inner %}I{% endblock %}{% endblock %}",
    "include_inner.j2": "inner({{ x }})",
    "outer_include.j2": "outer:{% include 'include_inner.j2' %}",
}
L = {"templates": T}
SHADOW = {"templates": {**T, "shadow.j2":
    "{% set g = 1 %}{% macro f(g) %}{{ g }}{% endmacro %}{% macro h() %}{% set g = 2 %}{{ g }}{% endmacro %}"
    "{% macro k() %}{{ g }}{% endmacro %}{% macro l() %}{% for g in [3] %}{{ g }}{% endfor %}{{ g }}{% endmacro %}"
    "{% macro w() %}{% with g = 4 %}{{ g }}{% endwith %}{{ g }}{% endmacro %}"
    "{% macro c() %}{{ caller(6) }}{% endmacro %}{% macro uc() %}{% call(g) c() %}{{ g }}{% endcall %}{% endmacro %}"
    "{% set h = {'a': 1} %}{% macro dct(h) %}{% set _ = h.update(z=1) %}{{ h }}{% endmacro %}"}}
SIB = {"templates": {**T, "sib.j2":
    "{% macro k() %}1{% endmacro %}{% macro a(g) %}[{{ k() }}]{% endmacro %}"
    "{% macro f() %}{% for i in [1, 2] %}{{ k() }}{% endfor %}{% endmacro %}{% set s = 'str' %}{% macro ps() %}{{ s }}{% endmacro %}"}}
CASES = [
    ("include", "{% include 'hello.j2' %}", L),
    ("include_context", "{% set x = 9 %}{% include 'uses_x.j2' %}", L),
    ("include_loop_var", "{% for x in [1, 2] %}{% include 'uses_x.j2' %}{% endfor %}", L),
    ("include_without_context", "{% include 'uses_x.j2' without context %}", L),
    ("include_ignore_missing", "a{% include 'missing.j2' ignore missing %}b", L),
    ("include_missing", "{% include 'missing.j2' %}", L),
    ("include_list", "{% include ['missing.j2', 'hello.j2'] %}", L),
    ("include_variable", "{% set t = 'hello.j2' %}{% include t %}", L),
    ("include_nested", "{% include 'outer_include.j2' %}", L),
    ("import_as", "{% import 'macros.j2' as m %}{{ m.greet('a') }}", L),
    ("import_variable", "{% import 'macros.j2' as m %}{{ m.const }}", L),
    ("import_macro_default", "{% import 'lib_default.j2' as L %}{{ L.m() }}", L),
    ("from_import_macro_default", "{% from 'lib_default.j2' import m %}{{ m() }}", L),
    ("import_no_context", "{% import 'macros.j2' as m %}[{{ m.ctx() }}]", L),
    ("import_with_context", "{% import 'macros.j2' as m with context %}[{{ m.ctx() }}]", L),
    ("from_import", "{% from 'macros.j2' import greet %}{{ greet('b') }}", L),
    ("from_import_as", "{% from 'macros.j2' import greet as g, const %}{{ g('c') }}{{ const }}", L),
    ("from_import_private", "{% from 'macros.j2' import _private %}", L),
    ("from_import_missing_name", "{% from 'macros.j2' import nope %}[{{ nope }}]", L),
    ("extends", "{% extends 'base.j2' %}{% block head %}h{% endblock %}", L),
    ("extends_two_levels", "{% extends 'child.j2' %}{% block head %}h{% endblock %}", L),
    ("extends_super", "{% extends 'child_super.j2' %}", L),
    ("extends_super_chain", "{% extends 'grandchild.j2' %}", L),
    ("extends_content_outside_blocks", "{% extends 'base.j2' %}ignored{% block body %}b{% endblock %}", L),
    ("extends_variable", "{% set p = 'base.j2' %}{% extends p %}", L),
    ("extends_conditional", "{% if true %}{% extends 'base.j2' %}{% endif %}", L),
    ("block_scoped", "{% extends 'loop_base.j2' %}{% block item %}[{{ i }}]{% endblock %}", L),
    ("block_scoped_keyword", "{% for i in [1, 2] %}{% block item scoped %}{{ i }}{% endblock %}{% endfor %}", L),
    ("block_unscoped_loop_var", "{% for i in [1, 2] %}{% block item %}[{{ i }}]{% endblock %}{% endfor %}", L),
    ("block_required_missing", "{% extends 'required_base.j2' %}", L),
    ("block_required_given", "{% extends 'required_base.j2' %}{% block r %}ok{% endblock %}", L),
    ("block_nested_override", "{% extends 'nested_blocks.j2' %}{% block inner %}i{% endblock %}", L),
    ("block_self_call", "{% block title %}T{% endblock %}|{{ self.title() }}", L),
    ("block_end_name", "{% block a %}x{% endblock a %}", L),
    ("block_end_name_mismatch", "{% block a %}x{% endblock b %}", L),
    ("block_duplicate", "{% block a %}{% endblock %}{% block a %}{% endblock %}", L),
    ("block_standalone", "{% block a %}standalone{% endblock %}", L),
    ("extends_output_before_kept", "pre{% extends 'base.j2' %}post{{ 'expr' }}", L),
    ("extends_conditional_false", "{% if false %}{% extends 'base.j2' %}{% endif %}tail{% block head %}X{% endblock %}", L),
    ("extends_conditional_output_dropped", "{% if true %}{% extends 'base.j2' %}after{% endif %}tail", L),
    ("extends_in_for", "{% for i in [1] %}{% extends 'base.j2' %}{% endfor %}", L),
    ("extends_twice_conditional", "{% if true %}{% extends 'base.j2' %}{% endif %}{% if true %}{% extends 'base.j2' %}{% endif %}", L),
    ("extends_none", "{% extends none %}", L),
    ("block_required_content", "{% block r required %}x{% endblock %}", L),
    ("block_required_standalone", "{% block r required %}{# c #} {% endblock %}", L),
    ("block_scoped_required", "{% extends 'scoped_required.j2' %}{% block r %}{{ i }}{% endblock %}",
     {"templates": {**T, "scoped_required.j2": "{% for i in [1, 2] %}{% block r scoped required %}{% endblock %}{% endfor %}"}}),
    ("block_scoped_in_child_only", "{% extends 'loop_base.j2' %}{% block item scoped %}[{{ i }}]{% endblock %}", L),
    ("block_super_missing", "{% block a %}{{ super() }}{% endblock %}", L),
    ("block_super_block_locals", "{% extends 'uses_y.j2' %}{% block a %}{% set y = 1 %}{{ super() }}{% endblock %}",
     {"templates": {**T, "uses_y.j2": "{% block a %}[{{ y }}]{% endblock %}"}}),
    ("block_self_before_definition", "{{ self.a() }}{% block a %}A{% endblock %}", L),
    ("block_super_as_value", "{% extends 'base.j2' %}{% block head %}{{ super()|lower }}{% set s = super() %}{{ s }}{% endblock %}", L),
    ("block_self_as_value", "{% block a %}x{% endblock %}{% set s = self.a() %}[{{ s|upper }}]", L),
    ("block_self_override", "{% extends 'base.j2' %}{% block head %}{{ self.body() }}{% endblock %}{% block body %}NB{% endblock %}", L),
    ("block_sees_top_level_set", "{% extends 'base.j2' %}{% set g = 5 %}{% block head %}[{{ g }}]{% endblock %}", L),
    ("block_nested_duplicate", "{% block a %}{% block b %}{% endblock %}{% endblock %}{% block b %}{% endblock %}", L),
    ("include_does_not_leak_sets", "{% include 'sets_y.j2' %}[{{ y }}]", {"templates": {**T, "sets_y.j2": "{% set y = 1 %}"}}),
    ("import_name_per_iteration", "{% for t in ['ya.j2', 'yb.j2'] %}{% import t as m %}{{ m.y }}{% endfor %}",
     {"templates": {**T, "ya.j2": "{% set y = 'a' %}", "yb.j2": "{% set y = 'b' %}"}}),
    ("from_import_private_alias", "{% from 'macros.j2' import greet as _g %}{{ _g('x') }}", L),
    # An included template sees the caller's names without copying them (docs/tasks/0108):
    # what it changes in place is seen by the caller, what it sets is not
    ("include_appends_to_caller_list", "{% set l = [1] %}{% include 'appends.j2' %}{{ l }}",
     {"templates": {**T, "appends.j2": "{{ l.append(2) }}"}}),
    ("include_sets_namespace", "{% set ns = namespace(v=1) %}{% include 'ns.j2' %}{{ ns.v }}",
     {"templates": {**T, "ns.j2": "{% set ns.v = ns.v + 1 %}"}}),
    ("include_set_shadows_caller", "{% set x = 1 %}{% for i in [1] %}{% include 'sets_x.j2' %}{{ x }}{% endfor %}{{ x }}",
     {"templates": {**T, "sets_x.j2": "{% set x = 2 %}{{ x }}"}}),
    ("include_sees_every_scope", "{% set a = 'A' %}{% for b in ['B'] %}{% with c = 'C' %}{% include 'abc.j2' %}{% endwith %}{% endfor %}",
     {"templates": {**T, "abc.j2": "{{ a }}{{ b }}{{ c }}|{% include 'abc_inner.j2' %}", "abc_inner.j2": "{{ a }}{{ b }}{{ c }}"}}),
    ("include_block_sees_caller", "{% for y in [7, 8] %}{% include 'block_y.j2' %}{% endfor %}",
     {"templates": {**T, "block_y.j2": "{% set z = y * 2 %}{% block a %}[{{ y }}{{ z }}]{% endblock %}"}}),
    ("include_updates_caller_dict", "{% set d = dict(a=1) %}{% include 'updates.j2' %}{{ d }}",
     {"templates": {**T, "updates.j2": "{{ d.update(dict(z=3)) }}"}}),
    ("block_updates_caller_dict", "{% set d = dict(a=1) %}{% block b %}{{ d.update(dict(z=3)) }}{% endblock %}{{ d }}", L),
    ("include_in_macro", "{% macro m(v) %}{% include 'uses_v.j2' %}{% endmacro %}{{ m(4) }}{{ m(5) }}",
     {"templates": {**T, "uses_v.j2": "<{{ v }}>"}}),
    # More scopes than a context keeps in place (8, docs/tasks/0129): names set at every
    # depth, seen from the template and from an include, and a shadowing name left at each level
    ("include_sees_deep_scopes",
     "{% set a = 1 %}{% for b in [2] %}{% for c in [3] %}{% with d = 4 %}{% for e in [5] %}{% with f = 6 %}"
     "{% for g in [7] %}{% for h in [8] %}{% with i = 9 %}{% for j in [0] %}{% set a = 7 %}{% include 'deep.j2' %}{{ a }}"
     "{% endfor %}{{ a }}{% endwith %}{% endfor %}{% endfor %}{% endwith %}{{ a }}{% endfor %}{% endwith %}{% endfor %}{% endfor %}{{ a }}",
     {"templates": {**T, "deep.j2": "{{ a }}{{ b }}{{ c }}{{ d }}{{ e }}{{ f }}{{ g }}{{ h }}{{ i }}{{ j }}|"}}),
    ("macro_in_deep_scopes",
     "{% macro m(v) %}{% for w in [v] %}{% with x = w %}{% for y in [x] %}{% for z in [y] %}{{ z }}{% endfor %}{% endfor %}{% endwith %}{% endfor %}{% endmacro %}"
     "{% for b in [1, 2] %}{% for c in [b] %}{% with d = c %}{% for e in [d] %}{% for f in [e] %}{% with g = f %}{% for h in [g] %}"
     "{{ m(h) }}{% endfor %}{% endwith %}{% endfor %}{% endfor %}{% endwith %}{% endfor %}{% endfor %}",
     {}),
    # An imported macro's own names hide the module's names, which hide the importer's
    # (docs/tasks/0038; 0117 P0)
    ("from_import_param_shadows_module_name", "{% from 'shadow.j2' import f %}{{ f(5) }}", SHADOW),
    ("import_param_shadows_module_name", "{% import 'shadow.j2' as m %}{{ m.f(5) }}", SHADOW),
    ("import_macro_locals_shadow_module_name", "{% from 'shadow.j2' import h, l, w, uc %}{{ h() }}{{ l() }}{{ w() }}{{ uc() }}", SHADOW),
    ("import_module_name_shadows_importer", "{% for g in [9] %}{% from 'shadow.j2' import f, k with context %}{{ f(5) }}{{ k() }}{% endfor %}", SHADOW),
    ("import_param_changed_in_place_shadows_module_name", "{% from 'shadow.j2' import dct %}{{ dct({'b': 2}) }}", SHADOW),
    # The module keeps the names it exports: its own macros still read them
    ("import_macro_calls_sibling", "{% import 'sib.j2' as m %}{{ m.a(5) }}", SIB),
    ("from_import_macro_calls_sibling_in_loop", "{% from 'sib.j2' import f %}{{ f() }}", SIB),
    ("import_macro_reads_module_string", "{% import 'sib.j2' as m %}{{ m.ps() }}", SIB),
    # `self` and the names that can hide it (docs/tasks/0139): a name the template sets wins,
    # the template's own `self` wins over the caller's, a macro sees its defining template's
    ("self_set_shadows", "{% block b %}B{% endblock %}{% set self = 1 %}{{ self }}", L),
    ("self_set_conditional", "{% if true %}{% set self = 1 %}{% endif %}{{ self }}", L),
    ("self_set_after_use", "{{ self.b() }}{% set self = 1 %}{% block b %}B{% endblock %}", L),
    ("self_set_in_block", "{% block b %}{% set self = 9 %}{{ self }}{% endblock %}|{{ self.b() }}", L),
    ("self_in_macro", "{% block b %}B{% endblock %}{% macro m() %}{{ self.b() }}{% endmacro %}{{ m() }}", L),
    ("self_macro_param", "{% block b %}B{% endblock %}{% macro m(self) %}{{ self }}{% endmacro %}{{ m(4) }}", L),
    ("self_in_block_before_definition", "{% block a %}{{ self.b() }}{% endblock %}{% block b %}B{% endblock %}", L),
    ("self_in_loop", "{% block b %}B{% endblock %}{% for i in [1, 2] %}{{ self.b() }}{% endfor %}", L),
    ("self_as_value", "{% block b %}B{% endblock %}{% set s = self %}{{ s.b() }}", L),
    ("self_subscript", "{% block b %}B{% endblock %}{{ self['b']() }}", L),
    ("self_missing_block", "{{ self.nope is defined }}|{{ self is defined }}", L),
    ("self_parent_calls_child_block", "{% extends 'self_base.j2' %}{% block body %}C{% endblock %}",
     {"templates": {**T, "self_base.j2": "[{{ self.body() }}]{% block body %}B{% endblock %}"}}),
    ("self_child_set_hidden_in_parent", "{% extends 'self_set_child.j2' %}",
     {"templates": {**T, "self_base.j2": "[{{ self.body() }}]{% block body %}B{% endblock %}",
                    "self_set_child.j2": "{% extends 'self_base.j2' %}{% set self = 7 %}"}}),
    ("self_include_own_blocks", "{% block b %}B{% endblock %}{% include 'self_inc.j2' %}{{ self.b() }}",
     {"templates": {**T, "self_inc.j2": "{% block ib %}IB{% endblock %}<{{ self.ib() }}>"}}),
    ("self_include_not_caller_blocks", "{% block body %}X{% endblock %}{% include 'self_inc.j2' %}",
     {"templates": {**T, "self_inc.j2": "<{{ self.body is defined }}>"}}),
    ("self_include_after_set", "{% set self = 1 %}{% include 'self_inc.j2' %}",
     {"templates": {**T, "self_inc.j2": "{% block ib %}IB{% endblock %}<{{ self.ib() }}>"}}),
    ("self_imported_macro", "{% import 'self_lib.j2' as l %}{{ l.m() }}",
     {"templates": {**T, "self_lib.j2": "{% macro m() %}{{ self.lb() }}{% endmacro %}{% block lb %}LB{% endblock %}"}}),
    ("self_from_imported_macro", "{% from 'self_lib.j2' import m %}{{ m() }}",
     {"templates": {**T, "self_lib.j2": "{% macro m() %}{{ self.lb() }}{% endmacro %}{% block lb %}LB{% endblock %}"}}),
    ("self_passed_to_imported_macro", "{% import 'self_show.j2' as l %}{% block b %}B{% endblock %}{{ l.show(self) }}",
     {"templates": {**T, "self_show.j2": "{% macro show(s) %}{{ s.b() }}{% endmacro %}{% block b %}LIB{% endblock %}"}}),
    ("self_alias_passed_to_from_imported_macro", "{% from 'self_show.j2' import show %}{% block b %}B{% endblock %}{% set s = self %}{{ show(s) }}",
     {"templates": {**T, "self_show.j2": "{% macro show(s) %}{{ s.b() }}{% endmacro %}"}}),
    ("self_passed_to_imported_macro_in_child", "{% extends 'self_base.j2' %}{% import 'self_show.j2' as l %}{% block body %}C{% endblock %}{% block extra %}{{ l.show(self) }}{% endblock %}",
     {"templates": {**T, "self_base.j2": "[{{ self.body() }}]{% block body %}B{% endblock %}<{% block extra %}{% endblock %}>",
                    "self_show.j2": "{% macro show(s) %}{{ s.body() }}{% endmacro %}"}}),
    # A macro of an imported module calls another one of the module (crashed: the names were moved out)
    ("import_module_macro_calls_sibling", "{% import 'sib.j2' as l %}{{ l.outer() }}",
     {"templates": {**T, "sib.j2": "{% macro inner() %}x{% endmacro %}{% macro outer() %}{{ inner() }}{% endmacro %}"}}),
    ("from_import_module_macro_calls_sibling", "{% from 'sib.j2' import outer %}{{ outer() }}",
     {"templates": {**T, "sib.j2": "{% macro inner() %}x{% endmacro %}{% macro outer() %}{{ inner() }}{% endmacro %}"}}),
    # Left for docs/tasks/0143: a block's `self` is the template even after a top-level
    # `set self`, and `self` prints as Jinja2's TemplateReference
    ("self_block_ignores_top_level_set", "{% set self = 1 %}{% block b %}{{ self is number }}{% endblock %}", L),
    ("self_printed", "{% block b %}{% endblock %}[{{ self }}]", L),
    ("self_imported_macro_importer_block", "{% block mb %}MB{% endblock %}{% import 'self_lib.j2' as l %}[{{ l.n() }}]",
     {"templates": {**T, "self_lib.j2": "{% macro n() %}{{ self.mb is defined }}{% endmacro %}"}}),
]
