"""Python methods called on str, list and dict values (no sandbox in Jinja2)."""
CONTEXT = {"s": "Hello World", "l": [3, 1, 2], "d": {"a": 1, "b": 2}, "csv": "a,b,,c", "pad": "  x  "}
CASES = [
    ("str_upper", "{{ s.upper() }}"),
    ("str_lower", "{{ s.lower() }}"),
    ("str_title", "{{ 'ab cd'.title() }}"),
    ("str_capitalize", "{{ 'abc'.capitalize() }}"),
    ("str_strip", "[{{ pad.strip() }}]"),
    ("str_lstrip_chars", "{{ 'xxaxx'.lstrip('x') }}"),
    ("str_rstrip", "[{{ pad.rstrip() }}]"),
    ("str_split", "{{ s.split(' ') }}"),
    ("str_split_default", "{{ ' a  b '.split() }}"),
    ("str_split_maxsplit", "{{ csv.split(',', 1) }}"),
    ("str_rsplit", "{{ csv.rsplit(',', 1) }}"),
    ("str_join", "{{ '-'.join(['a', 'b']) }}"),
    ("str_replace", "{{ s.replace('l', 'L') }}"),
    ("str_replace_count", "{{ s.replace('l', 'L', 1) }}"),
    ("str_startswith", "{{ s.startswith('He') }}"),
    ("str_endswith", "{{ s.endswith('ld') }}"),
    ("str_find", "{{ s.find('o') }}"),
    ("str_count", "{{ s.count('l') }}"),
    ("str_format", "{{ '{}-{}'.format(1, 2) }}"),
    ("str_format_named", "{{ '{a}!'.format(a=5) }}"),
    ("str_isdigit", "{{ '123'.isdigit() }}"),
    ("str_zfill", "{{ '7'.zfill(3) }}"),
    ("str_center", "[{{ 'a'.center(5, '*') }}]"),
    ("str_partition", "{{ 'a=b'.partition('=') }}"),
    ("str_percent_format", "{{ '%s=%d' % ('a', 3) }}"),
    ("str_percent_single", "{{ '%05.1f' % 3.14159 }}"),
    ("list_index", "{{ l.index(1) }}"),
    ("list_count", "{{ [1, 1, 2].count(1) }}"),
    ("list_append_do", "{% do l.append(4) %}{{ l }}", {"env": {"extensions": ["do"]}}),
    ("list_append_expr", "{{ l.append(4) }}{{ l }}"),
    ("list_pop", "{{ l.pop() }}{{ l }}"),
    ("dict_items", "{{ d.items() | list }}"),
    ("dict_keys", "{{ d.keys() | list }}"),
    ("dict_values", "{{ d.values() | list }}"),
    ("dict_get", "{{ d.get('a') }}|{{ d.get('z', 'dflt') }}|{{ d.get('z') }}"),
    ("dict_update_do", "{% do d.update({'c': 3}) %}{{ d|length }}", {"env": {"extensions": ["do"]}}),
    ("dict_items_loop", "{% for k, v in d.items() %}{{ k }}={{ v }};{% endfor %}"),
    ("dict_setdefault", "{{ d.setdefault('z', 9) }}"),
    ("int_method", "{{ (255).bit_length() }}"),
    ("float_is_integer", "{{ (2.0).is_integer() }}"),
    ("unknown_method", "{{ s.no_such_method() }}"),
    # More str methods
    ("str_rfind", "{{ s.rfind('o') }}|{{ s.find('o', 5) }}|{{ s.find('zz') }}"),
    ("str_index_missing", "{{ s.index('zz') }}"),
    ("str_swapcase", "{{ s.swapcase() }}"),
    ("str_ljust_rjust", "[{{ 'ab'.ljust(4, '.') }}|{{ 'ab'.rjust(4) }}]"),
    ("str_splitlines", "{{ 'a\nb\r\nc'.splitlines() }}"),
    ("str_startswith_tuple", "{{ s.startswith(('x', 'He')) }}|{{ s.endswith('World', 0, 5) }}"),
    ("str_is_checks", "{{ 'abc'.isalpha() }}{{ '  '.isspace() }}{{ 'AB'.isupper() }}{{ 'ab1'.islower() }}{{ ''.isdigit() }}"),
    ("str_rpartition", "{{ 'a.b.c'.rpartition('.') }}|{{ 'abc'.partition('x') }}"),
    ("str_removeprefix", "{{ s.removeprefix('Hello ') }}|{{ s.removesuffix('World') }}"),
    ("str_split_none_maxsplit", "{{ ' a b  c '.split(None, 1) }}|{{ ' a b  c '.rsplit(None, 1) }}"),
    ("str_replace_empty", "{{ 'ab'.replace('', '-') }}"),
    ("str_strip_unicode", "[{{ 'été'.strip('é') }}|{{ 'héllo'.find('l') }}]"),
    ("str_format_spec", "{{ '{:>6.2f}|{:,}|{!r}|{:^5}|{:+d}|{:08.3f}|{:x}'.format(3.14159, 1234567, 'x', 'ab', 5, -2.5, 255) }}"),
    ("str_format_index", "{{ '{0[1]} {1[a]} {0}'.format([1, 2], {'a': 'z'}) }}"),
    ("str_join_non_str", "{{ ','.join([1, 2]) }}"),
    ("str_method_on_loop_item", "{% for w in s.split() %}{{ w.lower() }};{% endfor %}"),
    # Methods as values
    ("method_is_defined", "{{ 'T' if s.upper is defined else 'F' }}{{ 'T' if s['upper'] is defined else 'F' }}{{ 'T' if s.nope is defined else 'F' }}"),
    ("method_bound_call", "{% set f = s.lower %}{{ f() }}"),
    ("unknown_method_list", "{{ l.no_such_method() }}"),
    # list and tuple
    ("tuple_methods", "{{ (1, 2, 1).count(1) }}|{{ (1, 2).index(2) }}"),
    ("list_index_missing", "{{ l.index(9) }}"),
    ("list_mutators", "{% set x = [1, 2, 3] %}{% do x.insert(0, 0) %}{% do x.remove(2) %}{% do x.extend([7, 8]) %}{% do x.reverse() %}{{ x }}|{{ x.pop(0) }}|{{ x }}", {"env": {"extensions": ["do"]}}),
    ("list_clear_copy", "{% set x = [1, 2] %}{% set y = x.copy() %}{% do x.clear() %}{{ x }}{{ y }}", {"env": {"extensions": ["do"]}}),
    ("list_pop_empty", "{{ [].pop() }}"),
    ("list_extend_self", "{% set x = [1, 2] %}{% do x.extend(x) %}{{ x }}", {"env": {"extensions": ["do"]}}),
    ("list_pop_chain", "{{ l.pop().bit_length() }}{{ l }}"),
    # Reference semantics: lists and dicts are shared, as in Python
    ("list_accumulate", "{% set x = [] %}{% for i in range(3) %}{% do x.append(i) %}{% endfor %}{{ x }}", {"env": {"extensions": ["do"]}}),
    ("list_alias", "{% set a = [1] %}{% set b = a %}{% do b.append(2) %}{{ a }}", {"env": {"extensions": ["do"]}}),
    ("list_append_in_with", "{% set x = [] %}{% with %}{% do x.append(1) %}{% endwith %}{{ x }}", {"env": {"extensions": ["do"]}}),
    ("list_append_in_macro", "{% macro add(acc) %}{% do acc.append(1) %}{% endmacro %}{% set x = [] %}{{ add(x) }}{{ x }}", {"env": {"extensions": ["do"]}}),
    ("list_pop_in_loop", "{% set x = [3, 1, 2] %}{% for i in x %}{% do x.pop() %}{{ i }}{% endfor %}", {"env": {"extensions": ["do"]}}),
    ("list_filter_copies", "{% set y = l|list %}{% do y.append(9) %}{{ l }}", {"env": {"extensions": ["do"]}}),
    ("nested_append", "{% do nd['k'].append(2) %}{% do nd.k.append(3) %}{{ nd['k'] }}", {"env": {"extensions": ["do"]}, "ctx": {"nd": {"k": [1]}}}),
    ("context_alias", "{% set y = l %}{% do y.append(9) %}{{ l }}", {"env": {"extensions": ["do"]}}),
    # dict
    ("dict_literal_methods", "{% set x = {'a': 1, 'b': 2} %}{{ x.keys()|list }}{{ x.values()|list }}{{ x.items()|list }}{{ x.get('b') }}"),
    ("dict_mutators", "{% set x = {'a': 1, 'b': 2} %}{{ x.pop('a') }}|{{ x.pop('z', 0) }}|{% do x.update(c=3) %}{{ x }}|{{ x.popitem() }}|{{ x }}", {"env": {"extensions": ["do"]}}),
    ("dict_copy_clear", "{% set x = {'a': 1} %}{% set y = x.copy() %}{% do x.clear() %}{{ x }}{{ y }}", {"env": {"extensions": ["do"]}}),
    ("dict_update_pairs", "{% set x = {} %}{% do x.update([('a', 1)]) %}{{ x }}", {"env": {"extensions": ["do"]}}),
    ("dict_pop_missing", "{{ {}.pop('z') }}"),
    ("dict_setdefault_shared", "{% set x = {} %}{% do x.setdefault('k', []).append(1) %}{{ x }}", {"env": {"extensions": ["do"]}}),
    ("dict_method_before_key", "{{ dd.items is defined }}|{{ dd['items'] }}|{{ dd.items()|list }}", {"ctx": {"dd": {"items": "own"}}}),
    ("macro_default_fresh", "{% macro m(x, acc=[]) %}{% do acc.append(x) %}{{ acc }}{% endmacro %}{{ m(1) }}{{ m(2) }}", {"env": {"extensions": ["do"]}}),
    ("str_join_chars", "{{ '-'.join('abc') }}|{{ ','.join({'a': 1}) }}"),
    ("str_find_empty", "{{ ''.find('') }}|{{ 'abc'.find('', 3) }}|{{ 'abc'.rfind('') }}"),
    ("str_huge_width", "{{ 'x'.center(100000000000) }}"),
    ("str_format_huge_width", "{{ '{:99999999999999999999}'.format(1) }}"),
    ("loop_cycle_no_args", "{% for x in [1, 2] %}{{ loop.cycle() }}{% endfor %}"),
    ("loop_attr_not_dict_method", "{% for i in [1] %}{{ loop.items is defined }}{% endfor %}"),
]
