"""Python methods called on str, list and dict values (no sandbox in Jinja2)."""
CONTEXT = {"s": "Hello World", "l": [3, 1, 2], "d": {"a": 1, "b": 2}, "csv": "a,b,,c", "pad": "  x  "}
CASES = [
    ("str_upper", "{{ s.upper() }}"),
    ("str_lower", "{{ s.lower() }}"),
    ("str_title", "{{ 'ab cd'.title() }}"),
    ("str_capitalize", "{{ 'abc'.capitalize() }}"),
    ("str_strip", "[{{ pad.strip() }}]"),
    ("str_lstrip_chars", "{{ 'xxaxx'.lstrip('x') }}"),
    ("str_rstrip", "[{{ pad.rstrip() }}]"),
    ("str_split", "{{ s.split(' ') }}"),
    ("str_split_default", "{{ ' a  b '.split() }}"),
    ("str_split_maxsplit", "{{ csv.split(',', 1) }}"),
    ("str_rsplit", "{{ csv.rsplit(',', 1) }}"),
    ("str_join", "{{ '-'.join(['a', 'b']) }}"),
    ("str_replace", "{{ s.replace('l', 'L') }}"),
    ("str_replace_count", "{{ s.replace('l', 'L', 1) }}"),
    ("str_startswith", "{{ s.startswith('He') }}"),
    ("str_endswith", "{{ s.endswith('ld') }}"),
    ("str_find", "{{ s.find('o') }}"),
    ("str_count", "{{ s.count('l') }}"),
    ("str_format", "{{ '{}-{}'.format(1, 2) }}"),
    ("str_format_named", "{{ '{a}!'.format(a=5) }}"),
    ("str_isdigit", "{{ '123'.isdigit() }}"),
    ("str_zfill", "{{ '7'.zfill(3) }}"),
    ("str_center", "[{{ 'a'.center(5, '*') }}]"),
    ("str_partition", "{{ 'a=b'.partition('=') }}"),
    ("str_percent_format", "{{ '%s=%d' % ('a', 3) }}"),
    ("str_percent_single", "{{ '%05.1f' % 3.14159 }}"),
    ("list_index", "{{ l.index(1) }}"),
    ("list_count", "{{ [1, 1, 2].count(1) }}"),
    ("list_append_do", "{% do l.append(4) %}{{ l }}", {"env": {"extensions": ["do"]}}),
    ("list_append_expr", "{{ l.append(4) }}{{ l }}"),
    ("list_pop", "{{ l.pop() }}{{ l }}"),
    ("dict_items", "{{ d.items() | list }}"),
    ("dict_keys", "{{ d.keys() | list }}"),
    ("dict_values", "{{ d.values() | list }}"),
    ("dict_get", "{{ d.get('a') }}|{{ d.get('z', 'dflt') }}|{{ d.get('z') }}"),
    ("dict_update_do", "{% do d.update({'c': 3}) %}{{ d|length }}", {"env": {"extensions": ["do"]}}),
    ("dict_items_loop", "{% for k, v in d.items() %}{{ k }}={{ v }};{% endfor %}"),
    ("dict_setdefault", "{{ d.setdefault('z', 9) }}"),
    ("int_method", "{{ (255).bit_length() }}"),
    ("float_is_integer", "{{ (2.0).is_integer() }}"),
    ("unknown_method", "{{ s.no_such_method() }}"),
]
