"""Arithmetic, comparison, logic, membership and concatenation operators.
Boolean results print as T/F so that bool repr (output.py) does not mask them."""
CONTEXT = {"x": 3, "y": 2.5, "l": [3, 1, 2], "s": "Hello", "d": {"a": 1}, "n": None, "z": 0}
CASES = [
    ("add", "{{ 1 + 2 }}"),
    ("sub", "{{ 1 - 5 }}"),
    ("mul", "{{ 3 * 4 }}"),
    ("div", "{{ 10 / 4 }}"),
    ("div_exact", "{{ 10 / 5 }}"),
    ("floordiv", "{{ 10 // 4 }}"),
    ("floordiv_negative", "{{ -7 // 2 }}"),
    ("floordiv_float", "{{ 7.5 // 2 }}"),
    ("mod", "{{ 10 % 3 }}"),
    ("mod_negative", "{{ -7 % 3 }}"),
    ("mod_float", "{{ 7.5 % 2 }}"),
    ("pow", "{{ 2 ** 10 }}"),
    ("pow_right_assoc", "{{ 2 ** 3 ** 2 }}"),
    ("pow_negative_exponent", "{{ 2 ** -1 }}"),
    ("pow_float", "{{ 4 ** 0.5 }}"),
    ("precedence", "{{ 1 + 2 * 3 - 4 }}"),
    ("precedence_parens", "{{ (1 + 2) * 3 }}"),
    ("unary_minus_pow", "{{ -2 ** 2 }}"),
    ("unary_plus", "{{ +x }}"),
    ("unary_minus_var", "{{ -x }}"),
    ("int_float_add", "{{ x + y }}"),
    ("div_by_zero", "{{ 1 / 0 }}"),
    ("floordiv_by_zero", "{{ 1 // 0 }}"),
    ("mod_by_zero", "{{ 1 % 0 }}"),
    ("string_plus", "{{ 'a' + 'b' }}"),
    ("string_plus_int", "{{ 'a' + 1 }}"),
    ("string_times", "{{ 'ab' * 3 }}"),
    ("int_times_string", "{{ 3 * 'ab' }}"),
    ("list_plus", "{{ [1] + [2] }}"),
    ("list_times", "{{ [1, 2] * 2 }}"),
    ("tilde", "{{ 'a' ~ 1 ~ 2.5 }}"),
    ("tilde_none", "{{ 'a' ~ none }}"),
    ("eq", "{{ 'T' if 1 == 1 else 'F' }}|{{ 'T' if 1 == 2 else 'F' }}"),
    ("eq_int_float", "{{ 'T' if 1 == 1.0 else 'F' }}"),
    ("eq_dict_order_insensitive", "{{ 'T' if {'a': 1, 'b': 2} == {'b': 2, 'a': 1} else 'F' }}"),
    ("eq_string_int", "{{ 'T' if '1' == 1 else 'F' }}"),
    ("eq_list", "{{ 'T' if [1, 2] == [1, 2] else 'F' }}"),
    ("eq_dict", "{{ {'a': 1} == {'a': 1} }}"),
    ("eq_none", "{{ 'T' if n == none else 'F' }}"),
    ("ne", "{{ 'T' if 1 != 2 else 'F' }}"),
    ("lt_gt", "{{ 'T' if 1 < 2 else 'F' }}{{ 'T' if 2 > 1 else 'F' }}{{ 'T' if 2 <= 2 else 'F' }}{{ 'T' if 3 >= 4 else 'F' }}"),
    ("compare_strings", "{{ 'T' if 'a' < 'b' else 'F' }}"),
    ("compare_lists", "{{ 'T' if [1, 2] < [1, 3] else 'F' }}"),
    ("compare_mixed_types", "{{ 'T' if 1 < 'a' else 'F' }}"),
    ("chained_compare", "{{ 'T' if 1 < 2 < 3 else 'F' }}"),
    ("chained_compare_false", "{{ 'T' if 1 < 3 < 2 else 'F' }}"),
    ("chained_eq", "{{ 'T' if 1 == 1 == 1 else 'F' }}"),
    ("in_list", "{{ 'T' if 2 in l else 'F' }}"),
    ("in_string", "{{ 'T' if 'ell' in s else 'F' }}"),
    ("in_dict", "{{ 'T' if 'a' in d else 'F' }}"),
    ("not_in", "{{ 'T' if 5 not in l else 'F' }}"),
    ("not_in_string", "{{ 'T' if 'z' not in s else 'F' }}"),
    ("and_value", "{{ x and 'yes' }}"),
    ("and_falsy_value", "{{ z and 'yes' }}"),
    ("or_value", "{{ z or 'fallback' }}"),
    ("or_truthy_value", "{{ x or 'fallback' }}"),
    ("and_or_idiom", "{{ x and 'yes' or 'no' }}"),
    ("or_empty_list", "{{ [] or 'empty' }}"),
    ("not", "{{ 'T' if not x else 'F' }}|{{ 'T' if not z else 'F' }}"),
    ("not_precedence", "{{ 'T' if not 1 == 2 else 'F' }}"),
    ("and_short_circuit", "{{ 'T' if false and undefined_fn() else 'F' }}"),
    ("or_short_circuit", "{{ 'T' if true or undefined_fn() else 'F' }}"),
    ("ternary", "{{ 'a' if x > 2 else 'b' }}"),
    ("ternary_no_else", "{{ 'a' if x > 5 }}"),
    ("ternary_nested", "{{ 'a' if x > 5 else 'b' if x > 2 else 'c' }}"),
    ("truthiness_empty_string", "{% if '' %}t{% else %}f{% endif %}"),
    ("truthiness_zero_float", "{% if 0.0 %}t{% else %}f{% endif %}"),
    ("truthiness_empty_dict", "{% if {} %}t{% else %}f{% endif %}"),
    ("truthiness_none", "{% if n %}t{% else %}f{% endif %}"),
    ("int_overflow_mul", "{{ 9223372036854775807 * 2 }}"),
    ("int_big_pow", "{{ 2 ** 100 }}"),
    ("int_plus_bool", "{{ 1 + true }}"),
    ("pow_precedence_over_add", "{{ 2 + 3 ** 2 }}"),
    ("pow_left_assoc", "{{ 2 ** 3 ** 2 }}"),
    ("pow_binds_tighter_than_minus", "{{ -2 ** 2 }}"),
    ("concat_precedence", "{{ 1 ~ 2 * 3 }}|{{ 'a' ~ 'b' == 'ab' }}"),
    ("not_before_filter", "{{ 'T' if not l|length else 'F' }}"),
    ("unary_minus_before_filter", "{{ -3|abs }}"),
    ("chained_compare_not_in", "{{ 'T' if 1 < 2 not in [3] else 'F' }}"),
    ("chained_in", "{{ 'b' in 'abc' in ['True'] }}"),
    ("test_then_and", "{{ x is eq 3 and true }}"),
    ("test_then_filter", "{{ x is odd|tojson }}"),
    ("test_arg_is_not_if", "{{ x is defined if 1 else 2 }}"),
    ("implicit_tuple", "{{ 1, 2 }}"),
    # Python numeric tower and type rules (task 0015)
    ("floordiv_float_negative", "{{ -7.5 // 2 }}|{{ 7.5 // -2 }}|{{ -7.5 % 2 }}|{{ 7.5 % -2 }}"),
    ("mod_negative_divisor", "{{ 7 % -2 }}|{{ -7 % -2 }}"),
    ("float_floordiv_by_zero", "{{ 1.5 // 0 }}"),
    ("float_mod_by_zero", "{{ 1.5 % 0.0 }}"),
    ("pow_zero_negative_exponent", "{{ 0 ** -1 }}"),
    ("int_max_no_overflow", "{{ 9223372036854775806 + 1 }}|{{ -9223372036854775807 - 1 }}|{{ 2 ** 62 }}"),
    ("bool_arithmetic", "{{ true + true }}|{{ -true }}|{{ true * 3 }}|{{ 'ab' * true }}"),
    ("float_equality_exact", "{{ 'T' if 0.1 + 0.2 == 0.3 else 'F' }}|{{ 'T' if 1 == 1.0 else 'F' }}"),
    ("int_float_compare_exact", "{{ 'T' if 9007199254740993 == 9007199254740992.0 else 'F' }}|{{ 'T' if 9007199254740993 > 9007199254740992.0 else 'F' }}"),
    ("ne_mixed_types", "{{ 'T' if x != 'a' else 'F' }}|{{ 'T' if x == 'a' else 'F' }}|{{ 'T' if n != 0 else 'F' }}"),
    ("compare_none_raises", "{{ 'T' if n < 1 else 'F' }}"),
    ("unary_minus_string_raises", "{{ -s }}"),
    ("list_tuple_not_equal", "{{ 'T' if [1, 2] == (1, 2) else 'F' }}|{{ 'T' if (1, 2) == (1, 2) else 'F' }}"),
    ("list_plus_tuple_raises", "{{ [1] + (2,) }}"),
    ("list_times_negative", "{% for i in l * -1 %}{{ i }}{% endfor %}|{% for i in 2 * l %}{{ i }}{% endfor %}"),
    ("compare_lists_prefix", "{{ 'T' if [1, 2] < [1, 2, 0] else 'F' }}|{{ 'T' if [2] > [1, 9] else 'F' }}"),
    ("ne_dict", "{{ 'T' if {'a': 1} != {'a': 2} else 'F' }}|{{ 'T' if d == {'a': 1} else 'F' }}"),
    ("dict_lt_raises", "{{ 'T' if {} < {} else 'F' }}"),
    ("not_on_containers", "{{ 'T' if not l else 'F' }}|{{ 'T' if not [] else 'F' }}|{{ 'T' if not d else 'F' }}"),
    ("truthiness_float", "{% if y %}t{% else %}f{% endif %}|{% if 1e-20 %}t{% else %}f{% endif %}|{{ 'T' if not 0.0 else 'F' }}"),
    ("and_or_short_circuit_value", "{{ z and undefined_fn() }}|{{ x or undefined_fn() }}"),
    ("in_dict_missing_key", "{{ 'T' if 'b' in d else 'F' }}|{{ 'T' if 'b' not in d else 'F' }}"),
]
