"""Environment options beyond whitespace and autoescape: delimiters, line statements, extensions."""
CONTEXT = {"x": 3, "l": [1, 2]}
CASES = [
    ("custom_variable_delimiters", "<<= x >>", {"env": {"variable_start_string": "<<=", "variable_end_string": ">>"}}),
    ("custom_block_delimiters", "<% if true %>y<% endif %>", {"env": {"block_start_string": "<%", "block_end_string": "%>"}}),
    ("custom_comment_delimiters", "a<# c #>b", {"env": {"comment_start_string": "<#", "comment_end_string": "#>"}}),
    ("latex_style", r"\VAR{x}\BLOCK{if true}y\BLOCK{endif}",
     {"env": {"block_start_string": r"\BLOCK{", "block_end_string": "}",
              "variable_start_string": r"\VAR{", "variable_end_string": "}"}}),
    ("line_statement", "# for i in l\n{{ i }}\n# endfor\n", {"env": {"line_statement_prefix": "#"}}),
    ("line_comment", "a ## comment\nb", {"env": {"line_comment_prefix": "##"}}),
    ("i18n_trans", "{% trans %}Hello {{ x }}{% endtrans %}", {"env": {"extensions": ["i18n"]}}),
    ("i18n_trans_vars", "{% trans n=x %}{{ n }} item{% pluralize %}{{ n }} items{% endtrans %}", {"env": {"extensions": ["i18n"]}}),
    ("i18n_gettext", "{{ _('Hello') }}|{{ gettext('Hi %(n)s', n=1) }}", {"env": {"extensions": ["i18n"]}}),
    ("loopcontrols_without_extension", "{% for i in l %}{% break %}{% endfor %}"),
    # How tags are split from the text, with default and custom delimiters (task 0028)
    ("stray_end_delimiters", "a }} b %} c #} d"),
    ("hash_text_without_line_statements", "# not a statement"),
    ("comment_ignores_begin_inside", "{# {# #}x"),
    ("expr_closing_braces_of_dict", "{{ {'a': 1}}}"),
    ("expr_end_delimiter_in_strings", "{{ '}}' ~ \"%}\" ~ 'a\\'}}' }}"),
    ("expr_extra_closing_brace", "{{ x }}}"),
    ("stmt_nested_dict_before_end", "{% set d = {'a': {'b': 1}}%}{{ d.a.b }}"),
    ("raw_without_spaces", "{%raw%}{{ x }}{%endraw%}"),
    ("asp_style_shared_prefix", "<%= x %><% if true %>y<% endif %>",
     {"env": {"block_start_string": "<%", "block_end_string": "%>",
              "variable_start_string": "<%=", "variable_end_string": "%>"}}),
    ("latex_style_braces_in_expression", r"\VAR{ {'a': 1}['a'] }|a } b",
     {"env": {"variable_start_string": r"\VAR{", "variable_end_string": "}"}}),
    ("custom_delimiters_raw", "{% raw %}{{ x }}{% endraw %}<% raw %>{{ y }}<% endraw %>",
     {"env": {"block_start_string": "<%", "block_end_string": "%>"}}),
    ("custom_delimiters_default_ones_are_text", "{{ x }} {# c #} {% if 1 %}y{% endif %}",
     {"env": {"block_start_string": "<%", "block_end_string": "%>"}}),
    ("custom_delimiters_whitespace_control", "a\n  <% if true %>\nb\n<%- endif -%>\n c",
     {"env": {"block_start_string": "<%", "block_end_string": "%>", "lstrip_blocks": True, "trim_blocks": True}}),
    ("line_statement_eats_blank_lines", "# for i in l\n\n{{ i }}\n# endfor\n", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_indented", "  # for i in l\n  {{ i }}\n  # endfor\nend", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_open_brackets", "# for i in [1,\n 2]\n{{ i }}\n# endfor\n", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_else_trailing_space", "# if false   \nyes\n# else\nno\n# endif", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_minus", "a\n#- if true\nyes\n# endif", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_set_at_end", "# set y = 1\n{{ y }}", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_unclosed_bracket", "# for i in [1,\n", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_empty", "#", {"env": {"line_statement_prefix": "#"}}),
    ("line_statement_and_comment", "## c\n# for i in l\n{{ i }}## c2\n# endfor\n",
     {"env": {"line_statement_prefix": "#", "line_comment_prefix": "##"}}),
    ("line_comment_minus", "a\n  ##- c\nb", {"env": {"line_comment_prefix": "##"}}),
    ("line_comment_after_text", "x## c\n{% if true %}a ## c\n{% endif %}", {"env": {"line_comment_prefix": "##"}}),
    ("line_comment_in_raw_and_comment", "{% raw %}a ## c\n{% endraw %}{# a ## c #}b", {"env": {"line_comment_prefix": "##"}}),
]
