"""How values are converted to text when printed ({{ value }})."""
CONTEXT = {"n": None, "t": True, "f": False, "i": 7, "fl": 2.5, "fw": 3.0, "s": "text",
           "l": [3, 1, 2], "e": [], "d": {"a": 1, "b": 2}, "nested": {"k": [1, {"x": None}]},
           "strs": ["a", "b'c", 'd"e'], "u": "héllo"}
CASES = [
    ("none_var", "{{ n }}"),
    ("true_var", "{{ t }}"),
    ("false_var", "{{ f }}"),
    ("int_var", "{{ i }}"),
    ("float_var", "{{ fl }}"),
    ("float_whole_var", "{{ fw }}"),
    ("string_var", "{{ s }}"),
    ("unicode_var", "{{ u }}"),
    ("list_var", "{{ l }}"),
    ("list_empty_var", "{{ e }}"),
    ("dict_var", "{{ d }}"),
    ("nested_var", "{{ nested }}"),
    ("list_of_strings_repr", "{{ strs }}"),
    ("bool_expr", "{{ 1 == 1 }}"),
    ("none_in_concat", "{{ 'a' ~ n }}"),
    ("bool_in_concat", "{{ 'a' ~ t }}"),
    ("list_in_concat", "{{ 'a' ~ l }}"),
    ("float_in_concat", "{{ 'a' ~ fw }}"),
    ("string_filter_list", "{{ l|string }}"),
    ("string_filter_none", "{{ n|string }}"),
    ("string_filter_bool", "{{ t|string }}"),
    ("float_division_whole", "{{ 4 / 2 }}"),
    ("float_repr_third", "{{ 1 / 3 }}"),
    ("int_times_float", "{{ 2 * 1.5 }}"),
    ("range_object", "{{ range(3) }}"),
    ("float_exponent_large", "{{ 10.0 ** 16 }}|{{ 10.0 ** 15 }}"),
    ("float_exponent_small", "{{ 1 / 10000000 }}|{{ 1 / 10000 }}"),
    ("float_inf", "{{ 1e308 * 10 }}|{{ -1e308 * 10 }}"),
    ("strings_repr_escapes", "{{ v }}", {"ctx": {"v": ["a\nb\tc", "back\\slash", "it's \"q\"", "\x01"]}}),
    ("nested_scalars_repr", "{{ v }}", {"ctx": {"v": {"k": [1.0, True, None, "s"]}}}),
    ("dictsort_items_repr", "{{ d|dictsort }}"),
    ("varargs_single_tuple", "{% macro m() %}{{ varargs }}{% endmacro %}{{ m(1) }}|{{ m() }}"),
    ("text_passthrough", "plain {text} % # text"),
    ("empty_template", ""),
]
