"""Strings as sequences of characters (code points, so UTF-8 text counts like Python str), and wordwrap."""
CONTEXT = {"s": "hello", "u": "héllo wörld", "e": "", "cab": "cabca",
           "text": "A long-winded sentence about well-known hyphen-separated words",
           "para": "first paragraph is here\n\nsecond one\r\nthird"}
CASES = [
    ("utf8_length", "{{ u|length }}"),
    ("utf8_index", "{{ u[1] }}{{ u[-4] }}"),
    ("utf8_reverse", "{{ u|reverse }}"),
    ("utf8_first_last", "{{ u|first }}{{ u|last }}"),
    ("utf8_for", "{% for c in u %}{{ c }}.{% endfor %}"),
    ("index_out_of_range", "[{{ s[5] }}][{{ s[-6] }}]"),
    ("empty_string", "[{{ e|length }}][{{ e|reverse }}][{{ e|first }}]"),
    ("join_string", "{{ s|join('-') }}"),
    ("list_string", "{{ s|list|join(',') }}"),
    ("sort_string", "{{ cab|sort|join }}|{{ cab|sort(reverse=true)|join }}"),
    ("unique_string", "{{ cab|unique|join }}"),
    ("min_max_string", "{{ cab|min }}{{ cab|max }}"),
    ("map_string", "{{ s|map('upper')|join }}"),
    ("select_string", "{{ s|reject('eq', 'l')|join }}"),
    ("batch_string", "{% for b in s|batch(2) %}{{ b|join }};{% endfor %}"),
    ("slice_string", "{% for b in s|slice(2) %}{{ b|join }};{% endfor %}"),
    ("in_string_loop", "{% for c in s %}{{ loop.index }}{{ c }}{% if loop.last %}!{% endif %}{% endfor %}"),
    ("wordwrap_hyphens", "{{ text|wordwrap(12) }}"),
    ("wordwrap_no_hyphens", "{{ text|wordwrap(12, break_on_hyphens=false) }}"),
    ("wordwrap_long_words", "{{ 'abcdefghijkl mn'|wordwrap(5) }}|{{ 'abcdefghijkl mn'|wordwrap(5, false) }}"),
    ("wordwrap_wrapstring", "{{ text|wordwrap(20, wrapstring='<br>') }}"),
    ("wordwrap_paragraphs", "{{ para|wordwrap(10) }}"),
    ("wordwrap_utf8", "{{ u|wordwrap(5) }}"),
    ("wordwrap_whitespace", "[{{ '  lead   and   trail  '|wordwrap(6) }}]"),
]
