"""Control structures: for, if, set, with, macro, call, filter blocks, raw, do, loop controls."""
CONTEXT = {"l": [3, 1, 2], "e": [], "d": {"a": 1, "b": 2}, "x": 3,
           "tree": [{"n": "a", "c": [{"n": "b", "c": []}, {"n": "c", "c": [{"n": "d", "c": []}]}]}]}
LC = {"env": {"extensions": ["loopcontrols"]}}
DO = {"env": {"extensions": ["do"]}}
CASES = [
    # for
    ("for", "{% for i in l %}{{ i }}{% endfor %}"),
    ("for_else", "{% for i in e %}x{% else %}empty{% endfor %}"),
    ("for_else_not_taken", "{% for i in l %}{{ i }}{% else %}empty{% endfor %}"),
    ("for_filter", "{% for i in l if i > 1 %}{{ i }}{% endfor %}"),
    ("for_filter_loop_index", "{% for i in l if i > 1 %}{{ loop.index }}/{{ loop.length }};{% endfor %}"),
    ("for_filter_else", "{% for i in l if i > 10 %}{{ i }}{% else %}none{% endfor %}"),
    ("for_unpack", "{% for a, b in [(1, 2), (3, 4)] %}{{ a + b }};{% endfor %}"),
    ("for_unpack_parens", "{% for (a, b) in [[1, 2]] %}{{ a }}{{ b }}{% endfor %}"),
    ("for_unpack_string", "{% for a, b in ['xy'] %}{{ a }}-{{ b }}{% endfor %}"),
    ("for_dict_keys", "{% for k in d %}{{ k }}{% endfor %}"),
    ("for_dict_literal_order", "{% for k in {'b': 1, 'a': 2, 'C': 3} %}{{ k }}{% endfor %}"),
    ("for_dict_duplicate_key", "{% set m = {'b': 1, 'a': 2, 'b': 3} %}{% for k in m %}{{ k }}={{ m[k] }},{% endfor %}"),
    ("for_string", "{% for c in 'abc' %}{{ c }}.{% endfor %}"),
    ("for_range", "{% for i in range(3) %}{{ i }}{% endfor %}"),
    ("for_nested", "{% for i in [1, 2] %}{% for j in [1, 2] %}{{ i }}{{ j }} {% endfor %}{% endfor %}"),
    ("for_outer_loop", "{% for i in [1, 2] %}{% set outer = loop %}{% for j in [1, 2] %}{{ outer.index }}{{ loop.index }} {% endfor %}{% endfor %}"),
    ("loop_index", "{% for i in l %}{{ loop.index }}{{ loop.index0 }},{% endfor %}"),
    ("loop_revindex", "{% for i in l %}{{ loop.revindex }}{{ loop.revindex0 }},{% endfor %}"),
    ("loop_first_last", "{% for i in l %}{% if loop.first %}F{% endif %}{% if loop.last %}L{% endif %}{{ i }}{% endfor %}"),
    ("loop_first_print", "{% for i in l %}{{ loop.first }},{% endfor %}"),
    ("loop_length", "{% for i in l %}{{ loop.length }}{% endfor %}"),
    ("loop_cycle", "{% for i in l %}{{ loop.cycle('a', 'b') }}{% endfor %}"),
    ("loop_previtem_nextitem", "{% for i in l %}[{{ loop.previtem }}|{{ loop.nextitem }}]{% endfor %}"),
    ("loop_changed", "{% for i in [1, 1, 2] %}{% if loop.changed(i) %}{{ i }}{% endif %}{% endfor %}"),
    ("loop_depth", "{% for i in [1] %}{{ loop.depth }}{{ loop.depth0 }}{% endfor %}"),
    # loop.<attribute> is resolved at Load (0117 P1); `loop` bound to something else takes the generic path
    ("loop_attr_arithmetic", "{% for i in l %}{{ loop.length + loop.index }}{{ loop.last }}{{ loop.revindex0 }},{% endfor %}"),
    ("loop_attr_chain", "{% for i in l %}{{ loop.index.foo }}|{% endfor %}"),
    ("loop_attr_unknown", "{% for i in l %}{{ loop.nope }}|{% endfor %}"),
    ("loop_bracket_attr", "{% for i in l %}{{ loop['index'] }}{{ loop['revindex'] }},{% endfor %}"),
    ("loop_cycle_nested", "{% for i in [1, 2] %}{% for j in [1, 2, 3] %}{{ loop.cycle('a', 'b') }}{% endfor %}|{{ loop.cycle('x', 'y') }}{% endfor %}"),
    ("loop_attr_on_passed_loop", "{% macro m(loop) %}{{ loop.index }}{{ loop.cycle('a', 'b') }}{% endmacro %}{% for i in l %}{{ m(loop) }}{% endfor %}"),
    ("loop_attr_on_dict_param", "{% macro m(loop) %}{{ loop.index }}{% endmacro %}{{ m({'index': 9}) }}"),
    ("loop_attr_on_set_dict", "{% set loop = {'index': 7} %}{{ loop.index }}"),
    ("loop_cycle_without_items", "{% for i in l %}{{ loop.cycle() }}{% endfor %}"),
    ("loop_recursive", "{% for item in tree recursive %}{{ item.n }}{% if item.c %}({{ loop(item.c) }}){% endif %}{% endfor %}"),
    ("loop_recursive_depth", "{% for item in tree recursive %}{{ item.n }}{{ loop.depth }} {{ loop(item.c) }}{% endfor %}"),
    ("loop_var_scope", "{% set i = 'outer' %}{% for i in l %}{% endfor %}{{ i }}"),
    ("loop_set_scope", "{% set c = 0 %}{% for i in l %}{% set c = c + i %}{% endfor %}{{ c }}"),
    ("loop_undefined_outside", "{% for i in l %}{% endfor %}[{{ loop }}]"),
    ("break", "{% for i in l %}{% if i == 1 %}{% break %}{% endif %}{{ i }}{% endfor %}", LC),
    ("continue", "{% for i in l %}{% if i == 1 %}{% continue %}{% endif %}{{ i }}{% endfor %}", LC),
    ("break_nested", "{% for i in [1, 2] %}{% for j in [1, 2] %}{{ i }}{{ j }}{% break %}{% endfor %};{% endfor %}", LC),
    ("break_else", "{% for i in l %}{{ i }}{% if i == 1 %}{% break %}{% endif %}{% else %}E{% endfor %}", LC),
    ("continue_else", "{% for i in l %}{{ i }}{% continue %}{% else %}E{% endfor %}", LC),
    ("break_filtered", "{% for i in l if i > 1 %}{{ i }}{% break %}{% endfor %}", LC),
    ("break_recursive", "{% for item in tree recursive %}{{ item.n }}{{ loop(item.c) }}{% break %}{% endfor %}", LC),
    ("continue_in_with", "{% for i in l %}{% with %}{% if i == 1 %}{% continue %}{% endif %}{{ i }}{% endwith %}{% endfor %}", LC),
    ("break_in_filter_block", "{% for i in l %}{% filter upper %}a{% if i == 1 %}{% break %}{% endif %}{% endfilter %}{% endfor %}", LC),
    ("break_in_set_block", "{% for i in l %}{% set x %}a{{ i }}{% if i == 1 %}{% break %}{% endif %}{% endset %}{{ x }}{% endfor %}", LC),
    ("break_outside_loop", "{% if l %}{% break %}{% endif %}", LC),
    ("break_in_for_else", "{% for i in e %}{% else %}{% break %}{% endfor %}", LC),
    ("break_in_macro", "{% for i in l %}{% macro m() %}{% break %}{% endmacro %}{% endfor %}", LC),
    ("break_in_call_block", "{% macro m() %}{{ caller() }}{% endmacro %}{% for i in l %}{% call m() %}{% break %}{% endcall %}{% endfor %}", LC),
    ("break_without_extension", "{% for i in l %}{% break %}{% endfor %}"),
    ("break_as_name", "{% set break = 1 %}{{ break }}", LC),
    ("loop_revindex_filtered", "{% for i in l if i > 1 %}{{ loop.revindex }}{{ loop.revindex0 }},{% endfor %}"),
    ("loop_length_filtered_single", "{% for i in l if i == 2 %}{{ loop.length }}{{ loop.revindex }}{% endfor %}"),
    ("loop_changed_args", "{% for i in [1, 2, 3, 4] %}{{ 'T' if loop.changed(i // 2, 'x') else 'F' }}{% endfor %}"),
    ("loop_changed_no_args", "{% for i in l %}{{ 'T' if loop.changed() else 'F' }}{% endfor %}"),
    ("loop_depth_nested", "{% for i in [1] %}{{ loop.depth }}{% for j in [1] %}{{ loop.depth }}{% endfor %}{% endfor %}"),
    # if
    ("if_elif_else", "{% if x > 5 %}a{% elif x > 2 %}b{% else %}c{% endif %}"),
    ("if_multiple_elif", "{% if x == 1 %}1{% elif x == 2 %}2{% elif x == 3 %}3{% endif %}"),
    ("if_inline_test", "{% if x is odd and x > 1 %}y{% endif %}"),
    # set
    ("set", "{% set a = 5 %}{{ a }}"),
    ("set_multiple", "{% set a, b = 1, 2 %}{{ a }}{{ b }}"),
    ("set_unpack_list", "{% set a, b = [1, 2] %}{{ b }}"),
    ("set_unpack_string", "{% set a, b = 'xy' %}{{ a }}-{{ b }}"),
    ("set_block_unpack", "{% set a, b %}xy{% endset %}{{ a }}-{{ b }}"),
    ("set_block", "{% set blk %}inner {{ x }}{% endset %}[{{ blk }}]"),
    ("set_block_filter", "{% set blk | upper %}inner{% endset %}{{ blk }}"),
    ("set_overrides_context", "{% set x = 10 %}{{ x }}"),
    ("namespace", "{% set ns = namespace(c=0) %}{% for i in l %}{% set ns.c = ns.c + i %}{% endfor %}{{ ns.c }}"),
    ("namespace_attr", "{% set ns = namespace() %}{% set ns.a = 1 %}{{ ns.a }}"),
    ("namespace_from_dict", "{% set ns = namespace(d) %}{{ ns.b }}"),
    ("namespace_in_with", "{% set ns = namespace(a=1) %}{% with %}{% set ns.a = 2 %}{% endwith %}{{ ns.a }}"),
    ("namespace_in_macro", "{% set ns = namespace(a=1) %}{% macro m() %}{% set ns.a = ns.a + 1 %}{% endmacro %}{{ m() }}{{ m() }}{{ ns.a }}"),
    ("namespace_set_block", "{% set ns = namespace() %}{% set ns.a %}x{{ x }}{% endset %}{{ ns.a }}"),
    ("namespace_subscript", "{% set ns = namespace({'a': 1}, b=2) %}{{ ns['a'] }}{{ ns.b }}"),
    ("namespace_missing_attr", "{% set ns = namespace() %}[{{ ns.a }}]"),
    ("namespace_set_on_dict", "{% set m = {} %}{% set m.a = 1 %}"),
    ("namespace_set_on_undefined", "{% set nope.a = 1 %}"),
    ("namespace_keeps_loop", "{% set ns = namespace() %}{% for i in l %}{% set ns.x = loop %}{% endfor %}{{ ns.x.index }}{{ ns.x.length }}{{ ns.x.revindex }}{{ 'T' if ns.x.last else 'F' }}"),
    ("namespace_keeps_filtered_loop", "{% set ns = namespace() %}{% for i in l if i > 1 %}{% set ns.x = loop %}{% endfor %}{{ ns.x.index }}{{ ns.x.length }}{{ ns.x.revindex0 }}"),
    ("namespace_keeps_broken_loop", "{% set ns = namespace() %}{% for i in l if i > 0 %}{% set ns.x = loop %}{% break %}{% endfor %}{{ ns.x.index }}{{ ns.x.length }}{{ ns.x.revindex }}", LC),
    ("namespace_keeps_loop_items", "{% set ns = namespace() %}{% for i in [1, 2, 3] %}{% set ns.x = loop %}{% if loop.index == 2 %}{% break %}{% endif %}{% endfor %}{{ ns.x.previtem }}{{ ns.x.nextitem }}{{ 'T' if ns.x.first else 'F' }}", LC),
    ("loop_prev_next_defined", "{% for i in [1, 2, 3] %}{{ 'T' if loop.previtem is defined else 'F' }}{{ 'T' if loop.nextitem is defined else 'F' }} {% endfor %}"),
    ("loop_previtem_unpacked", "{% for a, b in [(1, 2), (3, 4)] %}{{ loop.previtem }}{{ a }}{{ b }}|{% endfor %}"),
    ("for_body_set_per_iteration", "{% for i in [1, 2, 3] %}{% if loop.first %}{% set a = 'x' %}{% endif %}[{{ a }}]{% endfor %}"),
    ("for_filter_ignores_body_set", "{% set y = 1 %}{% for i in [1, 2, 3] if i > y %}{% set y = 5 %}{{ i }}{% endfor %}"),
    ("for_else_sees_outer_loop", "{% for x in [1, 2] %}{% for y in [] %}{% else %}{{ loop.index }}{{ loop.depth }}|{% endfor %}{% endfor %}"),
    ("for_else_has_no_loop", "{% for y in [] %}{% else %}{{ 'T' if loop is defined else 'F' }}{% endfor %}"),
    ("for_filter_loop_length", "{% for x in [1, 2, 3] if loop.length > 1 %}{{ x }}{% endfor %}"),
    ("for_filter_uses_loop", "{% for x in [1, 2, 3] if loop.index > 1 %}{{ x }}{% endfor %}"),
    ("for_filter_sees_body_namespace", "{% set ns = namespace(stop=false) %}{% for x in [1, 2, 3] if not ns.stop %}{{ x }}{% set ns.stop = true %}{% endfor %}"),
    ("for_filter_peek_last_after_body_write", "{% set ns = namespace(n=0) %}{% for x in [1, 2, 3] if ns.n < 2 %}{% set ns.n = ns.n + 1 %}{{ x }}{{ loop.last }}{% endfor %}"),
    ("for_filter_peek_from_macro", "{% macro m(l) %}[{{ l.length }}{{ l.last }}{{ l.revindex }}]{% endmacro %}{% for x in range(7) if x > 2 %}{{ x }}{{ m(loop) }}{% endfor %}"),
    ("for_filter_peek_ignores_body_set", "{% set o = 1 %}{% for x in range(1, 9) if x > o %}{% set o = 5 %}{{ x }}{{ loop.last }}{{ loop.nextitem }}{% endfor %}"),
    ("for_filter_peek_ignores_body_set_in_macro", "{% macro m(l) %}[{{ l.length }}]{% endmacro %}{% for x in range(1, 9) if y is not defined %}{% set y = 1 %}{{ x }}{{ m(loop) }}{% endfor %}"),
    ("for_filter_loop_vars", "{% for x in range(10) if x is odd %}{{ x }}:{{ loop.index }}/{{ loop.length }} {{ loop.revindex0 }} {{ loop.last }} {{ loop.nextitem }} {{ loop.previtem }};{% endfor %}"),
    ("for_over_none", "{% for x in none %}{{ x }}{% else %}empty{% endfor %}"),
    ("loop_recursive_no_args", "{% for x in [1] recursive %}{{ x }}{{ loop() }}{% endfor %}"),
    ("loop_recursive_filtered", "{% for x in tree if x.n recursive %}{{ x.n }}{{ loop(x.c) }}{% endfor %}"),
    ("for_else_keeps_outer_name", "{% set i = 'outer' %}{% for i in [] %}{% else %}{{ i }}{% endfor %}"),
    ("namespace_keeps_loop_changed", "{% set ns = namespace() %}{% for i in l %}{% set ns.x = loop %}{% endfor %}{{ 'T' if ns.x.changed(1) else 'F' }}{{ 'T' if ns.x.changed(1) else 'F' }}"),
    ("namespace_in_tuple_target", "{% set ns = namespace() %}{% set ns.a, b = 1, 2 %}{{ ns.a }}{{ b }}"),
    ("namespace_in_for_target", "{% set ns = namespace() %}{% for ns.a in [1] %}{% endfor %}"),
    ("namespace_print", "{% set ns = namespace(a=1) %}{{ ns }}"),
    ("namespace_is_mapping", "{% set ns = namespace(a=1) %}{{ 'T' if ns is mapping else 'F' }}"),
    ("namespace_iterate", "{% set ns = namespace(a=1) %}{% for k in ns %}{{ k }}{% endfor %}"),
    ("namespace_no_dict_methods", "{% set ns = namespace(a=1) %}{{ ns.get('a') }}"),
    ("set_nested_target", "{% set (a, b), c = [[1, 2], 3] %}{{ a }}{{ b }}{{ c }}"),
    # with
    ("with", "{% with a = 1 %}{{ a }}{% endwith %}[{{ a }}]"),
    ("with_multiple", "{% with a = 1, b = 2 %}{{ a + b }}{% endwith %}"),
    ("with_set_inside", "{% with %}{% set a = 1 %}{{ a }}{% endwith %}[{{ a }}]"),
    # macro
    ("macro", "{% macro m(a, b=2) %}{{ a }}-{{ b }}{% endmacro %}{{ m(1) }} {{ m(1, b=3) }} {{ m(b=4, a=5) }}"),
    ("macro_missing_arg", "{% macro m(a) %}[{{ a }}]{% endmacro %}{{ m() }}"),
    ("macro_varargs", "{% macro m() %}{% for i in varargs %}{{ i }},{% endfor %}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_kwargs", "{% macro m() %}{{ kwargs.k }}{% endmacro %}{{ m(k=3) }}"),
    ("macro_varargs_print", "{% macro m() %}{{ varargs }}{{ kwargs }}{% endmacro %}{{ m(1, 2, k=3) }}"),
    ("macro_too_many_args", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_unknown_kwarg", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, z=2) }}"),
    ("macro_default_refers_arg", "{% macro m(a, b=a) %}{{ b }}{% endmacro %}{{ m(5) }}"),
    ("macro_name", "{% macro m(a, b) %}{% endmacro %}{{ m.name }}|{{ m.arguments|join(',') }}"),
    ("macro_catch_flags", "{% macro m(a) %}{{ varargs }}{% endmacro %}{% for f in [m.catch_varargs, m.catch_kwargs, m.caller] %}{{ 'T' if f else 'F' }}{% endfor %}"),
    ("macro_kwarg_fills_later_arg", "{% macro m(a, b=1, c=2) %}{{ a }}{{ b }}{{ c }}{% endmacro %}{{ m(0, c=5) }}"),
    ("macro_kwarg_repeats_positional", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, a=2) }}"),
    ("macro_extra_kwarg_caught", "{% macro m(a) %}{{ a }}{% for k in kwargs %}{{ k }}{% endfor %}{% endmacro %}{{ m(1, z=2) }}"),
    ("macro_kwargs_order", "{% macro m() %}{% for k in kwargs %}{{ k }}{% endfor %}{% endmacro %}{{ m(z=1, a=2, m=3) }}"),
    ("macro_missing_arg_shadows", "{% macro m(x) %}[{{ x }}]{% endmacro %}{{ m() }}"),
    ("macro_default_lexical", "{% set g = 'top' %}{% macro m(a=g) %}{{ a }}{% endmacro %}{% macro o(g) %}{{ m() }}{% endmacro %}{{ o('inner') }}"),
    ("macro_default_sees_kwargs", "{% macro m(a=kwargs) %}{{ a.x }}:{{ kwargs.x }}{% endmacro %}{{ m(x=7) }}"),
    ("macro_assigned_varargs_not_caught", "{% macro m() %}{% set varargs = ['local'] %}{% for v in varargs %}{{ v }}{% endfor %}{% endmacro %}{{ 'T' if m.catch_varargs else 'F' }}|{{ m() }}"),
    ("macro_assigned_varargs_rejects_extra", "{% macro m() %}{% set varargs = [1] %}{{ varargs|length }}{% endmacro %}{{ m(1) }}"),
    ("macro_varargs_read_before_set", "{% macro m() %}{% for v in varargs %}{{ v }}{% endfor %}{% set varargs = [] %}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_for_target_kwargs", "{% macro m() %}{% for kwargs in [1] %}{{ kwargs }}{% endfor %}{% endmacro %}{{ 'T' if m.catch_kwargs else 'F' }}"),
    ("macro_with_kwarg_label", "{% macro f(kwargs) %}{% endmacro %}{% macro m() %}{% with x = f(kwargs=1) %}{{ kwargs.z }}{% endwith %}{% endmacro %}{{ m(z=7) }}"),
    ("macro_inner_param_varargs", "{% macro m() %}{% macro n(varargs) %}{{ varargs }}{% endmacro %}{{ n(3) }}{% endmacro %}{{ 'T' if m.catch_varargs else 'F' }}{{ m() }}"),
    ("macro_param_named_varargs", "{% macro m(varargs) %}{{ varargs }}{% endmacro %}{{ m(7) }}"),
    ("macro_default_later_arg", "{% macro m(a, b=a~x, x=7) %}{{ b }}|{{ x }}{% endmacro %}{{ m(5) }}"),
    ("macro_body_name_not_bound", "{% macro m() %}[{{ name }}{{ arguments }}]{% endmacro %}{{ m() }}"),
    ("macro_returns_markup", "{% macro m() %}<b>{% endmacro %}{{ m() }}"),
    ("macro_context_access", "{% macro m() %}{{ x }}{% endmacro %}{{ m() }}"),
    ("macro_recursive", "{% macro f(n) %}{{ n }}{% if n > 0 %}{{ f(n - 1) }}{% endif %}{% endmacro %}{{ f(3) }}"),
    ("macro_result_filtered", "{% macro m(v) %}<{{ v }}>{% endmacro %}{{ m('a')|upper }}"),
    ("caller", "{% macro m() %}[{{ caller() }}]{% endmacro %}{% call m() %}body{% endcall %}"),
    ("caller_args", "{% macro m() %}{% for i in [1, 2] %}{{ caller(i) }}{% endfor %}{% endmacro %}{% call(v) m() %}<{{ v }}>{% endcall %}"),
    ("caller_defined", "{% macro m() %}{{ caller is defined }}{% endmacro %}{{ m() }}"),
    ("caller_in_default", "{% macro m(a=caller) %}{{ a() }}{{ caller() }}{% endmacro %}{% call m() %}C{% endcall %}"),
    ("caller_explicit_with_default", "{% macro m(caller='no') %}{{ caller if caller is string else caller() }}{% endmacro %}{{ m() }}|{% call m() %}C{% endcall %}"),
    ("caller_truthy", "{% macro m() %}{{ 'T' if caller else 'F' }}{% if caller %}{{ caller() }}{% endif %}{% endmacro %}{% call m() %}C{% endcall %}|{{ 'T' if m else 'F' }}"),
    ("macro_default_reassigned_global", "{% set y = 1 %}{% macro m(a=y) %}{{ a }}{% endmacro %}{% set y = 2 %}{{ m() }}"),
    ("macro_body_lexical_scope", "{% set g = 'top' %}{% macro m() %}{{ g }}{% endmacro %}{% macro o(g) %}{{ m() }}{% endmacro %}{{ o('inner') }}"),
    ("caller_not_used", "{% macro m() %}x{% endmacro %}{% call m() %}y{% endcall %}"),
    ("caller_too_many_args", "{% macro m() %}{{ caller(1, 2) }}{% endmacro %}{% call(a) m() %}{{ a }}{% endcall %}"),
    ("caller_attributes", "{% macro m() %}{{ caller.arguments|join(',') }}:{{ caller(1) }}{% endmacro %}{% call(a, b=a) m() %}{{ a }}{{ b }}{% endcall %}"),
    ("caller_not_inherited", "{% macro n() %}{{ 'T' if caller is defined else 'F' }}{% endmacro %}{% macro m() %}{{ caller() }}{{ n() }}{% endmacro %}{% call m() %}y{% endcall %}"),
    # filter / raw / do / misc
    ("filter_block", "{% filter upper %}abc {{ x }}{% endfilter %}"),
    ("filter_block_chain", "{% filter upper|replace('B', 'x') %}abc{% endfilter %}"),
    ("filter_block_args", "{% filter center(7) %}abc{% endfilter %}"),
    ("raw", "{% raw %}{{ x }}{% if %}{% endraw %}"),
    ("comment", "a{# comment {{ x }} #}b"),
    ("comment_multiline", "a{# line1\nline2 #}b"),
    ("comment_begin_at_end", "a{#"),
    ("comment_begin_dash_at_end", "a{#-"),
    ("comment_begin_plus_at_end", "a{#+"),
    ("do", "{% do l.append(4) %}{% for i in l %}{{ i }},{% endfor %}", DO),
    ("do_without_extension", "{% do l.append(4) %}"),
    ("autoescape_block", "{% autoescape true %}{{ '<a>' }}{% endautoescape %}|{{ '<a>' }}"),
    ("autoescape_block_off", "{% autoescape false %}{{ '<a>' }}{% endautoescape %}"),
    ("unknown_tag", "{% frobnicate %}"),
    ("for_implicit_tuple", "{% for x in 1, 2 %}{{ x }}{% endfor %}"),
    ("for_unpack_filter", "{% for a, b in [[1, 2]] if a %}{{ a }}{{ b }}{% endfor %}"),
    ("for_nested_target", "{% for (a, b), c in [[[1, 2], 3]] %}{{ a }}{{ b }}{{ c }}{% endfor %}"),
    ("for_nested_target_inner", "{% for a, (b, c) in [[1, [2, 3]]] %}{{ a }}{{ b }}{{ c }}{% endfor %}"),
    ("for_nested_target_mismatch", "{% for (a, b), c in [[[1, 2, 4], 3]] %}{{ a }}{% endfor %}"),
    ("for_trailing_comma_target", "{% for a, in [[1], [2]] %}{{ a }}{% endfor %}"),
    ("for_empty_tuple_target", "{% for () in [[]] %}x{% endfor %}"),
    ("for_loop_target", "{% for loop in l %}{{ loop }}{% endfor %}"),
    ("for_nested_loop_target", "{% for a, (loop, b) in [[1, [2, 3]]] %}{% endfor %}"),
    ("set_trailing_comma_target", "{% set a, = [1] %}{{ a }}"),
    ("loop_changed_kwargs", "{% for i in [1, 2] %}{{ loop.changed(a=i) }}{% endfor %}"),
    ("for_paren_single_tuple", "{% for (a,) in [[1]] %}{{ a }}{% endfor %}"),
    ("if_tuple", "{% if l, s %}y{% endif %}"),
    # loop.cycle is a value of its own, not an integer every call of 2 is mistaken for
    ("call_int_is_not_loop_cycle", "{% set f = 2 %}{{ f('a', 'b') }}"),
    ("call_int_with_int_loop", "{% set loop = 1 %}{% set f = 2 %}{{ f('a') }}"),
    ("loop_cycle_as_value", "{% for x in [1, 2] %}{% set c = loop.cycle %}{{ c('a', 'b') }}{% endfor %}"),
    # Loop names in slots (0117 P1): each pins what the Load-time resolver must keep
    ('for_target_shadowed_by_body_set', '{% for x in [1,2] %}{{ x }}{% set x = x * 10 %}{{ x }}{% endfor %}'),
    ('for_nested_same_target', "{% for x in 'ab' %}{{ x }}{% for x in [1,2] %}{{ x }}{% endfor %}{% endfor %}"),
    ('for_filter_reads_outer_target', '{% for o in [1,2] %}{% for x in [1,2,3] if x != o %}{{ o }}{{ x }}{% endfor %}{% endfor %}'),
    ('loop_length_filtered_from_macro', '{% macro m(l) %}{{ l.length }}{% endmacro %}{% for x in [1,2,3] if x > 1 %}{{ m(loop) }}{% endfor %}'),
    ('recursive_loop_else_reads_outer', "{% set o = 'O' %}{% for x in [[1, []]] recursive %}<{{ o }}{% if x is iterable %}{{ loop(x) }}{% else %}{% for y in [] %}{% else %}E{{ o }}{% endfor %}{% endif %}>{% endfor %}"),
    ('recursive_loop_via_macro_reads_outer', "{% set o = 'O' %}{% macro m(l, v) %}{{ l(v) }}{% endmacro %}{% for x in [[1]] recursive %}{% if x is iterable %}{{ o }}{{ m(loop, x) }}{% else %}{{ o }}{% endif %}{% endfor %}"),
    ('recursive_loop_called_after_loop', '{% for x in [1, 5] recursive %}{% set ns = namespace() %}[{{ x }}]{% endfor %}'),
    ('with_target_set_in_body', '{% for x in [1] %}{% with y = x %}{% set y = y + 1 %}{{ x }}{{ y }}{% endwith %}{% endfor %}'),
    ('with_targets_see_outer', '{% set a = 5 %}{% with a = a + 1, b = a %}{{ a }}{{ b }}{% endwith %}'),
    ('macro_param_set_in_body', '{% macro m(a) %}{% set a = a + 1 %}{{ a }}{% endmacro %}{% for x in [0] %}{{ m(x) }}{{ m(1) }}{% endfor %}'),
    ('call_param_shadows_loop_target', '{% macro m() %}{{ caller(1) }}{% endmacro %}{% for x in [9] %}{% call(x) m() %}{{ x }}{% endcall %}{% endfor %}'),
    ('call_body_reads_loop_target', '{% macro m() %}{{ caller() }}{% endmacro %}{% for x in [1,2] %}{% call m() %}{{ x }}{% endcall %}{% endfor %}'),
    ('set_block_in_loop_reads_target', '{% for x in [1,2] %}{% set b %}{{ x }}{% endset %}{{ b }}{% endfor %}'),
    ('filter_block_in_loop', "{% for x in ['a'] %}{% filter upper %}{{ x }}{% endfilter %}{% endfor %}"),
    ('tuple_target_partly_shadowed', '{% for a, b in [(1, 2)] %}{% set b = 4 %}{{ a }}{{ b + 1 }}{% endfor %}'),
    ('loop_target_namespace_attr', '{% set ns = namespace(x=0) %}{% for x in [1,2] %}{% set ns.x = x %}{% endfor %}{{ ns.x }}'),
    ('macro_param_vs_caller_loop_var', '{% macro m(x) %}{{ x }}{% endmacro %}{% for x in [1] %}{{ m(3) }}{{ x }}{% endfor %}'),
    ('macro_param_inside_with', '{% macro m(a) %}{% with b = a %}{{ b }}{% endwith %}{% endmacro %}{% for x in [2] %}{{ m(x) }}{% endfor %}'),
    ('set_in_if_inside_loop', '{% for x in [1,2] %}[{% if x == 2 %}{% set y = x %}{{ y }}{% endif %}]{% endfor %}'),
    ('macro_reads_caller_loop_target', '{% macro m() %}{{ x }}{% endmacro %}{% for x in [1,2] %}{{ m() }}{% endfor %}'),
    ('macro_reads_caller_loop', '{% macro m() %}{{ loop.index }}{% endmacro %}{% for x in [1,2] %}{{ m() }}{% endfor %}'),
    ('loop_filter_target_from_macro_param', '{% macro m(x) %}{% for y in [1,2,3,4] if y > x %}{{ x }}{% endfor %}{% endmacro %}{{ m(0) }}'),
    ('recursive_loop_reads_outer_target', "{% for o in ['O'] %}{% for x in [[1]] recursive %}{{ o }}{% if x is iterable %}{{ loop(x) }}{% endif %}{% endfor %}{% endfor %}"),
    ('with_target_shadows_loop_target', '{% for x in [1] %}{% with x = 2 %}{{ x }}{% endwith %}{{ x }}{% endfor %}'),
    ('with_body_reads_loop_target', '{% for x in [1] %}{% with y = 2 %}{{ x }}{{ y }}{% endwith %}{% endfor %}'),
    ('with_body_set_shadows_loop_target', '{% for x in [1] %}{% with %}{% set x = 3 %}{{ x }}{% endwith %}{{ x }}{% endfor %}'),
    ('call_args_read_loop_target', '{% macro m(a) %}{{ a }}{{ caller() }}{% endmacro %}{% for x in [1,2] %}{% call m(x) %}-{% endcall %}{% endfor %}'),
    ('for_else_reads_outer_target', '{% for o in [1] %}{% for x in [] %}{% else %}{{ o }}{% endfor %}{% endfor %}'),
    ('macro_def_in_loop_shadows_target', '{% for x in [1] %}{% macro x() %}M{% endmacro %}{{ x() }}{% endfor %}'),
    ('loop_in_macro_called_in_loop', '{% macro m() %}{% for y in [1,2] %}{{ y }}{% endfor %}{% endmacro %}{% for x in [7] %}{{ x }}{{ m() }}{{ x }}{% endfor %}'),
    ('loop_target_mutated_in_place', '{% for x in [[1]] %}{% set _ = x.append(2) %}{{ x }}{% endfor %}'),
    ('self_as_loop_target', '{% for self in [1,2] %}{{ self }}{% endfor %}'),
    ('sibling_loop_reuses_slot', '{% for x in [1] %}{% endfor %}{% for y in [2] %}{{ x }}{{ y }}{% endfor %}'),
    ('caller_loop_in_call_body', "{% macro m() %}{% for x in 'ab' %}{{ caller() }}{% endfor %}{% endmacro %}{% for x in [1,2] %}{% call m() %}{{ x }}{% endcall %}{% endfor %}"),
    ('set_loop_in_body', '{% for x in [1,2] %}{% set loop = 5 %}{{ loop }}{% endfor %}'),
    ('loop_update_in_place', "{% for x in [{'a': 1}] %}{% set _ = x.update(b=2) %}{{ x|dictsort }}{% endfor %}"),
    ('loop_filter_outer_name_from_macro', '{% macro m(x) %}{% for y in [1,2,3,4] if y > x %}{{ x }}{% endfor %}{% endmacro %}{% for x in [3] %}{{ m(0) }}{% endfor %}'),
    ('loop_in_filter_frame_macro_reads_target', '{% macro m() %}{{ y }}{% endmacro %}{% for y in [1,2] if m() %}{{ y }}{% endfor %}'),
]
