"""Control structures: for, if, set, with, macro, call, filter blocks, raw, do, loop controls."""
CONTEXT = {"l": [3, 1, 2], "e": [], "d": {"a": 1, "b": 2}, "x": 3,
           "tree": [{"n": "a", "c": [{"n": "b", "c": []}, {"n": "c", "c": [{"n": "d", "c": []}]}]}]}
LC = {"env": {"extensions": ["loopcontrols"]}}
DO = {"env": {"extensions": ["do"]}}
CASES = [
    # for
    ("for", "{% for i in l %}{{ i }}{% endfor %}"),
    ("for_else", "{% for i in e %}x{% else %}empty{% endfor %}"),
    ("for_else_not_taken", "{% for i in l %}{{ i }}{% else %}empty{% endfor %}"),
    ("for_filter", "{% for i in l if i > 1 %}{{ i }}{% endfor %}"),
    ("for_filter_loop_index", "{% for i in l if i > 1 %}{{ loop.index }}/{{ loop.length }};{% endfor %}"),
    ("for_filter_else", "{% for i in l if i > 10 %}{{ i }}{% else %}none{% endfor %}"),
    ("for_unpack", "{% for a, b in [(1, 2), (3, 4)] %}{{ a + b }};{% endfor %}"),
    ("for_unpack_parens", "{% for (a, b) in [[1, 2]] %}{{ a }}{{ b }}{% endfor %}"),
    ("for_dict_keys", "{% for k in d %}{{ k }}{% endfor %}"),
    ("for_string", "{% for c in 'abc' %}{{ c }}.{% endfor %}"),
    ("for_range", "{% for i in range(3) %}{{ i }}{% endfor %}"),
    ("for_nested", "{% for i in [1, 2] %}{% for j in [1, 2] %}{{ i }}{{ j }} {% endfor %}{% endfor %}"),
    ("for_outer_loop", "{% for i in [1, 2] %}{% set outer = loop %}{% for j in [1, 2] %}{{ outer.index }}{{ loop.index }} {% endfor %}{% endfor %}"),
    ("loop_index", "{% for i in l %}{{ loop.index }}{{ loop.index0 }},{% endfor %}"),
    ("loop_revindex", "{% for i in l %}{{ loop.revindex }}{{ loop.revindex0 }},{% endfor %}"),
    ("loop_first_last", "{% for i in l %}{% if loop.first %}F{% endif %}{% if loop.last %}L{% endif %}{{ i }}{% endfor %}"),
    ("loop_first_print", "{% for i in l %}{{ loop.first }},{% endfor %}"),
    ("loop_length", "{% for i in l %}{{ loop.length }}{% endfor %}"),
    ("loop_cycle", "{% for i in l %}{{ loop.cycle('a', 'b') }}{% endfor %}"),
    ("loop_previtem_nextitem", "{% for i in l %}[{{ loop.previtem }}|{{ loop.nextitem }}]{% endfor %}"),
    ("loop_changed", "{% for i in [1, 1, 2] %}{% if loop.changed(i) %}{{ i }}{% endif %}{% endfor %}"),
    ("loop_depth", "{% for i in [1] %}{{ loop.depth }}{{ loop.depth0 }}{% endfor %}"),
    ("loop_recursive", "{% for item in tree recursive %}{{ item.n }}{% if item.c %}({{ loop(item.c) }}){% endif %}{% endfor %}"),
    ("loop_recursive_depth", "{% for item in tree recursive %}{{ item.n }}{{ loop.depth }} {{ loop(item.c) }}{% endfor %}"),
    ("loop_var_scope", "{% set i = 'outer' %}{% for i in l %}{% endfor %}{{ i }}"),
    ("loop_set_scope", "{% set c = 0 %}{% for i in l %}{% set c = c + i %}{% endfor %}{{ c }}"),
    ("loop_undefined_outside", "{% for i in l %}{% endfor %}[{{ loop }}]"),
    ("break", "{% for i in l %}{% if i == 1 %}{% break %}{% endif %}{{ i }}{% endfor %}", LC),
    ("continue", "{% for i in l %}{% if i == 1 %}{% continue %}{% endif %}{{ i }}{% endfor %}", LC),
    # if
    ("if_elif_else", "{% if x > 5 %}a{% elif x > 2 %}b{% else %}c{% endif %}"),
    ("if_multiple_elif", "{% if x == 1 %}1{% elif x == 2 %}2{% elif x == 3 %}3{% endif %}"),
    ("if_inline_test", "{% if x is odd and x > 1 %}y{% endif %}"),
    # set
    ("set", "{% set a = 5 %}{{ a }}"),
    ("set_multiple", "{% set a, b = 1, 2 %}{{ a }}{{ b }}"),
    ("set_unpack_list", "{% set a, b = [1, 2] %}{{ b }}"),
    ("set_block", "{% set blk %}inner {{ x }}{% endset %}[{{ blk }}]"),
    ("set_block_filter", "{% set blk | upper %}inner{% endset %}{{ blk }}"),
    ("set_overrides_context", "{% set x = 10 %}{{ x }}"),
    ("namespace", "{% set ns = namespace(c=0) %}{% for i in l %}{% set ns.c = ns.c + i %}{% endfor %}{{ ns.c }}"),
    ("namespace_attr", "{% set ns = namespace() %}{% set ns.a = 1 %}{{ ns.a }}"),
    ("namespace_from_dict", "{% set ns = namespace(d) %}{{ ns.b }}"),
    # with
    ("with", "{% with a = 1 %}{{ a }}{% endwith %}[{{ a }}]"),
    ("with_multiple", "{% with a = 1, b = 2 %}{{ a + b }}{% endwith %}"),
    ("with_set_inside", "{% with %}{% set a = 1 %}{{ a }}{% endwith %}[{{ a }}]"),
    # macro
    ("macro", "{% macro m(a, b=2) %}{{ a }}-{{ b }}{% endmacro %}{{ m(1) }} {{ m(1, b=3) }} {{ m(b=4, a=5) }}"),
    ("macro_missing_arg", "{% macro m(a) %}[{{ a }}]{% endmacro %}{{ m() }}"),
    ("macro_varargs", "{% macro m() %}{% for i in varargs %}{{ i }},{% endfor %}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_kwargs", "{% macro m() %}{{ kwargs.k }}{% endmacro %}{{ m(k=3) }}"),
    ("macro_varargs_print", "{% macro m() %}{{ varargs }}{{ kwargs }}{% endmacro %}{{ m(1, 2, k=3) }}"),
    ("macro_too_many_args", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_unknown_kwarg", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, z=2) }}"),
    ("macro_default_refers_arg", "{% macro m(a, b=a) %}{{ b }}{% endmacro %}{{ m(5) }}"),
    ("macro_name", "{% macro m(a, b) %}{% endmacro %}{{ m.name }}|{{ m.arguments|join(',') }}"),
    ("macro_returns_markup", "{% macro m() %}<b>{% endmacro %}{{ m() }}"),
    ("macro_context_access", "{% macro m() %}{{ x }}{% endmacro %}{{ m() }}"),
    ("macro_recursive", "{% macro f(n) %}{{ n }}{% if n > 0 %}{{ f(n - 1) }}{% endif %}{% endmacro %}{{ f(3) }}"),
    ("macro_result_filtered", "{% macro m(v) %}<{{ v }}>{% endmacro %}{{ m('a')|upper }}"),
    ("caller", "{% macro m() %}[{{ caller() }}]{% endmacro %}{% call m() %}body{% endcall %}"),
    ("caller_args", "{% macro m() %}{% for i in [1, 2] %}{{ caller(i) }}{% endfor %}{% endmacro %}{% call(v) m() %}<{{ v }}>{% endcall %}"),
    ("caller_defined", "{% macro m() %}{{ caller is defined }}{% endmacro %}{{ m() }}"),
    # filter / raw / do / misc
    ("filter_block", "{% filter upper %}abc {{ x }}{% endfilter %}"),
    ("filter_block_chain", "{% filter upper|replace('B', 'x') %}abc{% endfilter %}"),
    ("filter_block_args", "{% filter center(7) %}abc{% endfilter %}"),
    ("raw", "{% raw %}{{ x }}{% if %}{% endraw %}"),
    ("comment", "a{# comment {{ x }} #}b"),
    ("comment_multiline", "a{# line1\nline2 #}b"),
    ("do", "{% do l.append(4) %}{% for i in l %}{{ i }},{% endfor %}", DO),
    ("do_without_extension", "{% do l.append(4) %}"),
    ("autoescape_block", "{% autoescape true %}{{ '<a>' }}{% endautoescape %}|{{ '<a>' }}"),
    ("autoescape_block_off", "{% autoescape false %}{{ '<a>' }}{% endautoescape %}"),
    ("unknown_tag", "{% frobnicate %}"),
]
