"""Control structures: for, if, set, with, macro, call, filter blocks, raw, do, loop controls."""
CONTEXT = {"l": [3, 1, 2], "e": [], "d": {"a": 1, "b": 2}, "x": 3,
           "tree": [{"n": "a", "c": [{"n": "b", "c": []}, {"n": "c", "c": [{"n": "d", "c": []}]}]}]}
LC = {"env": {"extensions": ["loopcontrols"]}}
DO = {"env": {"extensions": ["do"]}}
CASES = [
    # for
    ("for", "{% for i in l %}{{ i }}{% endfor %}"),
    ("for_else", "{% for i in e %}x{% else %}empty{% endfor %}"),
    ("for_else_not_taken", "{% for i in l %}{{ i }}{% else %}empty{% endfor %}"),
    ("for_filter", "{% for i in l if i > 1 %}{{ i }}{% endfor %}"),
    ("for_filter_loop_index", "{% for i in l if i > 1 %}{{ loop.index }}/{{ loop.length }};{% endfor %}"),
    ("for_filter_else", "{% for i in l if i > 10 %}{{ i }}{% else %}none{% endfor %}"),
    ("for_unpack", "{% for a, b in [(1, 2), (3, 4)] %}{{ a + b }};{% endfor %}"),
    ("for_unpack_parens", "{% for (a, b) in [[1, 2]] %}{{ a }}{{ b }}{% endfor %}"),
    ("for_unpack_string", "{% for a, b in ['xy'] %}{{ a }}-{{ b }}{% endfor %}"),
    ("for_dict_keys", "{% for k in d %}{{ k }}{% endfor %}"),
    ("for_dict_literal_order", "{% for k in {'b': 1, 'a': 2, 'C': 3} %}{{ k }}{% endfor %}"),
    ("for_dict_duplicate_key", "{% set m = {'b': 1, 'a': 2, 'b': 3} %}{% for k in m %}{{ k }}={{ m[k] }},{% endfor %}"),
    ("for_string", "{% for c in 'abc' %}{{ c }}.{% endfor %}"),
    ("for_range", "{% for i in range(3) %}{{ i }}{% endfor %}"),
    ("for_nested", "{% for i in [1, 2] %}{% for j in [1, 2] %}{{ i }}{{ j }} {% endfor %}{% endfor %}"),
    ("for_outer_loop", "{% for i in [1, 2] %}{% set outer = loop %}{% for j in [1, 2] %}{{ outer.index }}{{ loop.index }} {% endfor %}{% endfor %}"),
    ("loop_index", "{% for i in l %}{{ loop.index }}{{ loop.index0 }},{% endfor %}"),
    ("loop_revindex", "{% for i in l %}{{ loop.revindex }}{{ loop.revindex0 }},{% endfor %}"),
    ("loop_first_last", "{% for i in l %}{% if loop.first %}F{% endif %}{% if loop.last %}L{% endif %}{{ i }}{% endfor %}"),
    ("loop_first_print", "{% for i in l %}{{ loop.first }},{% endfor %}"),
    ("loop_length", "{% for i in l %}{{ loop.length }}{% endfor %}"),
    ("loop_cycle", "{% for i in l %}{{ loop.cycle('a', 'b') }}{% endfor %}"),
    ("loop_previtem_nextitem", "{% for i in l %}[{{ loop.previtem }}|{{ loop.nextitem }}]{% endfor %}"),
    ("loop_changed", "{% for i in [1, 1, 2] %}{% if loop.changed(i) %}{{ i }}{% endif %}{% endfor %}"),
    ("loop_depth", "{% for i in [1] %}{{ loop.depth }}{{ loop.depth0 }}{% endfor %}"),
    ("loop_recursive", "{% for item in tree recursive %}{{ item.n }}{% if item.c %}({{ loop(item.c) }}){% endif %}{% endfor %}"),
    ("loop_recursive_depth", "{% for item in tree recursive %}{{ item.n }}{{ loop.depth }} {{ loop(item.c) }}{% endfor %}"),
    ("loop_var_scope", "{% set i = 'outer' %}{% for i in l %}{% endfor %}{{ i }}"),
    ("loop_set_scope", "{% set c = 0 %}{% for i in l %}{% set c = c + i %}{% endfor %}{{ c }}"),
    ("loop_undefined_outside", "{% for i in l %}{% endfor %}[{{ loop }}]"),
    ("break", "{% for i in l %}{% if i == 1 %}{% break %}{% endif %}{{ i }}{% endfor %}", LC),
    ("continue", "{% for i in l %}{% if i == 1 %}{% continue %}{% endif %}{{ i }}{% endfor %}", LC),
    ("break_nested", "{% for i in [1, 2] %}{% for j in [1, 2] %}{{ i }}{{ j }}{% break %}{% endfor %};{% endfor %}", LC),
    ("break_else", "{% for i in l %}{{ i }}{% if i == 1 %}{% break %}{% endif %}{% else %}E{% endfor %}", LC),
    ("continue_else", "{% for i in l %}{{ i }}{% continue %}{% else %}E{% endfor %}", LC),
    ("break_filtered", "{% for i in l if i > 1 %}{{ i }}{% break %}{% endfor %}", LC),
    ("break_recursive", "{% for item in tree recursive %}{{ item.n }}{{ loop(item.c) }}{% break %}{% endfor %}", LC),
    ("continue_in_with", "{% for i in l %}{% with %}{% if i == 1 %}{% continue %}{% endif %}{{ i }}{% endwith %}{% endfor %}", LC),
    ("break_in_filter_block", "{% for i in l %}{% filter upper %}a{% if i == 1 %}{% break %}{% endif %}{% endfilter %}{% endfor %}", LC),
    ("break_in_set_block", "{% for i in l %}{% set x %}a{{ i }}{% if i == 1 %}{% break %}{% endif %}{% endset %}{{ x }}{% endfor %}", LC),
    ("break_outside_loop", "{% if l %}{% break %}{% endif %}", LC),
    ("break_in_for_else", "{% for i in e %}{% else %}{% break %}{% endfor %}", LC),
    ("break_in_macro", "{% for i in l %}{% macro m() %}{% break %}{% endmacro %}{% endfor %}", LC),
    ("break_in_call_block", "{% macro m() %}{{ caller() }}{% endmacro %}{% for i in l %}{% call m() %}{% break %}{% endcall %}{% endfor %}", LC),
    ("break_without_extension", "{% for i in l %}{% break %}{% endfor %}"),
    ("break_as_name", "{% set break = 1 %}{{ break }}", LC),
    ("loop_revindex_filtered", "{% for i in l if i > 1 %}{{ loop.revindex }}{{ loop.revindex0 }},{% endfor %}"),
    ("loop_length_filtered_single", "{% for i in l if i == 2 %}{{ loop.length }}{{ loop.revindex }}{% endfor %}"),
    ("loop_changed_args", "{% for i in [1, 2, 3, 4] %}{{ 'T' if loop.changed(i // 2, 'x') else 'F' }}{% endfor %}"),
    ("loop_changed_no_args", "{% for i in l %}{{ 'T' if loop.changed() else 'F' }}{% endfor %}"),
    ("loop_depth_nested", "{% for i in [1] %}{{ loop.depth }}{% for j in [1] %}{{ loop.depth }}{% endfor %}{% endfor %}"),
    # if
    ("if_elif_else", "{% if x > 5 %}a{% elif x > 2 %}b{% else %}c{% endif %}"),
    ("if_multiple_elif", "{% if x == 1 %}1{% elif x == 2 %}2{% elif x == 3 %}3{% endif %}"),
    ("if_inline_test", "{% if x is odd and x > 1 %}y{% endif %}"),
    # set
    ("set", "{% set a = 5 %}{{ a }}"),
    ("set_multiple", "{% set a, b = 1, 2 %}{{ a }}{{ b }}"),
    ("set_unpack_list", "{% set a, b = [1, 2] %}{{ b }}"),
    ("set_unpack_string", "{% set a, b = 'xy' %}{{ a }}-{{ b }}"),
    ("set_block_unpack", "{% set a, b %}xy{% endset %}{{ a }}-{{ b }}"),
    ("set_block", "{% set blk %}inner {{ x }}{% endset %}[{{ blk }}]"),
    ("set_block_filter", "{% set blk | upper %}inner{% endset %}{{ blk }}"),
    ("set_overrides_context", "{% set x = 10 %}{{ x }}"),
    ("namespace", "{% set ns = namespace(c=0) %}{% for i in l %}{% set ns.c = ns.c + i %}{% endfor %}{{ ns.c }}"),
    ("namespace_attr", "{% set ns = namespace() %}{% set ns.a = 1 %}{{ ns.a }}"),
    ("namespace_from_dict", "{% set ns = namespace(d) %}{{ ns.b }}"),
    ("namespace_in_with", "{% set ns = namespace(a=1) %}{% with %}{% set ns.a = 2 %}{% endwith %}{{ ns.a }}"),
    ("namespace_in_macro", "{% set ns = namespace(a=1) %}{% macro m() %}{% set ns.a = ns.a + 1 %}{% endmacro %}{{ m() }}{{ m() }}{{ ns.a }}"),
    ("namespace_set_block", "{% set ns = namespace() %}{% set ns.a %}x{{ x }}{% endset %}{{ ns.a }}"),
    ("namespace_subscript", "{% set ns = namespace({'a': 1}, b=2) %}{{ ns['a'] }}{{ ns.b }}"),
    ("namespace_missing_attr", "{% set ns = namespace() %}[{{ ns.a }}]"),
    ("namespace_set_on_dict", "{% set m = {} %}{% set m.a = 1 %}"),
    ("namespace_set_on_undefined", "{% set nope.a = 1 %}"),
    ("namespace_keeps_loop", "{% set ns = namespace() %}{% for i in l %}{% set ns.x = loop %}{% endfor %}{{ ns.x.index }}{{ ns.x.length }}{{ ns.x.revindex }}{{ 'T' if ns.x.last else 'F' }}"),
    ("namespace_keeps_filtered_loop", "{% set ns = namespace() %}{% for i in l if i > 1 %}{% set ns.x = loop %}{% endfor %}{{ ns.x.index }}{{ ns.x.length }}{{ ns.x.revindex0 }}"),
    ("namespace_keeps_broken_loop", "{% set ns = namespace() %}{% for i in l if i > 0 %}{% set ns.x = loop %}{% break %}{% endfor %}{{ ns.x.index }}{{ ns.x.length }}{{ ns.x.revindex }}", LC),
    ("namespace_keeps_loop_changed", "{% set ns = namespace() %}{% for i in l %}{% set ns.x = loop %}{% endfor %}{{ 'T' if ns.x.changed(1) else 'F' }}{{ 'T' if ns.x.changed(1) else 'F' }}"),
    ("namespace_in_tuple_target", "{% set ns = namespace() %}{% set ns.a, b = 1, 2 %}{{ ns.a }}{{ b }}"),
    ("namespace_in_for_target", "{% set ns = namespace() %}{% for ns.a in [1] %}{% endfor %}"),
    ("namespace_print", "{% set ns = namespace(a=1) %}{{ ns }}"),
    ("namespace_is_mapping", "{% set ns = namespace(a=1) %}{{ 'T' if ns is mapping else 'F' }}"),
    ("namespace_iterate", "{% set ns = namespace(a=1) %}{% for k in ns %}{{ k }}{% endfor %}"),
    ("namespace_no_dict_methods", "{% set ns = namespace(a=1) %}{{ ns.get('a') }}"),
    ("set_nested_target", "{% set (a, b), c = [[1, 2], 3] %}{{ a }}{{ b }}{{ c }}"),
    # with
    ("with", "{% with a = 1 %}{{ a }}{% endwith %}[{{ a }}]"),
    ("with_multiple", "{% with a = 1, b = 2 %}{{ a + b }}{% endwith %}"),
    ("with_set_inside", "{% with %}{% set a = 1 %}{{ a }}{% endwith %}[{{ a }}]"),
    # macro
    ("macro", "{% macro m(a, b=2) %}{{ a }}-{{ b }}{% endmacro %}{{ m(1) }} {{ m(1, b=3) }} {{ m(b=4, a=5) }}"),
    ("macro_missing_arg", "{% macro m(a) %}[{{ a }}]{% endmacro %}{{ m() }}"),
    ("macro_varargs", "{% macro m() %}{% for i in varargs %}{{ i }},{% endfor %}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_kwargs", "{% macro m() %}{{ kwargs.k }}{% endmacro %}{{ m(k=3) }}"),
    ("macro_varargs_print", "{% macro m() %}{{ varargs }}{{ kwargs }}{% endmacro %}{{ m(1, 2, k=3) }}"),
    ("macro_too_many_args", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_unknown_kwarg", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, z=2) }}"),
    ("macro_default_refers_arg", "{% macro m(a, b=a) %}{{ b }}{% endmacro %}{{ m(5) }}"),
    ("macro_name", "{% macro m(a, b) %}{% endmacro %}{{ m.name }}|{{ m.arguments|join(',') }}"),
    ("macro_catch_flags", "{% macro m(a) %}{{ varargs }}{% endmacro %}{% for f in [m.catch_varargs, m.catch_kwargs, m.caller] %}{{ 'T' if f else 'F' }}{% endfor %}"),
    ("macro_kwarg_fills_later_arg", "{% macro m(a, b=1, c=2) %}{{ a }}{{ b }}{{ c }}{% endmacro %}{{ m(0, c=5) }}"),
    ("macro_kwarg_repeats_positional", "{% macro m(a) %}{{ a }}{% endmacro %}{{ m(1, a=2) }}"),
    ("macro_extra_kwarg_caught", "{% macro m(a) %}{{ a }}{% for k in kwargs %}{{ k }}{% endfor %}{% endmacro %}{{ m(1, z=2) }}"),
    ("macro_kwargs_order", "{% macro m() %}{% for k in kwargs %}{{ k }}{% endfor %}{% endmacro %}{{ m(z=1, a=2, m=3) }}"),
    ("macro_missing_arg_shadows", "{% macro m(x) %}[{{ x }}]{% endmacro %}{{ m() }}"),
    ("macro_default_lexical", "{% set g = 'top' %}{% macro m(a=g) %}{{ a }}{% endmacro %}{% macro o(g) %}{{ m() }}{% endmacro %}{{ o('inner') }}"),
    ("macro_default_sees_kwargs", "{% macro m(a=kwargs) %}{{ a.x }}:{{ kwargs.x }}{% endmacro %}{{ m(x=7) }}"),
    ("macro_assigned_varargs_not_caught", "{% macro m() %}{% set varargs = ['local'] %}{% for v in varargs %}{{ v }}{% endfor %}{% endmacro %}{{ 'T' if m.catch_varargs else 'F' }}|{{ m() }}"),
    ("macro_assigned_varargs_rejects_extra", "{% macro m() %}{% set varargs = [1] %}{{ varargs|length }}{% endmacro %}{{ m(1) }}"),
    ("macro_varargs_read_before_set", "{% macro m() %}{% for v in varargs %}{{ v }}{% endfor %}{% set varargs = [] %}{% endmacro %}{{ m(1, 2) }}"),
    ("macro_for_target_kwargs", "{% macro m() %}{% for kwargs in [1] %}{{ kwargs }}{% endfor %}{% endmacro %}{{ 'T' if m.catch_kwargs else 'F' }}"),
    ("macro_with_kwarg_label", "{% macro f(kwargs) %}{% endmacro %}{% macro m() %}{% with x = f(kwargs=1) %}{{ kwargs.z }}{% endwith %}{% endmacro %}{{ m(z=7) }}"),
    ("macro_inner_param_varargs", "{% macro m() %}{% macro n(varargs) %}{{ varargs }}{% endmacro %}{{ n(3) }}{% endmacro %}{{ 'T' if m.catch_varargs else 'F' }}{{ m() }}"),
    ("macro_param_named_varargs", "{% macro m(varargs) %}{{ varargs }}{% endmacro %}{{ m(7) }}"),
    ("macro_default_later_arg", "{% macro m(a, b=a~x, x=7) %}{{ b }}|{{ x }}{% endmacro %}{{ m(5) }}"),
    ("macro_body_name_not_bound", "{% macro m() %}[{{ name }}{{ arguments }}]{% endmacro %}{{ m() }}"),
    ("macro_returns_markup", "{% macro m() %}<b>{% endmacro %}{{ m() }}"),
    ("macro_context_access", "{% macro m() %}{{ x }}{% endmacro %}{{ m() }}"),
    ("macro_recursive", "{% macro f(n) %}{{ n }}{% if n > 0 %}{{ f(n - 1) }}{% endif %}{% endmacro %}{{ f(3) }}"),
    ("macro_result_filtered", "{% macro m(v) %}<{{ v }}>{% endmacro %}{{ m('a')|upper }}"),
    ("caller", "{% macro m() %}[{{ caller() }}]{% endmacro %}{% call m() %}body{% endcall %}"),
    ("caller_args", "{% macro m() %}{% for i in [1, 2] %}{{ caller(i) }}{% endfor %}{% endmacro %}{% call(v) m() %}<{{ v }}>{% endcall %}"),
    ("caller_defined", "{% macro m() %}{{ caller is defined }}{% endmacro %}{{ m() }}"),
    ("caller_in_default", "{% macro m(a=caller) %}{{ a() }}{{ caller() }}{% endmacro %}{% call m() %}C{% endcall %}"),
    ("caller_explicit_with_default", "{% macro m(caller='no') %}{{ caller if caller is string else caller() }}{% endmacro %}{{ m() }}|{% call m() %}C{% endcall %}"),
    ("caller_truthy", "{% macro m() %}{{ 'T' if caller else 'F' }}{% if caller %}{{ caller() }}{% endif %}{% endmacro %}{% call m() %}C{% endcall %}|{{ 'T' if m else 'F' }}"),
    ("macro_default_reassigned_global", "{% set y = 1 %}{% macro m(a=y) %}{{ a }}{% endmacro %}{% set y = 2 %}{{ m() }}"),
    ("macro_body_lexical_scope", "{% set g = 'top' %}{% macro m() %}{{ g }}{% endmacro %}{% macro o(g) %}{{ m() }}{% endmacro %}{{ o('inner') }}"),
    ("caller_not_used", "{% macro m() %}x{% endmacro %}{% call m() %}y{% endcall %}"),
    ("caller_too_many_args", "{% macro m() %}{{ caller(1, 2) }}{% endmacro %}{% call(a) m() %}{{ a }}{% endcall %}"),
    ("caller_attributes", "{% macro m() %}{{ caller.arguments|join(',') }}:{{ caller(1) }}{% endmacro %}{% call(a, b=a) m() %}{{ a }}{{ b }}{% endcall %}"),
    ("caller_not_inherited", "{% macro n() %}{{ 'T' if caller is defined else 'F' }}{% endmacro %}{% macro m() %}{{ caller() }}{{ n() }}{% endmacro %}{% call m() %}y{% endcall %}"),
    # filter / raw / do / misc
    ("filter_block", "{% filter upper %}abc {{ x }}{% endfilter %}"),
    ("filter_block_chain", "{% filter upper|replace('B', 'x') %}abc{% endfilter %}"),
    ("filter_block_args", "{% filter center(7) %}abc{% endfilter %}"),
    ("raw", "{% raw %}{{ x }}{% if %}{% endraw %}"),
    ("comment", "a{# comment {{ x }} #}b"),
    ("comment_multiline", "a{# line1\nline2 #}b"),
    ("comment_begin_at_end", "a{#"),
    ("comment_begin_dash_at_end", "a{#-"),
    ("comment_begin_plus_at_end", "a{#+"),
    ("do", "{% do l.append(4) %}{% for i in l %}{{ i }},{% endfor %}", DO),
    ("do_without_extension", "{% do l.append(4) %}"),
    ("autoescape_block", "{% autoescape true %}{{ '<a>' }}{% endautoescape %}|{{ '<a>' }}"),
    ("autoescape_block_off", "{% autoescape false %}{{ '<a>' }}{% endautoescape %}"),
    ("unknown_tag", "{% frobnicate %}"),
    ("for_implicit_tuple", "{% for x in 1, 2 %}{{ x }}{% endfor %}"),
    ("for_unpack_filter", "{% for a, b in [[1, 2]] if a %}{{ a }}{{ b }}{% endfor %}"),
    ("for_nested_target", "{% for (a, b), c in [[[1, 2], 3]] %}{{ a }}{{ b }}{{ c }}{% endfor %}"),
    ("for_nested_target_inner", "{% for a, (b, c) in [[1, [2, 3]]] %}{{ a }}{{ b }}{{ c }}{% endfor %}"),
    ("for_nested_target_mismatch", "{% for (a, b), c in [[[1, 2, 4], 3]] %}{{ a }}{% endfor %}"),
    ("for_trailing_comma_target", "{% for a, in [[1], [2]] %}{{ a }}{% endfor %}"),
    ("for_empty_tuple_target", "{% for () in [[]] %}x{% endfor %}"),
    ("for_loop_target", "{% for loop in l %}{{ loop }}{% endfor %}"),
    ("for_nested_loop_target", "{% for a, (loop, b) in [[1, [2, 3]]] %}{% endfor %}"),
    ("set_trailing_comma_target", "{% set a, = [1] %}{{ a }}"),
    ("loop_changed_kwargs", "{% for i in [1, 2] %}{{ loop.changed(a=i) }}{% endfor %}"),
    ("for_paren_single_tuple", "{% for (a,) in [[1]] %}{{ a }}{% endfor %}"),
    ("if_tuple", "{% if l, s %}y{% endif %}"),
]
