"""Attribute access, subscripts and slicing."""
CONTEXT = {"l": [3, 1, 2, 5], "s": "Hello World", "d": {"a": 1, "b": {"c": 2}, "key with space": 3, "items": "own"},
           "users": [{"name": "bob"}, {"name": "alice"}]}
CASES = [
    ("index", "{{ l[0] }}"),
    ("index_negative", "{{ l[-1] }}"),
    ("index_out_of_range", "[{{ l[10] }}]"),
    ("index_string", "{{ s[1] }}"),
    ("index_string_negative", "{{ s[-1] }}"),
    ("slice_from", "{{ l[1:] }}"),
    ("slice_to", "{{ l[:2] }}"),
    ("slice_step", "{{ l[::2] }}"),
    ("slice_reverse", "{{ l[::-1] }}"),
    ("slice_negative", "{{ l[-2:] }}"),
    ("slice_string", "{{ s[0:5] }}"),
    ("slice_string_reverse", "{{ s[::-1] }}"),
    ("dot_attr", "{{ d.a }}"),
    ("item_attr", "{{ d['a'] }}"),
    ("nested_dot", "{{ d.b.c }}"),
    ("nested_item", "{{ d['b']['c'] }}"),
    ("item_with_space", "{{ d['key with space'] }}"),
    ("item_variable_key", "{% set k = 'a' %}{{ d[k] }}"),
    ("dot_index", "{{ l.0 }}"),
    ("list_of_dicts", "{{ users[1].name }}"),
    ("missing_attr", "[{{ d.missing }}]"),
    ("missing_nested_attr", "[{{ d.missing.deeper }}]"),
    ("dict_key_shadows_method", "{{ d['items'] }}"),
    ("dot_shadows_method", "{{ d.items is callable }}"),
    ("literal_subscript", "{{ [1, 2, 3][1] }}"),
    ("literal_dict_subscript", "{{ {'a': 'x'}['a'] }}"),
    ("string_literal_index", "{{ 'abc'[0] }}"),
    ("subscript_int", "[{{ x[0] }}]", {"ctx": {"x": 3}}),
    ("subscript_on_call", "{{ range(5)[2] }}"),
    ("slice_step_only", "{{ l[::2] }}"),
    ("slice_both_ends", "{{ l[1:-1] }}|{{ l[:] }}"),
    ("slice_tuple", "{{ (1, 2, 3)[1:] }}"),
    ("slice_string_clamped", "{{ 'abc'[5:1:-1] }}"),
    ("slice_then_index", "{{ l[0:2][1] }}"),
    ("slice_step_zero", "{{ l[::0] }}"),
    ("dot_index_chain", "{{ d.b.c }}{{ users.1.name }}"),
    ("slice_extreme_step", "{{ l[1::9223372036854775807] }}|{{ l[::-9223372036854775807-1] }}"),
    ("tuple_index", "[{{ l[1, 2] }}][{{ l[] }}]"),
]
