"""Builtin tests (`is` operator). Results print as T/F so that bool repr (output.py) does not mask them."""
CONTEXT = {"x": 3, "y": 2.5, "s": "hello", "S": "HELLO", "l": [1, 2], "d": {"a": 1}, "n": None, "t": True, "e": ""}
CASES = [
    ("boolean", "{{ 'T' if t is boolean else 'F' }}{{ 'T' if x is boolean else 'F' }}"),
    ("callable", "{{ 'T' if range is callable else 'F' }}{{ 'T' if x is callable else 'F' }}"),
    ("defined", "{{ 'T' if x is defined else 'F' }}{{ 'T' if nope is defined else 'F' }}"),
    ("undefined", "{{ 'T' if nope is undefined else 'F' }}{{ 'T' if x is undefined else 'F' }}"),
    ("divisibleby_space", "{{ 'T' if 9 is divisibleby 3 else 'F' }}"),
    ("divisibleby_call", "{{ 'T' if 9 is divisibleby(4) else 'F' }}"),
    ("eq", "{{ 'T' if x is eq 3 else 'F' }}{{ 'T' if x is equalto 4 else 'F' }}"),
    ("ne", "{{ 'T' if x is ne 3 else 'F' }}"),
    ("greaterthan_lessthan", "{{ 'T' if x is greaterthan 2 else 'F' }}{{ 'T' if x is lessthan 2 else 'F' }}"),
    ("lt_le_gt_ge", "{{ 'T' if x is lt 4 else 'F' }}{{ 'T' if x is le 3 else 'F' }}{{ 'T' if x is gt 4 else 'F' }}{{ 'T' if x is ge 3 else 'F' }}"),
    ("escaped", "{{ 'T' if s is escaped else 'F' }}{{ 'T' if s|e is escaped else 'F' }}"),
    ("even_odd", "{{ 'T' if x is even else 'F' }}{{ 'T' if x is odd else 'F' }}"),
    ("false_true", "{{ 'T' if false is false else 'F' }}{{ 'T' if 0 is false else 'F' }}{{ 'T' if true is true else 'F' }}{{ 'T' if 1 is true else 'F' }}"),
    ("filter", "{{ 'T' if 'upper' is filter else 'F' }}{{ 'T' if 'nope' is filter else 'F' }}"),
    ("test", "{{ 'T' if 'odd' is test else 'F' }}{{ 'T' if 'nope' is test else 'F' }}"),
    ("float", "{{ 'T' if y is float else 'F' }}{{ 'T' if x is float else 'F' }}"),
    ("integer", "{{ 'T' if x is integer else 'F' }}{{ 'T' if y is integer else 'F' }}{{ 'T' if t is integer else 'F' }}"),
    ("in", "{{ 'T' if 1 is in l else 'F' }}{{ 'T' if 5 is in l else 'F' }}"),
    ("iterable", "{{ 'T' if l is iterable else 'F' }}{{ 'T' if s is iterable else 'F' }}{{ 'T' if x is iterable else 'F' }}"),
    ("lower_upper", "{{ 'T' if s is lower else 'F' }}{{ 'T' if S is upper else 'F' }}{{ 'T' if s is upper else 'F' }}"),
    ("mapping", "{{ 'T' if d is mapping else 'F' }}{{ 'T' if l is mapping else 'F' }}"),
    ("none", "{{ 'T' if n is none else 'F' }}{{ 'T' if x is none else 'F' }}"),
    ("not_none", "{{ 'T' if x is not none else 'F' }}"),
    ("number", "{{ 'T' if x is number else 'F' }}{{ 'T' if y is number else 'F' }}{{ 'T' if s is number else 'F' }}"),
    ("sameas", "{{ 'T' if n is sameas none else 'F' }}{{ 'T' if x is sameas 3 else 'F' }}"),
    ("sameas_container", "{% set a = [1] %}{% set b = a %}{{ 'T' if b is sameas a else 'F' }}{{ 'T' if a is sameas [1] else 'F' }}{{ 'T' if l is sameas l else 'F' }}"),
    ("sequence", "{{ 'T' if l is sequence else 'F' }}{{ 'T' if s is sequence else 'F' }}{{ 'T' if x is sequence else 'F' }}"),
    ("string", "{{ 'T' if s is string else 'F' }}{{ 'T' if x is string else 'F' }}"),
    ("is_not", "{{ 'T' if x is not even else 'F' }}"),
    ("test_in_condition", "{% if x is odd %}odd{% endif %}"),
    ("test_precedence_and", "{{ 'T' if x is odd and y is float else 'F' }}"),
    ("test_on_filter", "{{ 'T' if s|upper is upper else 'F' }}"),
    ("unknown_test", "{{ x is nonexistent }}"),
    ("print_test_result", "{{ x is odd }}"),
    ("select_with_test", "{{ [1, 2, 3, 4]|select('even')|list }}"),
    ("is_not_with_parens", "{{ 'T' if 4 is not divisibleby(3) else 'F' }}"),
]
