"""Undefined values: default, strict and chainable undefined behaviour."""
CONTEXT = {"d": {"a": 1}, "n": None}
STRICT = {"env": {"undefined": "strict"}}
CHAIN = {"env": {"undefined": "chainable"}}
DEBUG = {"env": {"undefined": "debug"}}
CASES = [
    ("print", "[{{ nope }}]"),
    ("attr_of_undefined", "[{{ nope.attr }}]"),
    ("item_of_undefined", "[{{ nope['x'] }}]"),
    ("attr_of_none", "[{{ n.attr }}]"),
    ("call_undefined", "[{{ nope() }}]"),
    ("method_of_undefined", "[{{ nope.upper() }}]"),
    ("iterate_undefined", "[{% for i in nope %}x{% endfor %}]"),
    ("length_undefined", "{{ nope|length }}"),
    ("undefined_in_concat", "[{{ 'a' ~ nope }}]"),
    ("undefined_plus", "[{{ nope + 1 }}]"),
    ("undefined_compare", "{{ nope == none }}"),
    ("undefined_truthiness", "{% if nope %}t{% else %}f{% endif %}"),
    ("undefined_in_test", "{{ nope is defined }}"),
    ("undefined_attr_in_test", "{{ nope.attr is defined }}"),
    ("undefined_string_filter", "[{{ nope|string }}]"),
    ("undefined_upper_filter", "[{{ nope|upper }}]"),
    ("undefined_list_filter", "{{ nope|list|length }}"),
    ("undefined_default_chain", "{{ nope.attr|default('dflt') }}"),
    ("undefined_join", "[{{ nope|join(',') }}]"),
    ("undefined_eq_undefined", "{{ nope == nope2 }}{{ nope != none }}{{ none == none }}{{ n == none }}"),
    ("not_undefined_not_none", "{{ not nope }}{{ not none }}"),
    ("undefined_in_none_list", "{{ nope in [none] }}{{ none in [none] }}"),
    ("none_is_defined", "{{ n is defined }}{{ n is undefined }}{{ none is defined }}"),
    ("none_truthiness", "{% if n %}t{% else %}f{% endif %}"),
    ("none_concat_left", "[{{ n ~ 'a' }}][{{ nope ~ 'a' }}]"),
    ("none_in_list", "{{ [n, 1] }}"),
    ("undefined_in_list", "{{ [nope, 1] }}"),
    ("none_join", "{{ [n, 1]|join(',') }}"),
    ("set_none", "{% set x = none %}{{ x is defined }}[{{ x }}]"),
    ("macro_default_none", "{% macro m(a=none) %}{{ a is defined }}[{{ a }}]{% endmacro %}{{ m() }}"),
    ("macro_missing_arg", "{% macro m(a) %}{{ a is defined }}[{{ a }}]{% endmacro %}{{ m() }}"),
    ("filter_out_none", "{% for i in [none, 1, 'a'] if i is not none %}{{ i }}{% endfor %}|{{ n is none }}{{ nope is none }}"),
    ("attr_of_none_default", "{{ n.attr|default('d') }}"),
    ("none_string_filters", "{{ n|upper }}|{{ n|lower }}|{{ n|replace('o', '0') }}|{{ n|center(6) }}"),
    ("strict_print", "{{ nope }}", STRICT),
    ("strict_is_defined", "{{ nope is defined }}", STRICT),
    ("strict_default", "{{ nope|default('d') }}", STRICT),
    ("strict_if", "{% if nope %}x{% endif %}", STRICT),
    ("strict_defined_attr", "{{ d.a }}", STRICT),
    ("strict_missing_attr", "{{ d.zz }}", STRICT),
    ("chainable_deep", "[{{ nope.a.b.c }}]", CHAIN),
    # default Undefined: printing, truth and iteration are fine, other uses fail
    ("undefined_neg", "[{{ -nope }}]"),
    ("undefined_lt", "{{ nope < 1 }}"),
    ("set_from_undefined_attr", "{% set x = nope %}[{{ x.a }}]"),
    ("missing_item_then_attr", "[{{ d['zz'].y }}]"),
    ("missing_index_then_attr", "{% set l = [1] %}[{{ l[5].y }}]"),
    ("none_attr_attr", "[{{ n.a.b }}]"),
    ("missing_attr_call", "[{{ d.zz() }}]"),
    ("undefined_sum_first", "{{ nope|sum }}[{{ nope|first }}]{{ nope|list }}"),
    ("undefined_for_method", "{% for x in nope.items() %}{% endfor %}"),
    ("macro_missing_arg_attr", "{% macro m(a) %}[{{ a.b }}]{% endmacro %}{{ m() }}"),
    ("undefined_stored_in_dict", "{% set m = {'a': nope} %}[{{ m.a }}][{{ m.a.b }}]"),
    ("null_member_attr", "[{{ m.a.b }}][{{ m['a'].b }}][{{ l[0].b }}]", {"ctx": {"m": {"a": None}, "l": [None]}}),
    ("null_member_strict", "[{{ m.a }}][{{ m.a is none }}]", {"ctx": {"m": {"a": None}}, "env": {"undefined": "strict"}}),
    # filters that convert or look into their argument fail on undefined
    ("undefined_int_filter", "{{ nope|int }}"),
    ("undefined_float_filter", "{{ nope|float }}"),
    ("undefined_attr_filter", "[{{ nope|attr('x') }}]"),
    ("undefined_map_attribute", "{{ [nope]|map(attribute='x')|list }}"),
    ("undefined_tojson", "{{ nope|tojson }}"),
    ("undefined_dictsort", "{{ nope|dictsort }}"),
    ("undefined_is_callable", "{{ nope is callable }}{{ nope is string }}"),
    ("undefined_pprint", "{{ nope|pprint }}"),
    ("undefined_first_hint", "{{ (nope|first).x }}"),
    ("undefined_range", "{{ range(nope) }}"),
    ("undefined_in_dict_repr", "{{ dict(a=nope) }}"),
    ("undefined_as_filter_name", "{{ [1]|map(nope)|list }}"),
    ("undefined_format", "{{ nope|format(1) }}"),
    ("undefined_indent_wordwrap", "{{ nope|indent }}|{{ nope|wordwrap }}"),
    ("strict_truncate", "{{ nope|truncate(3) }}", STRICT),
    # StrictUndefined: only the defined tests and the default filter accept it
    ("strict_iterate", "{% for i in nope %}{% endfor %}", STRICT),
    ("strict_eq", "{{ nope == 1 }}", STRICT),
    ("strict_concat", "{{ 'a' ~ nope }}", STRICT),
    ("strict_length", "{{ nope|length }}", STRICT),
    ("strict_not", "{{ not nope }}", STRICT),
    ("strict_in", "{{ 1 in nope }}", STRICT),
    ("strict_upper", "{{ nope|upper }}", STRICT),
    ("strict_is_none", "{{ nope is none }}", STRICT),
    ("strict_set_unused", "{% set x = nope %}ok", STRICT),
    ("strict_or_short_circuit", "{{ 1 or nope }}", STRICT),
    ("strict_missing_attr_default", "{{ d.zz|default('x') }}{{ d.zz is defined }}", STRICT),
    ("strict_ternary", "{{ 'a' if nope is defined else 'b' }}", STRICT),
    # ChainableUndefined: attributes and items of it are undefined too
    ("chainable_item", "[{{ nope['a'].b }}]", CHAIN),
    ("chainable_call", "{{ nope.a() }}", CHAIN),
    ("chainable_default", "{{ nope.a.b|default('d') }}", CHAIN),
    ("chainable_plus", "{{ nope.a + 1 }}", CHAIN),
    ("chainable_missing_attr", "[{{ d.zz.yy }}]", CHAIN),
    # DebugUndefined prints what is missing
    ("debug_print", "{{ nope }}", DEBUG),
    ("debug_missing_attr", "{{ d.zz }}|{{ d[1] }}|{{ d['k'] }}", DEBUG),
    ("debug_concat", "{{ 'a' ~ nope }}", DEBUG),
    ("debug_attr", "{{ nope.a }}", DEBUG),
    ("debug_if", "{% if nope %}t{% else %}f{% endif %}{{ nope|default('d') }}", DEBUG),
]
