"""Whitespace control: -/+ modifiers, trim_blocks, lstrip_blocks, keep_trailing_newline."""
TB = {"trim_blocks": True}
LB = {"lstrip_blocks": True}
BOTH = {"trim_blocks": True, "lstrip_blocks": True}
CASES = [
    ("expr_minus", "a {{- ' b ' -}} c"),
    ("block_minus", "a  {%- if true %} x {% endif -%}  b"),
    ("comment_minus", "a  {#- c -#}  b"),
    ("minus_strips_newlines", "a\n\n  {%- if true -%}\n\n  x\n{%- endif %}"),
    ("block_newline_default", "{% if true %}\nx\n{% endif %}\ny"),
    ("trailing_newline_default", "x\n"),
    ("trailing_newlines_two", "x\n\n"),
    ("trailing_newline_after_block", "{% if true %}\n  x\n{% endif %}\n"),
    ("keep_trailing_newline", "x\n", {"env": {"keep_trailing_newline": True}}),
    ("trim_blocks", "{% if true %}\nx\n{% endif %}\ny", {"env": TB}),
    ("trim_blocks_comment", "{# c #}\nx", {"env": TB}),
    ("trim_blocks_expression_untouched", "{{ 'a' }}\nb", {"env": TB}),
    ("trim_blocks_crlf", "{% if true %}\r\nx{% endif %}", {"env": TB}),
    ("lstrip_blocks", "  {% if true %}x{% endif %}", {"env": LB}),
    ("lstrip_blocks_tabs", "\t {% if true %}x{% endif %}", {"env": LB}),
    ("lstrip_blocks_not_after_text", "a {% if true %}x{% endif %}", {"env": LB}),
    ("lstrip_blocks_comment", "  {# c #}x", {"env": LB}),
    ("lstrip_blocks_expression_untouched", "  {{ 'x' }}", {"env": LB}),
    ("both", "<ul>\n  {% for i in [1, 2] %}\n  <li>{{ i }}</li>\n  {% endfor %}\n</ul>", {"env": BOTH}),
    ("plus_disables_lstrip", "  {%+ if true %}x{% endif %}", {"env": LB}),
    ("plus_disables_trim", "{% if true +%}\nx{% endif %}", {"env": TB}),
    ("minus_with_trim", "a\n  {%- if true %}\nx\n{% endif %}", {"env": BOTH}),
    ("raw_whitespace", "{%- raw -%}  {{ x }}  {%- endraw -%}"),
    ("raw_trim_blocks", "{% raw %}\nx{% endraw %}\ny", {"env": TB}),
    ("macro_whitespace", "{% macro m() %}\n  m\n{% endmacro %}[{{ m() }}]"),
    ("set_block_whitespace", "{% set v %}\n  v\n{% endset %}[{{ v }}]", {"env": BOTH}),
    ("crlf_text", "a\r\nb"),
    ("newline_sequence", "a\nb", {"env": {"newline_sequence": "\r\n"}}),
    ("newline_sequence_cr", "a\nb\n\nc", {"env": {"newline_sequence": "\r"}}),
    ("newline_sequence_string", "{{ 'a\nb' }}|{{ 'c\\nd' }}", {"env": {"newline_sequence": "\r\n"}}),
    ("newline_sequence_trim_blocks", "{% if true %}\r\nx\n{% endif %}\ny", {"env": {"newline_sequence": "\r\n", "trim_blocks": True}}),
    ("cr_text", "a\rb\r\rc"),
    ("crlf_trailing_newline", "a\r\n"),
    ("keep_trailing_newline_crlf", "x\r\n", {"env": {"keep_trailing_newline": True}}),
    ("only_newline", "\n"),
    ("trim_blocks_keeps_spaces", "{% if true %}  \nx{% endif %}", {"env": TB}),
    ("trim_blocks_comment_spaces", "{# c #}  \nx", {"env": TB}),
    ("expr_minus_strips_newlines", "{{ 'a' -}}\n\n  b"),
    ("raw_plus_lstrip", "a\n  {%+ raw -%}\n  x{% endraw %}", {"env": LB}),
    ("raw_minus_lstrip_trim", "a\n  {%- raw %}\n  x{% endraw %}", {"env": BOTH}),
    ("raw_body_starts_with_modifier", "{% raw %}-x{% endraw %}|{% raw %}+y{% endraw %}"),
    ("raw_plus_close_rejected", "{% raw +%}x{% endraw %}"),
    ("lstrip_trailing_whitespace", "a\n  ", {"env": LB}),
    ("lstrip_expression_trailing_space", "{{ 1 }}  ", {"env": LB}),
    ("lstrip_between_tags", "{% if true %}x{% endif %} {% if true %}y{% endif %}", {"env": LB}),
    ("minus_strips_unicode_space", "{{ 'a' -}}\u00a0\u2003b"),
    ("raw_minus_and_trim_blocks", "{% raw -%}  \n\n x{% endraw %}\n\ny", {"env": TB}),
]
