name: CI-windows-build

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  windows-msvc-build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        base-flags: ["", -DJINJA2CPP_CXX_STANDARD=17]
        build-config: [Release, Debug]
        build-platform: [x64]
        build-runtime: ["", /MT, /MD]
        build-shared: [FALSE, TRUE]

    steps:
    - uses: actions/checkout@v4

    # Setup MSVC environment
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.build-platform }}

    - name: Build
      shell: cmd
      env:
        INPUT_COMPILER: ${{ matrix.compiler }}
        INPUT_BASE_FLAGS: ${{ matrix.base-flags }}
        INPUT_BUILD_CONFIG: ${{ matrix.build-config }}
        INPUT_BUILD_SHARED: ${{ matrix.build-shared }}
        INPUT_EXTRA_FLAGS: ${{ matrix.extra_flags }}
        INPUT_BUILD_PLATFORM: ${{ matrix.build-platform }}
        INPUT_BUILD_RUNTIME: ${{ matrix.build-runtime }}
      run: |
        mkdir -p .build
        cd .build
        cmake --version
        cmake .. -G "NMake Makefiles" -Dvariant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -DCMAKE_BUILD_TYPE=%INPUT_BUILD_CONFIG% -DJINJA2CPP_MSVC_RUNTIME_TYPE="%INPUT_BUILD_RUNTIME%" -DJINJA2CPP_DEPS_MODE=internal -DJINJA2CPP_BUILD_SHARED=%INPUT_BUILD_SHARED% %INPUT_BASE_FLAGS% %INPUT_EXTRA_FLAGS%
        cmake --build . --config %INPUT_BUILD_CONFIG% --verbose

    - name: Test
      shell: cmd
      env:
        INPUT_BUILD_CONFIG: ${{ matrix.build-config }}
      run: |
        cd .build
        ctest -C %INPUT_BUILD_CONFIG% -V
